import personal from './content/personal.mjs';
import teams from './content/teams.mjs';
import committees from './content/committees.mjs';
import coordination from './content/coordination.mjs';
import review from './content/review.mjs';
import governance from './content/governance.mjs';
import finance from './content/finance.mjs';
import platform from './content/platform.mjs';
export const KNOWLEDGE_VERSION = '2026-10-10.1';
export const books = [personal, teams, committees, coordination, review, governance, finance, platform];
