// Explicit bindings: a new screen/command/canon item needs an editorial decision.
export const acceptanceArticles={
 A01:['urenstand'],A02:['urenstand'],A03:['winterplanning'],A04:['uren-vraag','uitvoering-correctie'],A05:['functie-erkennen'],A06:['functie-erkennen'],A07:['huishouden'],A08:['intakehulp','extra-uitvoerder'],A09:['gescheiden-ouders','privacy'],A10:['dossierkoppelingen'],
 A11:['inloggen','toegang-beheer'],A12:['teamuren-review'],A13:['taak-boeken','wachtlijst'],A14:['overnemen'],A15:['afmelden','afspraken-instellingen'],A16:['commissieplanning','concepten-sjablonen'],A17:['concepten-sjablonen','wijzigingsimpact'],A18:['wedstrijdvoorstellen','agenda'],A19:['sportlink'],A20:['meldingen','communicatieregels'],
 A21:['berichttemplates','verzendlog'],A22:['beleid','beleid-publiceren'],A23:['beleid','beleid-publiceren'],A24:['werkkaarten','acties'],A25:['commissieberichten','documenten','privacy'],A26:['uitzonderingen','financiele-basis','financiele-verwerking'],A27:['wachtlijst','reservehulp','opleidingen','werkdruk','passend-aanbod-beoordelen'],A28:['instructie-feedback','vrijwilligerspot'],A29:['intakehulp','uitvoering-correctie'],A30:['seizoensovergang','rapporten'],
};
export const proposalArticles={
 '01':['urenstand','functie-erkennen'],'02':['dossierkoppelingen','huishouden'],'03':['starten','toegang-beheer'],'04':['concepten-sjablonen'],'05':['wedstrijdvoorstellen'],'06':['wijzigingsimpact','wedstrijdvoorstellen'],'07':['sportlink'],'08':['passend-aanbod','taak-boeken'],'09':['passend-aanbod'],'10':['wachtlijst','reservehulp'],'11':['opleidingen','taak-boeken'],'12':['vaste-functie','vacature-opvolging'],'13':['passend-aanbod-beoordelen'],'14':['werkdruk'],
 '15':['acties'],'16':['werkkaarten','commissieberichten'],'17':['werkkaarten'],'18':['acties','commissieberichten'],'19':['instructie-feedback','vrijwilligerspot'],'20':['opleidingen','opleiding-beheer'],'21':['intakehulp'],'22':['uitvoering','uitvoering-correctie'],'23':['financiele-verwerking'],'24':['uitzonderingen'],'25':['beleid','beleid-publiceren'],'26':['berichttemplates','verzendlog'],'27':['seizoensovergang'],'28':['rapporten'],
};
export const mobileScreenArticles={home:['starten','urenstand','acties'],tasks:['taak-boeken','teamplaats','afmelden','wachtlijst','overnemen'],agenda:['agenda'],teams:['teamplaats','teamouder-start','verdeling','teamdoelen','teamoverdracht'],more:['starten'],actions:['acties'],notifications:['meldingen'],manage:['commissieplanning','uitvoering','teamuren-review','vragen-opvolgen'],profile:['profiel'],household:['huishouden','urenstand','extra-uitvoerder','uren-vraag'],policies:['beleid'],courses:['opleidingen'],opportunities:['vaste-functie'],messages:['berichten'],settings:['meldingen','privacy','online-status'],help:['hulpvragen'],install:['installeren'],reports:['rapporten'],finance:['vrijwilligerspot'],committees:['commissie-start','werkkaarten','documenten']};
export const clubSectionArticles={cockpit:['beheer-start'],organization:['vereniging-inrichten','afspraken-instellingen'],people:['personen-beheer','dossierkoppelingen'],access:['toegang-beheer'],committees:['commissie-start','documenten'],teams:['teamouder-start','teamdoelen','verdeling'],planning:['commissieplanning','taakcatalogus','clusters','wijzigingsimpact'],execution:['uitvoering','uitvoering-correctie'],requests:['vragen-opvolgen','uitzonderingen','uurvragen-beoordelen','teamuren-review','functie-erkennen'],policies:['beleid-publiceren'],courses:['opleiding-beheer'],communication:['berichttemplates','communicatieregels','verzendlog'],reports:['rapporten'],finance:['financiele-basis','financiele-verwerking','vrijwilligerspot'],seasons:['seizoen-inrichten','seizoenssluiting','seizoensovergang'],support:['supporttoestemming']};
export const platformSectionArticles={overview:['platformoverzicht'],tenants:['tenant-inrichten','tenant-uitnodigingen','tenant-status','tenant-modules'],staff:['platformrechten'],defaults:['platformstandaarden'],integrations:['integraties-platform'],support:['support-platform'],audit:['platformaudit']};
export const referencePageArticles={
 P00:['starten','inloggen','privacy','online-status','installeren'],P01:['urenstand','acties','agenda','passend-aanbod'],P02:['taak-boeken','wachtlijst','passend-aanbod','vaste-functie'],P03:['taak-voorbereiden','uitvoering','afmelden','uren-vraag'],P04:['huishouden','teamplaats','agenda'],P05:['overnemen'],P06:['agenda','commissieberichten'],P07:['sportlink','wedstrijdvoorstellen','wijzigingsimpact'],P08:['commissieplanning','concepten-sjablonen','clusters'],P09:['dossierkoppelingen','extra-uitvoerder','uitzonderingen','functie-erkennen','winterplanning','intakehulp'],P10:['commissie-start','documenten'],P11:['werkkaarten','documenten','acties'],P12:['teamouder-start','teamtaak-maken','teamdoelen','verdeling','reservehulp','teamoverdracht','teamfeedback'],P13:['acties'],P14:['berichten','meldingen','communicatieregels','verzendlog'],P15:['beleid','beleid-publiceren'],P16:['instructie-feedback','teamfeedback'],P17:['opleidingen','opleiding-beheer'],P18:['vaste-functie','vacature-opvolging','functie-erkennen'],P19:['rapporten','werkdruk','passend-aanbod-beoordelen'],P20:['financiele-basis','financiele-verwerking','betalingen','financiele-herziening','vrijwilligerspot'],P21:['berichttemplates','communicatieregels','verzendlog'],P22:['afspraken-instellingen','functiecatalogus','sportlink','ledenimport','toegang-beheer','installeren','seizoensovergang'],P23:['profiel','intakehulp'],
};
const bind=groups=>Object.fromEntries(Object.entries(groups).flatMap(([article,commands])=>commands.map(command=>[command,[article]])));
export const commandArticles={
 mobile:bind({
  'taak-boeken':['book_shift'],'overnemen':['accept_transfer','open_transfer'],'teamdoelen':['set_team_goal'],'clusters':['reserve_cluster'],'verdeling':['assign_member','apply_distribution'],'deadlines':['set_followup'],'reservehulp':['request_reserve'],'teamoverdracht':['prepare_handover','save_handover_draft','accept_handover','revoke_handover'],'taak-voorbereiden':['save_feedback','prepare_booking'],'hulpvragen':['ask_question'],'vragen-opvolgen':['answer_question','take_question'],'commissieberichten':['create_channel','send_message'],'meldingen':['mark_inbox_read','mark_all_inbox_read','save_preferences'],'privacy':['dismiss_help','reset_help'],'opleidingen':['enroll_course','withdraw_course'],'beleid':['open_policy','accept_policy'],'agenda':['rsvp_event'],'werkkaarten':['create_card','update_card','check_card_item','reply_card'],'instructie-feedback':['publish_instructions'],'afmelden':['report_obstruction','cancel_booking'],'teamtaak-maken':['create_team_task'],'commissieplanning':['create_club_task'],'teamuren-review':['review_team_credit','publish_team_credit'],'installeren':['save_push_subscription','revoke_push_subscription'],'uitvoering':['confirm_attendance','confirm_attendance_batch'],'wachtlijst':['join_waitlist'],'vaste-functie':['express_interest'],'profiel':['start_profile','save_profile'],'vereniging-inrichten':['save_club_contact'],'extra-uitvoerder':['invite_executor'],
 }),
 club:bind({
  'uurvragen-beoordelen':['take_hour_dispute','resolve_hour_dispute'],'functiecatalogus':['save_volunteer_role','revise_volunteer_role','save_vacancy','set_vacancy_state'],'vacature-opvolging':['follow_vacancy_interest'],'functie-erkennen':['recognize_vacancy_appointment'],'uitvoering':['confirm_attendance'],'uitvoering-correctie':['correct_attendance_award'],'berichttemplates':['save_template_draft','preview_template','queue_template_test','approve_template','publish_template'],'financiele-voorbereiding':['prepare_assessment'],'financiele-goedkeuring':['approve_assessment'],'financiele-verwerking':['finalize_assessment'],'uitzonderingen':['review_exception','finalize_exception'],'seizoenssluiting':['close_season'],'seizoensovergang':['rollover_season'],'vrijwilligerspot':['post_fund_entry'],'vereniging-inrichten':['save_organization','save_location'],'commissie-start':['save_committee_contact','add_committee_member','end_committee_member','save_committee'],'personen-beheer':['save_team','save_person','save_household','link_household_person','add_team_member','end_team_member'],'toegang-beheer':['invite_access','cancel_access_invitation','grant_access','revoke_access'],'supporttoestemming':['consent_support','end_support'],'taakcatalogus':['save_category','save_task_type','revise_task_type'],'opleiding-beheer':['save_course','save_qualification_type','save_course_session','register_qualification','revoke_qualification','certify_enrollment'],'beleid-publiceren':['save_policy_draft','publish_policy'],'seizoen-inrichten':['save_season'],'afspraken-instellingen':['save_settings'],
 }),
 platform:bind({
  'integraties-platform':['retry_delivery'],'tenant-uitnodigingen':['invite_administrator','cancel_administrator_invitation'],'tenant-inrichten':['onboard_administrator','create_tenant','update_tenant'],'tenant-seizoen':['onboard_season'],'tenant-status':['set_tenant_status'],'platformrechten':['grant_staff','revoke_staff'],'tenant-modules':['set_module'],'platformstandaarden':['save_default'],'support-platform':['request_support','revoke_support'],
 }),
};
