// Opt-in actual PWA readonly precision normalization on a new network-none
// PostgreSQL17 fixture. No hosted credentials, backup or existing DB is used.
import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {isDeepStrictEqual} from 'node:util';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {IMAGE} from '../scripts/pg17-capture-worker.mjs';
import {INITIAL_RESTORE_STARTUP} from '../scripts/staging-pwa-upgrade-restore.mjs';
import {CATALOG_QUERIES} from '../scripts/staging-capture-catalog.mjs';
import {aggregate} from '../scripts/staging-capture-queries.mjs';
import {PWA_DEPARSE_CONTEXT_SQL,publicDeparseContext,publicSourceDeparseNormalization,cloneDeparseSettingsSQL} from '../scripts/staging-pwa-restore-diagnostic.mjs';
const hash=value=>createHash('sha256').update(value).digest('hex'),literal=value=>"'"+value.replaceAll("'","''")+"'";
const catalogSql='SELECT jsonb_build_object('+Object.entries(CATALOG_QUERIES).map(([family,query])=>literal(family)+',('+aggregate(query)+')').join(',')+');';
const dataSql="SELECT jsonb_build_object('rows',count(*),'sha256',encode(sha256(convert_to(coalesce(string_agg(to_jsonb(t)::text,E'\\n' ORDER BY to_jsonb(t)::text),''),'UTF8')),'hex'),'float_bits',jsonb_agg(jsonb_build_array(encode(float8send(t.precise_double),'hex'),encode(float4send(t.precise_real),'hex')) ORDER BY id)) FROM public.pwa_lossless_fixture t;";
const ddl=`CREATE ROLE postgres LOGIN NOSUPERUSER NOBYPASSRLS;REVOKE USAGE ON SCHEMA public FROM PUBLIC;GRANT USAGE,CREATE ON SCHEMA public TO postgres;SET ROLE postgres;
 CREATE TABLE public.pwa_lossless_fixture(id integer PRIMARY KEY,precise_double double precision NOT NULL,precise_real real NOT NULL,
 happened_at timestamptz NOT NULL,fixed_date date NOT NULL,duration interval NOT NULL,
 CONSTRAINT pwa_lossless_threshold CHECK(precise_double >= '0.12345678901234568'::double precision
 AND precise_real >= '1.2345679'::real AND happened_at >= TIMESTAMPTZ '2026-10-09 12:34:56+00'
 AND fixed_date >= DATE '2026-10-09' AND duration >= INTERVAL '1 day 02:03:04'));
 INSERT INTO public.pwa_lossless_fixture VALUES
 (1,0.12345678901234568,1.2345679,'2026-10-09 12:34:56+00','2026-10-09','1 day 02:03:04'),
 (2,1.0000000000000002,16777216,'2026-10-10 12:34:56+00','2026-10-10','2 day 02:03:04'),
 (3,1.7976931348623157e+308,3.4028235e+38,'2026-10-11 12:34:56+00','2026-10-11','3 day 02:03:04');RESET ROLE;`;
const inspectFormat='{"id":{{json .Id}},"name":{{json .Name}},"image":{{json .Image}},"config_image":{{json .Config.Image}},"label":{{json (index .Config.Labels "cluvo.pwa.source-precision-test")}},"network":{{json .HostConfig.NetworkMode}},"ports":{{json .HostConfig.PortBindings}},"binds":{{json .HostConfig.Binds}},"mounts":{{json .Mounts}},"privileged":{{json .HostConfig.Privileged}},"log":{{json .HostConfig.LogConfig.Type}},"restart":{{json .HostConfig.RestartPolicy.Name}},"user":{{json .Config.User}}}';

test('actual owned PG17: PWA source0 normalizes only readonly snapshot sessions to3; live snapshot dump restores exact floats, rows and28 catalogs',
 {skip:process.env.CLUVO_PWA_SOURCE_PRECISION_NATIVE_TESTS!=='owned-pg17',timeout:90000},async t=>{
 const socket='unix:///run/user/1001/docker.sock',name='cluvo-pwa-source-precision-'+randomBytes(12).toString('hex');let id,imageId,created=false,removed=false,proof;
 const run=(args,input)=>spawnSync('/usr/bin/docker',['--host',socket,...args],{input,env:{PATH:'/usr/bin:/bin',LANG:'C.UTF-8'},timeout:30000,maxBuffer:4_000_000});
 const checked=(args,input)=>{const r=run(args,input);let diagnostic='OWNED_SOURCE_PRECISION_PROCESS_FAILED';if(r.status!==0){try{const candidates=r.stderr.toString().split('\n').map(line=>{try{return JSON.parse(line);}catch{return null;}});const v=candidates.find(x=>x?.owned_stage);if(!v)throw Error('NO_TYPED_HELPER_DIAGNOSTIC');if(['open_actual_local_libpq','source_connection_setting_zero','first_readonly_snapshot','first_catalog_and_rows','actual_export_bound_pg_dump','first_rollback','fresh_readonly_snapshot','fresh_rollback'].includes(v.owned_stage))diagnostic+=':'+v.owned_stage+':'+(['Failure','OSError','ImportError','ValueError','TypeError','AssertionError'].includes(v.error_kind)?v.error_kind:'UNKNOWN_KIND')+':'+(typeof v.safe_code==='string'&&/^[A-Z0-9_]{1,100}$/.test(v.safe_code)?v.safe_code:'UNKNOWN');}catch{const text=r.stderr.toString();const library=text.match(/lib[a-z0-9._+-]+\.so(?:\.[0-9]+)*/)?.[0];if(library)diagnostic+=':PUBLIC_RUNTIME_LIBRARY:'+library;else if(/ModuleNotFoundError/.test(text))diagnostic+=':PUBLIC_STDLIB_MODULE_MISSING';else if(/Fatal Python error/.test(text))diagnostic+=':PUBLIC_PYTHON_INIT_FAILED';else{const kind=text.match(/(SyntaxError|ImportError|AttributeError|TypeError|FileNotFoundError|RuntimeError|ValueError):/)?.[1];diagnostic+=':'+(kind??'UNCLASSIFIED_PUBLIC_RUNTIME');}}}assert.equal(r.status,0,diagnostic);assert.equal(r.stderr.length,0,'OWNED_SOURCE_PRECISION_PROCESS_WARNING');return r.stdout;};
 const sql=(database,text,{failure=false}={})=>{const r=run(['exec','-i',id,'psql','-X','-qtA','--no-password','--set=ON_ERROR_STOP=1','--set=VERBOSITY=sqlstate','-h','/restore','-U','supabase_admin','-d',database],'SET client_min_messages=warning;\n'+text);if(failure){assert.notEqual(r.status,0);assert.match(r.stderr.toString(),/23514/);return;}assert.equal(r.status,0,'OWNED_SOURCE_PRECISION_SQL_FAILED');assert.equal(r.stderr.length,0,'OWNED_SOURCE_PRECISION_SQL_WARNING');return r.stdout.toString().trim();};
 const json=(database,text)=>JSON.parse(sql(database,text));
 const guard=()=>{const v=JSON.parse(checked(['inspect',id,'--format',inspectFormat]).toString());assert.equal(v.id,id);assert.equal(v.name,'/'+name);assert.equal(v.label,name);assert.equal(v.image,imageId);assert.equal(v.config_image,IMAGE);assert.equal(v.user,'postgres');assert.equal(v.network,'none');assert.ok(v.ports===null||Object.keys(v.ports).length===0);assert.equal(v.binds,null);assert.ok(v.mounts.every(m=>m.Type==='tmpfs'));assert.equal(v.privileged,false);assert.equal(v.log,'none');assert.equal(v.restart,'no');};
 try{
  const image=JSON.parse(checked(['image','inspect',IMAGE,'--format','{"id":{{json .Id}},"digests":{{json .RepoDigests}}}']).toString());assert.ok(image.digests.includes(IMAGE));imageId=image.id;assert.equal(run(['inspect',name]).status,1);
  created=true;id=checked(['create','--pull=never','--name',name,'--label','cluvo.pwa.source-precision-test='+name,'--network=none','--restart=no','--log-driver=none','--no-healthcheck','--user=postgres','--cap-drop=ALL','--security-opt=no-new-privileges','--pids-limit=64','--memory=512m','--cpus=1','--tmpfs','/restore:rw,exec,size=512m,mode=1777','--entrypoint','/bin/sh',IMAGE,'-c',INITIAL_RESTORE_STARTUP,'cluvo-pwa-source-precision-test','supabase_admin']).toString().trim();assert.match(id,/^[0-9a-f]{64}$/);guard();checked(['start',id]);let ready=false;
  for(let n=0;n<50;n++){if(run(['exec',id,'pg_isready','-h','/restore','-U','supabase_admin','-d','postgres']).status===0){ready=true;break;}await new Promise(r=>setTimeout(r,100));}assert.equal(ready,true);guard();
  sql('postgres',ddl+'CREATE DATABASE precision_restored;');checked(['exec',id,'mkdir','-p','/restore/runtime','/restore/pwa-source-normalization']);checked(['exec',id,'touch','/restore/runtime/empty-passfile']);checked(['exec',id,'chmod','600','/restore/runtime/empty-passfile']);
  const sources={};for(const file of ['scripts/staging_backup_session.py','scripts/staging_pwa_upgrade_session.py','tests/helpers/staging-pwa-source-normalization-owned.py']){const bytes=await readFile(new URL('../'+file,import.meta.url));sources[file]=hash(bytes);const target='/restore/pwa-source-normalization/'+file.split('/').at(-1);checked(['exec','-i',id,'sh','-c','cat > "$1"','copy-public-source',target],bytes);}
  checked(['exec','-i',id,'sh','-c','cat > /restore/pwa-source-normalization/catalog.sql'],catalogSql);
  // The pinned Postgres image intentionally lacks Python. Copy only the public
  // system interpreter/stdlib into this owned tmpfs, never user packages/env.
  const runtimeProbe=spawnSync('/usr/bin/python3',['-S','-c',"import sys,sysconfig,os,json;print(json.dumps({'executable':os.path.realpath(sys.executable),'stdlib':sysconfig.get_path('stdlib'),'version':sys.version.split()[0]}))"],{env:{PATH:'/usr/bin:/bin'},timeout:5000,maxBuffer:10000});assert.equal(runtimeProbe.status,0);const py=JSON.parse(runtimeProbe.stdout);
  assert.match(py.executable,/^\/usr\/bin\/python3\.[0-9]+$/);assert.match(py.stdlib,/^\/usr\/lib\/python3\.[0-9]+$/);
  const interpreter=await readFile(py.executable),stdlibArchive=spawnSync('/usr/bin/tar',['-C','/usr/lib','--exclude=__pycache__','-czf','-',py.stdlib.split('/').at(-1)],{env:{PATH:'/usr/bin:/bin'},timeout:30000,maxBuffer:64_000_000});assert.equal(stdlibArchive.status,0);assert.equal(stdlibArchive.stderr.length,0);
  checked(['exec',id,'mkdir','-p','/restore/public-python/bin','/restore/public-python/lib']);checked(['exec','-i',id,'sh','-c','cat > /restore/public-python/bin/python3'],interpreter);checked(['exec',id,'chmod','700','/restore/public-python/bin/python3']);checked(['exec','-i',id,'tar','-xzf','-','-C','/restore/public-python/lib'],stdlibArchive.stdout);
  const testRuntime={python_version:py.version,interpreter_sha256:hash(interpreter),stdlib_archive_sha256:hash(stdlibArchive.stdout),public_system_runtime_only:true,temporary_owned_tmpfs_only:true,user_site_packages_disabled:true,packages_installed:false};
  // Host and image may have different glibc releases. These are public runtime
  // files inside the owned test only; pg_dump/archive subprocesses retain image
  // libraries and receive no LD_LIBRARY_PATH or formatter overrides.
  checked(['exec',id,'mkdir','-p','/restore/public-python/systemlib']);testRuntime.system_library_sha256={};
  const publicLibpq='/usr/lib/x86_64-linux-gnu/libpq.so.5';
  const dependencies=spawnSync('/usr/bin/ldd',[publicLibpq],{env:{PATH:'/usr/bin:/bin',LANG:'C'},timeout:5000,maxBuffer:20000});assert.equal(dependencies.status,0);assert.equal(dependencies.stderr.length,0);
  const libpqDependencies=[...dependencies.stdout.toString().matchAll(/=> (\/lib\/x86_64-linux-gnu\/lib[a-zA-Z0-9._+-]+\.so(?:\.[0-9]+)*) /g)].map(match=>match[1]);assert.ok(libpqDependencies.length>=5&&libpqDependencies.length<=30);assert.ok(!dependencies.stdout.toString().includes('not found'));
  for(const path of new Set(['/lib64/ld-linux-x86-64.so.2','/lib/x86_64-linux-gnu/libc.so.6','/lib/x86_64-linux-gnu/libm.so.6','/lib/x86_64-linux-gnu/libz.so.1','/lib/x86_64-linux-gnu/libexpat.so.1','/lib/x86_64-linux-gnu/libffi.so.8',publicLibpq,...libpqDependencies])){const bytes=await readFile(path),name=path.split('/').at(-1);testRuntime.system_library_sha256[name]=hash(bytes);checked(['exec','-i',id,'sh','-c','cat > "$1"','copy-public-runtime','/restore/public-python/systemlib/'+name],bytes);}
  checked(['exec',id,'chmod','700','/restore/public-python/systemlib/ld-linux-x86-64.so.2']);
  const observed=JSON.parse(checked(['exec','--env','PYTHONHOME=/restore/public-python',id,'/restore/public-python/systemlib/ld-linux-x86-64.so.2','--library-path','/restore/public-python/systemlib','/restore/public-python/bin/python3','-S','-B','/restore/pwa-source-normalization/staging-pwa-source-normalization-owned.py']).toString());
  const capture=publicSourceDeparseNormalization(observed.first_proof),fresh=publicSourceDeparseNormalization(observed.fresh_proof);assert.equal(capture.original_context.extra_float_digits,0);assert.equal(capture.effective_context.extra_float_digits,3);assert.equal(fresh.original_context.extra_float_digits,0);assert.equal(fresh.effective_context.extra_float_digits,3);assert.equal(fresh.phase,'fresh_read');
  assert.equal(observed.rollback_restored_original_zero_twice,true);assert.equal(observed.same_backend_exclusive_lock_preserved,true);assert.equal(observed.database_and_role_settings_unchanged,true);assert.equal(observed.actual_pg_dump_same_live_exported_snapshot,true);assert.equal(observed.archive_process_settings_changed,false);
  const sourceCatalog=observed.catalog,sourceData=observed.data;assert.equal(Object.keys(sourceCatalog).length,28);assert.equal(sourceData.rows,3);assert.equal(sourceData.float_bits.length,3);
  const sourceUnderZero=json('postgres','SET extra_float_digits TO 0;'+dataSql);assert.equal(isDeepStrictEqual(sourceUnderZero,sourceData),false,'LOSSY_ZERO_ROW_HASH_NOT_REPRODUCED');assert.deepEqual(sourceUnderZero.float_bits,sourceData.float_bits);
  const archive=checked(['exec',id,'cat','/restore/pwa-source-normalization/fixture.archive']);assert.equal(archive.subarray(0,5).toString(),'PGDMP');sql('precision_restored','DROP SCHEMA public;');checked(['exec','-i',id,'pg_restore','-h','/restore','-U','supabase_admin','-d','precision_restored','--single-transaction','--exit-on-error'],archive);
  const alignment=cloneDeparseSettingsSQL(capture.effective_context),readback=(extra='')=>json('precision_restored','BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY;'+alignment+extra+"SELECT jsonb_build_object('context',("+PWA_DEPARSE_CONTEXT_SQL.replace(/;$/,'')+"),'catalog',("+catalogSql.replace(/;$/,'')+"),'data',("+dataSql.replace(/;$/,'')+'));ROLLBACK;');
  const restored=readback();assert.deepEqual(publicDeparseContext(restored.context),capture.effective_context);assert.deepEqual(restored.catalog,sourceCatalog);assert.deepEqual(restored.data,sourceData);
  const lossy=json('precision_restored','SET extra_float_digits TO 0;'+dataSql);assert.equal(isDeepStrictEqual(lossy,sourceData),false);assert.deepEqual(lossy.float_bits,sourceData.float_bits);
  const writeReadback=body=>json('precision_restored','BEGIN;'+alignment+body+"SELECT jsonb_build_object('catalog',("+catalogSql.replace(/;$/,'')+"),'data',("+dataSql.replace(/;$/,'')+'));ROLLBACK;');
  const rowDrift=writeReadback('UPDATE public.pwa_lossless_fixture SET precise_double=0.2 WHERE id=1;');assert.equal(isDeepStrictEqual(rowDrift.data,sourceData),false);
  const extra=writeReadback('CREATE TABLE public.precision_extra(id integer);');assert.equal(isDeepStrictEqual(extra.catalog,sourceCatalog),false);
  const acl=writeReadback('GRANT SELECT ON public.pwa_lossless_fixture TO PUBLIC;');assert.equal(isDeepStrictEqual(acl.catalog,sourceCatalog),false);
  const floatThreshold=writeReadback("ALTER TABLE public.pwa_lossless_fixture DROP CONSTRAINT pwa_lossless_threshold;ALTER TABLE public.pwa_lossless_fixture ADD CONSTRAINT pwa_lossless_threshold CHECK(precise_double >= '0.12345678901234570'::double precision) NOT VALID;");assert.equal(isDeepStrictEqual(floatThreshold.catalog,sourceCatalog),false);
  sql('precision_restored',alignment+"BEGIN;ALTER TABLE public.pwa_lossless_fixture DROP CONSTRAINT pwa_lossless_threshold;ALTER TABLE public.pwa_lossless_fixture ADD CONSTRAINT pwa_lossless_threshold CHECK(precise_double >= '0.12345678901234570'::double precision) NOT VALID;INSERT INTO public.pwa_lossless_fixture VALUES(4,0.12345678901234568,1.2345679,'2026-10-09 12:34:56+00','2026-10-09','1 day 02:03:04');",{failure:true});
  assert.deepEqual(readback().catalog,sourceCatalog);assert.deepEqual(readback().data,sourceData);
  proof={scope:'LOCAL_OWNED_PG17_PWA_SOURCE_READONLY_LOSSLESS_PRECISION',testRuntime,sourcePrecision:{capture,fresh},pinned_image:IMAGE,network:'none',owned_databases:2,hosted_or_shared_connections:0,credentials_or_private_archives_received:false,synthetic_fixture_rows:3,actual_pg_dump_bound_to_live_exported_snapshot:true,archive_process_settings_changed:false,
   all28_catalogs_exact_after_archive_restore:true,actual_rows_and_float4_float8_bits_exact:true,lossy_zero_row_checksum_actual_mismatch:true,original_zero_restored_after_both_rollbacks:true,backend_exclusive_lock_preserved:true,database_role_defaults_unchanged:true,
   actual_float_row_drift_rejected:true,actual_extra_table_rejected:true,actual_acl_drift_rejected:true,actual_float_threshold_drift_rejected:true,actual_boundary_insert_refused_after_threshold_drift:true,all_negative_changes_rolled_back:true,
   source_catalog_sha256:hash(JSON.stringify(sourceCatalog)),source_data_sha256:sourceData.sha256,restored_data_sha256:restored.data.sha256,archive_sha256:hash(archive),sourceFilesSha256:sources,
   frozen_backup_transport_sha256:sources['scripts/staging_backup_session.py'],catalog_query_definitions_changed:false,comparison_normalized:false,staging_verified:false,production_enabled:false};
 }finally{if(created&&id){guard();checked(['rm','--force','--volumes',id]);assert.equal(run(['inspect',id]).status,1);removed=true;}}
 assert.equal(removed,true);proof.owned_container_removed=true;proof.test_source_sha256=hash(await readFile(new URL(import.meta.url)));proof.diagnostic_source_sha256=hash(await readFile(new URL('../scripts/staging-pwa-restore-diagnostic.mjs',import.meta.url)));
 if(process.env.CLUVO_PWA_SOURCE_PRECISION_EVIDENCE==='owned-pg17'){const path=new URL('../docs/release/evidence/local/20261009-pwa35-source-precision-owned-proof.json',import.meta.url);await mkdir(new URL('.',path),{recursive:true});await writeFile(path,JSON.stringify(proof,null,2)+'\n');}
 t.diagnostic(JSON.stringify(proof));
});
