export type Role='bestuur'|'vrijwilligerscommissie'|'coordinator'|'teamouder'|'lid'|'vrijwilliger'|'financien';
export const roles:Record<Role,string>={bestuur:'Bestuur',vrijwilligerscommissie:'Vrijwilligerscommissie',coordinator:'Commissiecoördinator',teamouder:'Teamouder',lid:'Lid / ouder',vrijwilliger:'Vaste vrijwilliger',financien:'Financieel beheer'};
export type Person={id:string;name:string;email:string;age:number;hh:string;team:string;skills:string[];prefs:string[];availability:string[];limitations:string;interests:string[];intake:boolean;certs:string[];verified:boolean;maxHours:number;reserve:boolean;buddy:boolean;unavailable?:string[];experience?:string;training?:string[];represents?:string[]};
export type Household={id:string;name:string;code:string;target:number;winter:number;base:number;baseBefore:number;separated:boolean;status:string;role?:string;exempt:boolean;buyout:boolean;blocked:boolean;team:string;note:string};
export type Shift={id:string;title:string;committee:string;category:string;date:string;start:string;end:string;minutes:number;capacity:number;status:string;location:string;minAge:number;qualification:string;buddy:boolean;cancelDays:number;instructions:string;match?:string;slot:number;teamTask?:string;experienced:number};
export type Booking={id:string;shiftId:string;personId:string;hh:string;status:string;minutes:number;cancelDays:number;reason?:string;swap?:boolean;buddyId?:string};
export type Card={id:string;title:string;committee:string;column:string;priority:string;assignees:string[];owner:string;deadline:string;description:string;labels:string[];checks:{text:string;done:boolean;owner?:string}[];comments:{name:string;text:string;at:string}[];event?:string;shift?:string};
export type Match={id:string;team:string;opponent:string;date:string;time:string;home:boolean;location:string;field:string;status:string;change?:string};
export type Event={id:string;title:string;date:string;time:string;end:string;kind:string;scope:string;location:string;owner:string;attendees:string[];repeat:string;description:string};
export type State={version:number;role:Role;currentPerson:string;households:Household[];people:Person[];shifts:Shift[];bookings:Booking[];waitlist:{shiftId:string;personId:string}[];cards:Card[];matches:Match[];events:Event[];documents:any[];teamTasks:any[];requests:any[];templates:any[];messages:any[];notifications:any[];acceptances:any[];policies:any[];appreciations:any[];courses:any[];vacancies:any[];applications:any[];roleCatalog:any[];assignments:any[];transactions:any[];invoices:any[];segments:any[];log:any[];sync:any;settings:any;archives:any[];columns:string[];committees:any[]};
export const uid=(prefix='id')=>prefix+'-'+Math.random().toString(36).slice(2,9);
export const TODAY='2026-10-02';
export const committees=['Kantine','Activiteiten','Vrijwilligers','Accommodatie','Wedstrijdzaken'];
export const categories=['Bar','Keuken','Onderhoud','Ontvangst','Scheidsrechter','Activiteiten'];
export const timeHours=(s:string)=>Number(s.split(':')[0])+Number(s.split(':')[1])/60;
export const hours=(minutes:number)=>new Intl.NumberFormat('nl-NL',{maximumFractionDigits:2}).format(minutes/60);
export const euro=(v:number)=>new Intl.NumberFormat('nl-NL',{style:'currency',currency:'EUR'}).format(v);
export const dateLabel=(date:string,short=false)=>new Date(date+'T12:00:00').toLocaleDateString('nl-NL',{weekday:short?undefined:'short',day:'numeric',month:'short'});
export const fullDate=(date:string)=>new Date(date+'T12:00:00').toLocaleDateString('nl-NL',{day:'numeric',month:'long',year:'numeric'});
export const money=(minutes:number,rate=12.5)=>Math.round(Math.max(0,minutes)/60*rate*100)/100;
const hhNames=['Vermeer','De Groot','Bakker','Van Dalen','Jansen','Visser','De Wit','Smit','Peters','Van Leeuwen','Mulder','Bos'];
const personNames=['Sanne Vermeer','Jens Vermeer','Sem Vermeer','Noor Vermeer','Eva de Groot','Mark Bakker','Lotte van Dalen','Daan Jansen','Mila Visser','Tom de Wit','Nora Smit','Bram Peters','Sophie van Leeuwen','Lars Mulder','Tess Bos','Robin Vos'];
export const seed=():State=>{
 const households:Household[]=hhNames.map((n,i)=>({id:'h'+(i+1),name:'Huishouden '+n,code:'CLV-'+['V8K2','Q3R6','A7P9','F2J5','D9L3','B5X8','N2M4','C8T6','Y5U9','R4S2','G7H3','K6W8'][i],target:720,winter:360,base:[240,360,480,0,180,720,300,420,120,600,60,480][i],baseBefore:[240,360,480,0,180,720,300,420,120,600,60,480][i],separated:i===3,status:i===3?'Intake onvolledig':'Actief',exempt:false,buyout:false,blocked:i===4,team:i%2===0?'JO13-1':'JO17-1',note:i===3?'Onafhankelijke ouderintakes. Elke ouder ziet alleen het eigen profiel.':''}));
 const people:Person[]=personNames.map((name,i)=>({id:'p'+(i+1),name,email:name.toLowerCase().replaceAll(' ','')+'@example.test',age:i===2?16:i===3?13:30+i,hh:i<4?'h1':'h'+Math.min(i-2,12),team:i===2?'JO17-1':i===3?'JO13-1':i%2?'JO17-1':'JO13-1',skills:i%3===0?['Organiseren','Gastvrijheid']:i%3===1?['Techniek','Klussen']:['Koken','Begeleiden'],prefs:i===0?['Bar','Activiteiten']:i%2?['Onderhoud','Ontvangst']:['Keuken','Bar'],availability:['Zaterdag ochtend','Zondag ochtend'],limitations:'',interests:[],intake:i!==6,certs:i%3===0?['IVA']:[],verified:true,maxHours:6,reserve:i%4===0,buddy:i===0}));
 const mk=(id:string,title:string,category:string,date:string,start:string,end:string,capacity:number,status='Gepubliceerd',slot=0):Shift=>({id,title,committee:['Bar','Keuken'].includes(category)?'Kantine':category==='Onderhoud'?'Accommodatie':category==='Ontvangst'?'Wedstrijdzaken':'Activiteiten',category,date,start,end,minutes:Math.round((timeHours(end)-timeHours(start))*60),capacity,status,location:'Clubhuis · Sportpark Duindorp',minAge:category==='Bar'?18:16,qualification:category==='Bar'?'IVA':'',buddy:category==='Bar',cancelDays:3,instructions:category==='Bar'?'Meld je 10 minuten vooraf bij de coördinator. Controleer de kassa, vul koelingen aan en draag de werkplek schoon over. Een IVA-begeleider is aanwezig.':'Meld je bij de coördinator. Lees de checklist, werk veilig en draag de werkplek netjes over.',slot,experienced:category==='Bar'?1:0});
 const shifts:Shift[]=[mk('s1','Een goede start achter de bar','Bar','2026-10-03','08:00','11:00',3),mk('s2','Lunch voor onze jeugd','Keuken','2026-10-03','10:00','12:00',2),mk('s3','Welkom op ons sportpark','Ontvangst','2026-10-03','09:00','12:00',2),mk('s4','Samen het park winterklaar','Onderhoud','2026-10-04','09:00','12:00',4),mk('s5','De derde helft','Bar','2026-10-03','13:00','16:00',3,'Gepubliceerd',1),mk('s6','Help mee met de familiedag','Activiteiten','2026-10-10','10:00','13:00',5),mk('s7','Zondagochtend in de keuken','Keuken','2026-10-04','10:00','12:00',2),mk('s8','Koffie & clubgevoel','Bar','2026-10-10','08:00','10:00',2),mk('s9','Klusploeg accommodatie','Onderhoud','2026-10-11','09:00','11:00',3),mk('s10','Bar na de thuiswedstrijd','Bar','2026-10-17','13:00','16:00',3,'Concept'),mk('s11','Keuken thuisdag','Keuken','2026-10-17','11:00','14:00',2,'Concept'),mk('s12','Ontvangst januari','Ontvangst','2027-01-09','09:00','11:00',4),mk('s13','Barploeg januari','Bar','2027-01-09','10:00','12:00',3),mk('s14','Zaterdag bardienst','Bar','2026-09-26','10:00','12:00',3),mk('s15','Keuken zaterdag','Keuken','2026-09-26','11:00','13:00',2)];shifts[0].match='m1';shifts[4].match='m3';shifts[9].match='m6';
 people[0].represents=['p3','p4'];people[1].represents=['p3','p4'];
 people.find(p=>p.id==='p6')!.certs=['IVA'];people.find(p=>p.id==='p9')!.certs=['IVA'];
 const bookings:Booking[]=[{id:'b1',shiftId:'s2',personId:'p1',hh:'h1',status:'Ingepland',minutes:120,cancelDays:3},{id:'b2',shiftId:'s14',personId:'p1',hh:'h1',status:'Te bevestigen',minutes:120,cancelDays:3},{id:'b3',shiftId:'s1',personId:'p6',hh:'h4',status:'Ingepland',minutes:180,cancelDays:3},{id:'b4',shiftId:'s1',personId:'p9',hh:'h7',status:'Ingepland',minutes:180,cancelDays:3},{id:'b5',shiftId:'s5',personId:'p5',hh:'h3',status:'Ingepland',minutes:180,cancelDays:3,swap:true},{id:'b6',shiftId:'s7',personId:'p8',hh:'h6',status:'Ingepland',minutes:120,cancelDays:3},{id:'b7',shiftId:'s7',personId:'p10',hh:'h8',status:'Ingepland',minutes:120,cancelDays:3},{id:'b8',shiftId:'s15',personId:'p8',hh:'h5',status:'Te bevestigen',minutes:120,cancelDays:3},{id:'b9',shiftId:'s3',personId:'p11',hh:'h9',status:'Ingepland',minutes:180,cancelDays:3}];
 bookings.forEach(b=>b.hh=people.find(p=>p.id===b.personId)!.hh);
 return {version:1,role:'bestuur',currentPerson:'p1',households,people,shifts,bookings,waitlist:[],
 cards:[{id:'k1',title:'Rooster herfstvakantie rondmaken',committee:'Kantine',column:'Bezig',priority:'Hoog',assignees:['p1','p6'],owner:'p1',deadline:'2026-10-07',description:'Stem de bezetting af op de thuiswedstrijden. Neem nieuwe vrijwilligers mee met een ervaren maatje.',labels:['Planning'],checks:[{text:'Wedstrijden controleren',done:true},{text:'Open plekken inventariseren',done:true},{text:'Rooster publiceren',done:false}],comments:[{name:'Jens Vermeer',text:'@Sanne Vermeer ik kan zaterdag de opening doen.',at:'09:12'}],shift:'s10'},
 {id:'k2',title:'Nieuwe koffie-instructie',committee:'Kantine',column:'Te doen',priority:'Normaal',assignees:['p6'],owner:'p6',deadline:'2026-10-12',description:'Een korte checklist bij de koffiemachine.',labels:['Instructie'],checks:[{text:'Foto maken',done:false}],comments:[]},
 {id:'k3',title:'Vrijwilligersavond voorbereiden',committee:'Activiteiten',column:'Ideeën',priority:'Normaal',assignees:['p1','p5'],owner:'p5',deadline:'2026-11-06',description:'Een avond om iedereen die bijdraagt te bedanken.',labels:['Waardering'],checks:[],comments:[],event:'e3'},
 {id:'k4',title:'Voorraad voor zaterdag bestellen',committee:'Kantine',column:'Wacht op',priority:'Hoog',assignees:['p6','p9'],owner:'p6',deadline:'2026-10-02',description:'Wacht op bevestiging leverancier.',labels:['Inkoop'],checks:[{text:'Bestellijst',done:true},{text:'Levering bevestigd',done:false}],comments:[]},
 {id:'k5',title:'Introductie nieuwe barvrijwilligers',committee:'Kantine',column:'Afgerond',priority:'Normaal',assignees:['p1'],owner:'p1',deadline:'2026-09-28',description:'Inwerkavond afgerond.',labels:['Opleiding'],checks:[{text:'Uitleg kassa',done:true}],comments:[]}],
 columns:['Ideeën','Te doen','Bezig','Wacht op','Afgerond'],
 matches:[{id:'m1',team:'JO13-1',opponent:'SV Noordzee JO13-1',date:'2026-10-03',time:'09:30',home:true,location:'Sportpark Duindorp',field:'Veld 2',status:'Gepland'},{id:'m2',team:'JO17-1',opponent:'FC Parkzicht JO17-1',date:'2026-10-03',time:'11:00',home:false,location:'Sportpark Parkzicht',field:'Veld 1',status:'Gepland'},{id:'m3',team:'Duindorp 1',opponent:'SV Westduin 1',date:'2026-10-03',time:'14:30',home:true,location:'Sportpark Duindorp',field:'Hoofdveld',status:'Gewijzigd',change:'Aanvang van 14:00 naar 14:30. 1 gekoppelde dienst vraagt controle.'},{id:'m4',team:'JO13-1',opponent:'FC Duinrand JO13-2',date:'2026-10-10',time:'10:00',home:false,location:'Sportpark Duinrand',field:'',status:'Gepland'},{id:'m5',team:'JO17-1',opponent:'SV Strandvogels JO17-1',date:'2026-10-10',time:'11:30',home:true,location:'Sportpark Duindorp',field:'Veld 2',status:'Gepland'},{id:'m6',team:'Duindorp 1',opponent:'FC Parkzicht 1',date:'2026-10-17',time:'14:00',home:true,location:'Sportpark Duindorp',field:'Hoofdveld',status:'Gepland'}],
 events:[{id:'e1',title:'Commissieoverleg kantine',date:'2026-10-06',time:'19:30',end:'20:30',kind:'Vergadering',scope:'Kantine',location:'Bestuurskamer',owner:'p6',attendees:['p1','p6'],repeat:'Maandelijks',description:'Rooster, voorraad en inwerken.'},{id:'e2',title:'Familiedag',date:'2026-10-10',time:'10:00',end:'17:00',kind:'Activiteit',scope:'Vereniging',location:'Sportpark',owner:'p5',attendees:[],repeat:'Geen',description:'Samen spelen, ontmoeten en genieten.'},{id:'e3',title:'Vrijwilligersavond',date:'2026-11-06',time:'19:00',end:'23:00',kind:'Waardering',scope:'Vereniging',location:'Clubhuis',owner:'p1',attendees:['p1'],repeat:'Jaarlijks',description:'Bedankt voor alles wat je doet.'},{id:'e4',title:'IVA-inwerkavond',date:'2026-10-08',time:'19:00',end:'21:00',kind:'Opleiding',scope:'Kantine',location:'Clubhuis',owner:'p6',attendees:[],repeat:'Geen',description:'Een goede start achter de bar.'}],
 documents:[{id:'d1',title:'Opening en afsluiting bar',committee:'Kantine',version:3,owner:'p6',scope:'Commissie',type:'Instructie',text:'1. Open met de coördinator.\n2. Controleer kassa en koeling.\n3. Werk schoon en veilig.\n4. Tel de kas samen.\n5. Sluit alle deuren en draag over.',checklist:['Koeling controleren','Kassa openen','Overdracht afronden']},{id:'d2',title:'Veilig werken in de keuken',committee:'Kantine',version:1,owner:'p6',scope:'Vereniging',type:'Document',text:'Was je handen, gebruik de juiste materialen en bespreek allergenen met de coördinator.'}],
 teamTasks:[{id:'tt1',title:'Fruit voor de rust',team:'JO13-1',date:'2026-10-03',person:'p1',status:'Teamtaak',minutes:0},{id:'tt2',title:'Bidons vullen',team:'JO13-1',date:'2026-10-03',person:'',status:'Teamtaak',minutes:0},{id:'tt3',title:'Scheidsrechter JO13-1 gezocht',team:'JO13-1',date:'2026-10-10',person:'',status:'Wacht op wedstrijdzaken',minutes:0}],
 requests:[{id:'r1',hh:'h5',person:'p8',type:'Urencontrole',reason:'Dienst op 26 september is nog niet bevestigd.',status:'In behandeling',reviews:[],target:720},{id:'r2',hh:'h4',person:'p6',type:'Afkoop',reason:'Beschikbare taken zijn samen besproken; op dit moment geen passend aanbod.',status:'In behandeling',reviews:['Coördinator A'],target:0}],
 templates:[{id:'t1',name:'Nieuwe passende taken',subject:'{{voornaam}}, er staat iets voor je klaar',preheader:'Bekijk de taken die passen bij jouw voorkeuren',body:'Hoi {{voornaam}},\nEr zijn nieuwe taken bij {{vereniging}} die passen bij jouw voorkeuren. Je huishouden heeft nog {{resterend}} uur te gaan.\nSamen maken we de club!',version:2,status:'Gepubliceerd',channel:'E-mail',category:'Aanbod',sender:'Cluvo · Duindorp SV',reply:'vrijwilligers@example.test',button:'Bekijk taken'},{id:'t2',name:'Herinnering aan je dienst',subject:'Morgen help je bij {{dienst}}',preheader:'Alles voor een fijne dienst',body:'Hoi {{voornaam}},\nMorgen zien we je bij {{dienst}}. Je vindt de instructies in Cluvo.\nBedankt voor je inzet!',version:1,status:'Gepubliceerd',channel:'E-mail',category:'Dienst',sender:'Cluvo · Duindorp SV',reply:'kantine@example.test',button:'Mijn dienst'},{id:'t3',name:'Fijne verjaardag',subject:'Gefeliciteerd, {{voornaam}}!',preheader:'Een mooie dag gewenst',body:'Van harte gefeliciteerd {{voornaam}}!\nWe wensen je een fijne dag namens iedereen bij {{vereniging}}.',version:1,status:'Concept',channel:'E-mail',category:'Waardering',sender:'Cluvo · Duindorp SV',reply:'bestuur@example.test',button:''}],
 messages:[{id:'msg1',channel:'Kantine',name:'Mark Bakker',text:'Het nieuwe rooster staat klaar. @Sanne Vermeer wil jij de opening even bekijken?',at:'09:12'},{id:'msg2',channel:'Kantine',name:'Sanne Vermeer',text:'Komt goed! Ik neem onze nieuwe vrijwilliger ook even mee.',at:'09:18'}],
 notifications:[{id:'n1',title:'3 passende taken voor jou',text:'Er zijn nieuwe diensten in Bar en Activiteiten.',route:'taken',read:false,kind:'Aanbod'},{id:'n2',title:'Je dienst begint morgen',text:'Keuken · 3 oktober · 10:00–12:00',route:'diensten',read:false,kind:'Dienst'},{id:'n3',title:'Een vermelding op het kanbanbord',text:'Mark noemde je in Rooster herfstvakantie.',route:'kanban',read:false,kind:'Mention'}],
 policies:[{id:'pol1',title:'Verenigingstakenbeleid',version:'1.0',date:'2026-09-01',status:'Gepubliceerd',text:'Samen maken we de club.\n\nIeder huishouden draagt twaalf uur per seizoen bij. Minimaal zes uur zijn vóór de winterstop uitgevoerd. Extra uren voor de winterstop tellen mee voor het hele seizoen. De vrijwilligerscommissie helpt bij het vinden en plannen van passende taken.\n\nErkende vaste vrijwilligersrollen geven vrijstelling voor het gehele gekoppelde huishouden. Bij bijzondere omstandigheden bespreken we samen een passende oplossing. Teamtaken leveren alleen uren op na voorafgaande goedkeuring voor de takenmarkt.\n\nAfmelden kan binnen de bij inschrijving genoemde termijn. Ziekte en nood kun je altijd melden.\n\nNa controle kan bij een tekort een vervangende bijdrage van €12,50 per uur ontstaan, tot €150 bij de standaardverplichting. Afkoop is alleen na overleg en goedkeuring mogelijk.\n\nDit is de voorbeeldtekst in het Cluvo-prototype.'}],acceptances:[{member:'p3',policy:'pol1',version:'1.0',actor:'p1',at:'2026-09-10 19:42',capacity:'Ouder/verzorger'}],
 appreciations:[{id:'a1',title:'10 jaar vrijwilliger · Mark',person:'p6',kind:'Jubileum',date:'2026-10-09',owner:'p1',budget:40,status:'Te doen',private:false},{id:'a2',title:'Verjaardag Sanne',person:'p1',kind:'Verjaardag',date:'2026-10-14',owner:'p5',budget:0,status:'Conceptbericht',private:false},{id:'a3',title:'Vrijwilligersavond',person:'',kind:'Waardering',date:'2026-11-06',owner:'p5',budget:650,status:'In voorbereiding',private:false},{id:'a4',title:'Een kaartje sturen',person:'p7',kind:'Lief & leed',date:'2026-10-05',owner:'p1',budget:10,status:'Te doen',private:true}],
 courses:[{id:'c1',title:'IVA · verantwoord schenken',date:'2026-10-08',places:10,enrolled:['p1'],cert:'IVA'},{id:'c2',title:'Eerste hulp op het sportpark',date:'2026-10-20',places:8,enrolled:['p6'],cert:'EHBO'}],
 vacancies:[{id:'v1',title:'Coördinator activiteiten',committee:'Activiteiten',hours:'4–6 uur per maand',exempt:true,description:'Breng ideeën tot leven en maak ontmoetingen mogelijk. Je werkt samen met een fijne commissie.'},{id:'v2',title:'Gastheer / gastvrouw op zondag',committee:'Kantine',hours:'2 zondagen per maand',exempt:true,description:'Een warm welkom voor spelers, ouders en bezoekers.'},{id:'v3',title:'Handige handen voor de klusploeg',committee:'Accommodatie',hours:'In overleg',exempt:false,description:'Van een los scharnier tot het opknappen van onze kleedkamers.'}],applications:[],
 roleCatalog:[{id:'role1',name:'Trainer',exempt:true},{id:'role2',name:'Bestuurslid',exempt:true},{id:'role3',name:'Commissielid',exempt:true},{id:'role4',name:'Vaste kantinevrijwilliger',exempt:true},{id:'role5',name:'Teamouder',exempt:false}],assignments:[{id:'as1',person:'p6',hh:'h3',role:'role1',exemptAtGrant:true,start:'2026-07-01',end:'2027-06-30',active:true},{id:'as2',person:'p9',hh:'h6',role:'role4',exemptAtGrant:true,start:'2026-07-01',end:'2027-06-30',active:true}],
 transactions:[{id:'tr1',title:'Ontvangen bijdragen',amount:1200,type:'Inkomst',status:'Ontvangen'},{id:'tr2',title:'IVA-opleiding',amount:180,type:'Uitgave',status:'Betaald'},{id:'tr3',title:'Vrijwilligersavond',amount:650,type:'Reservering',status:'Goedgekeurd'}],invoices:[],segments:[],
 log:[{id:'l1',at:'Vandaag, 09:42',actor:'Sanne Vermeer',action:'Aanmelding keuken bevestigd'},{id:'l2',at:'Vandaag, 08:30',actor:'Mark Bakker',action:'Conceptrooster 17 oktober aangemaakt'}],
 sync:{last:'2 oktober 2026, 06:00',status:'Demo · bron niet verbonden',changes:1,count:6},
 settings:{club:'Duindorp SV',season:'2026 / 2027',start:'2026-07-01',end:'2027-06-30',winter:'2026-12-20',target:12,winterPercent:50,cancelDays:3,confirmDays:7,disputeDays:14,contribution:150,sync1:'06:00',sync2:'18:00',timezone:'Europe/Amsterdam',reminder1:7,reminder2:24,digest:true,push:false,email:true,privacy:true},archives:[],
 committees:committees.map((name,i)=>({id:'com'+i,name,coordinator:i===0?'p6':'p'+(i+5),members:i===0?['p1','p6','p9']:['p'+(i+5),'p'+(i+8)],color:['coral','violet','blue','green','amber'][i]}))};
};
export const activeBookings=(s:State,shiftId:string)=>s.bookings.filter(b=>b.shiftId===shiftId&&['Ingepland','Te bevestigen','Aanwezig','In beoordeling'].includes(b.status));
export function progress(s:State,id:string){const h=s.households.find(h=>h.id===id)!;const bs=s.bookings.filter(b=>b.hh===id);const confirmed=h.base+bs.filter(b=>b.status==='Aanwezig').reduce((a,b)=>a+b.minutes,0);const before=h.baseBefore+bs.filter(b=>b.status==='Aanwezig'&&(s.shifts.find(x=>x.id===b.shiftId)?.date||'')<s.settings.winter).reduce((a,b)=>a+b.minutes,0);const planned=bs.filter(b=>b.status==='Ingepland').reduce((a,b)=>a+b.minutes,0);const pending=bs.filter(b=>['Te bevestigen','In beoordeling'].includes(b.status)).reduce((a,b)=>a+b.minutes,0);const role=s.assignments.find(a=>a.hh===id&&a.active&&a.start<=TODAY&&a.end>=TODAY&&(a.exemptAtGrant??s.roleCatalog.find(r=>r.id===a.role)?.exempt));const exempt=h.exempt||!!role;return {confirmed,before,planned,pending,exempt,role,remaining:exempt||h.buyout?0:Math.max(0,h.target-confirmed),winterRemaining:exempt||h.buyout?0:Math.max(0,h.winter-before),percent:exempt||h.buyout?100:Math.min(100,confirmed/h.target*100)};}
export const nameOf=(s:State,id:string)=>s.people.find(p=>p.id===id)?.name||'Nog niet toegewezen';
export function bookingError(s:State,t:Shift,p:Person,exclude?:string,hasBuddy=false){if(t.status!=='Gepubliceerd')return'Deze dienst is nog niet gepubliceerd.';if(p.age<t.minAge)return`Voor deze dienst geldt een minimumleeftijd van ${t.minAge} jaar.`;if(!p.verified)return'Verifieer eerst het e-mailadres van de uitvoerder.';if(p.unavailable?.includes(t.date))return'De uitvoerder heeft deze datum als verhinderd opgegeven.';if(t.qualification&&(p as any).certExpiry?.[t.qualification]&&((p as any).certExpiry[t.qualification]<t.date))return'De vereiste kwalificatie is verlopen op de dienstdatum.';if(t.qualification&&!p.certs.includes(t.qualification)&&!hasBuddy)return`Een geldig ${t.qualification}-certificaat is vereist.`;const overlap=s.bookings.some(b=>b.id!==exclude&&b.personId===p.id&&['Ingepland','Te bevestigen'].includes(b.status)&&s.shifts.some(x=>x.id===b.shiftId&&x.date===t.date&&timeHours(x.start)<timeHours(t.end)&&timeHours(x.end)>timeHours(t.start)));if(overlap)return'De uitvoerder heeft op dit tijdstip al een dienst.';return'';}
