'use client';
import React,{createContext,useContext,useEffect,useState} from 'react';
import {toast} from 'sonner';
import {State,seed,uid,Person,Shift,Booking,activeBookings,bookingError,nameOf} from './data';
type AppContext={s:State;change:(action:string,fn:(draft:State)=>void,silent?:boolean)=>void;route:string;go:(r:string)=>void;person:Person;isAdmin:boolean;canPlan:boolean;notify:(title:string,text:string,route:string)=>void;book:(t:Shift,p:Person,buddyId?:string)=>boolean;reset:()=>void};
const C=createContext<AppContext>(null!);
export const useApp=()=>useContext(C);
export function AppProvider({children}:{children:React.ReactNode}){const [s,setS]=useState<State>(seed);const [loaded,setLoaded]=useState(false);const [route,setRoute]=useState('overzicht');
useEffect(()=>{if('serviceWorker' in navigator&&location.hostname.endsWith('.chatgpt.site'))navigator.serviceWorker.register('/sw.js').catch(()=>{});try{const saved=localStorage.getItem('cluvo-demo-v1');if(saved){const j=JSON.parse(saved);if(j.version===1)setS(j)}}catch{toast.error('Opgeslagen demo kon niet worden gelezen. Een nieuwe demo is geopend.')}setLoaded(true);const read=()=>setRoute(window.location.hash.slice(1)||'overzicht');read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read)},[]);
useEffect(()=>{if(loaded)try{localStorage.setItem('cluvo-demo-v1',JSON.stringify(s))}catch{toast.error('Opslaan op dit apparaat is niet gelukt. Je wijzigingen blijven alleen in deze sessie.')}},[s,loaded]);
const go=(r:string)=>{setRoute(r);window.location.hash=r;window.scrollTo({top:0,behavior:'smooth'})};
const change=(action:string,fn:(draft:State)=>void,silent=false)=>{setS(prev=>{const d=structuredClone(prev);fn(d);d.log.unshift({id:uid('log'),at:new Date().toLocaleString('nl-NL'),actor:nameOf(prev,prev.currentPerson)+' · '+prev.role,action});return d});if(!silent)toast.success(action)};
const person=s.people.find(p=>p.id===s.currentPerson)||s.people[0];
const notify=(title:string,text:string,route:string)=>change('Melding toegevoegd',d=>{d.notifications.unshift({id:uid('n'),title,text,route,read:false,kind:'Actie'})},true);
const book=(t:Shift,p:Person,buddyId?:string)=>{const error=bookingError(s,t,p,undefined,!!buddyId);if(error){toast.error(error);return false}if(activeBookings(s,t.id).length>=t.capacity){toast.error('Deze dienst is vol. Je kunt op de wachtlijst.');return false}if(buddyId){const guide=s.people.find(x=>x.id===buddyId),guideBooking=activeBookings(s,t.id).find(b=>b.personId===buddyId);if(!guide||!guideBooking||bookingError(s,t,guide,guideBooking.id)){toast.error('Het maatje moet geschikt, beschikbaar en voor deze dienst ingepland zijn.');return false}}if(buddyId&&!s.people.some(x=>x.id===buddyId&&x.id!==p.id&&x.age>=18&&x.certs.includes(t.qualification))){toast.error('Dit maatje voldoet niet aan de kwalificatie.');return false}if(t.qualification&&!p.certs.includes(t.qualification)&&!buddyId){toast.error('Kies eerst een bevoegd maatje.');return false}change('Je inschrijving is bevestigd',d=>{d.bookings.push({id:uid('b'),shiftId:t.id,personId:p.id,hh:p.hh,status:'Ingepland',minutes:t.minutes,cancelDays:t.cancelDays,buddyId});d.waitlist=d.waitlist.filter(w=>!(w.shiftId===t.id&&w.personId===p.id));d.notifications.unshift({id:uid('n'),title:'Inschrijving bevestigd',text:`${p.name} · ${t.title}`,route:'diensten',read:false,kind:'Dienst'})});return true};
useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const abort=new AbortController();for(const tool of [{name:'cluvo_read_overview',title:'Cluvo-overzicht lezen',description:'Lees de lokale demo, rol en aantallen. Geen echte persoonsgegevens.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({role:s.role,route,shifts:s.shifts.length,households:s.households.length,bookings:s.bookings.length})},{name:'cluvo_navigate',title:'Open een Cluvo-werkruimte',description:'Open een bestaande pagina in het prototype.',inputSchema:{type:'object',properties:{page:{type:'string'}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false},execute:({page}:any)=>{const allowed=['overzicht','taken','diensten','ruilmarkt','planbord','huishoudens','commissies','kanban','teams','wedstrijden','agenda','berichten','acties','beleid','waardering','opleidingen','vacatures','rapportages','financien','templates','instellingen','intake'];if(!allowed.includes(page))throw new Error('Onbekende pagina');go(page);return{page}}}])Promise.resolve(mc.registerTool(tool,{signal:abort.signal})).catch(()=>{});return()=>abort.abort()},[s,route]);
return <C.Provider value={{s,change,route,go,person,isAdmin:['bestuur','vrijwilligerscommissie'].includes(s.role),canPlan:['bestuur','vrijwilligerscommissie','coordinator'].includes(s.role),notify,book,reset:()=>{setS(seed());go('overzicht');toast.success('De voorbeeldgegevens zijn hersteld')}}}>{children}</C.Provider>}
