'use client';
import React,{useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Search,Plus,Check,Download,Inbox,Clock,CalendarDays,Users,MapPin} from 'lucide-react';
export {Button,Input,Textarea,Checkbox,Progress,Table,TableHeader,TableHead,TableBody,TableRow,TableCell};
export const initials=(s:string)=>s.split(' ').filter(Boolean).map(x=>x[0]).slice(0,2).join('');
export function Avatar({name,size='normal',color='coral'}:{name:string;size?:string;color?:string}){return <span className={`avatar ${size} ${color}`} title={name}>{initials(name)}</span>}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Btn({children,onClick,variant='primary',className='',...rest}:any){return <Button type="button" className={'btn '+variant+' '+className} onClick={onClick} {...rest}>{children}</Button>}
export function SelectBox({value,onChange,options,label,className=''}:{value:string;onChange:(s:string)=>void;options:(string|{value:string;label:string})[];label?:string;className?:string}){return <Select value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)}><SelectTrigger aria-label={label||'Selecteer'} className={'select '+className}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>{const v=typeof o==='string'?o:o.value;return <SelectItem key={v||'none'} value={v||'__none'}>{typeof o==='string'?o:o.label}</SelectItem>})}</SelectContent></Select>}
export function Segments({value,onChange,options}:{value:string;onChange:(s:string)=>void;options:string[]}){return <Tabs value={value} onValueChange={onChange}><TabsList className="segments">{options.map(o=><TabsTrigger key={o} value={o}>{o}</TabsTrigger>)}</TabsList></Tabs>}
export function SearchBox({value,onChange,placeholder='Zoeken…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="searchbox"><Search size={17}/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
export function Empty({title='Geen resultaten',text='Pas je filters aan of voeg iets toe.',action}:{title?:string;text?:string;action?:React.ReactNode}){return <div className="empty"><Inbox size={32}/><h3>{title}</h3><p>{text}</p>{action}</div>}
export function PageTitle({eyebrow,title,description,actions}:{eyebrow?:string;title:string;description?:string;actions?:React.ReactNode}){return <div className="page-title"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="page-actions">{actions}</div></div>}
export function Panel({title,subtitle,actions,children,className=''}:{title?:string;subtitle?:string;actions?:React.ReactNode;children:React.ReactNode;className?:string}){return <section className={'panel '+className}>{title&&<div className="panel-head"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div>{actions}</div>}{children}</section>}
export function Stat({label,value,detail,icon:Icon,tone='coral'}:any){return <div className="stat"><div className="stat-top"><span>{label}</span>{Icon&&<span className={'icon-tile '+tone}><Icon size={18}/></span>}</div><strong>{value}</strong><p>{detail}</p></div>}
export function Hint({children,tone='blue'}:{children:React.ReactNode;tone?:string}){return <div className={'hint '+tone}>{children}</div>}
export function Field({label,children,hint}:{label:string;children:React.ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}
export function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="checkline"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/><span>{label}</span></label>}
export function CheckList({values,selected,onChange}:{values:string[];selected:string[];onChange:(s:string[])=>void}){return <div className="chipchecks">{values.map(v=><button type="button" key={v} className={'chipcheck '+(selected.includes(v)?'selected':'')} aria-pressed={selected.includes(v)} onClick={()=>onChange(selected.includes(v)?selected.filter(x=>x!==v):[...selected,v])}>{selected.includes(v)&&<Check size={14}/>} {v}</button>)}</div>}
export function MiniDetails({date,time,location,places}:any){return <div className="mini-details">{date&&<span><CalendarDays size={15}/>{date}</span>}{time&&<span><Clock size={15}/>{time}</span>}{location&&<span><MapPin size={15}/>{location}</span>}{places&&<span><Users size={15}/>{places}</span>}</div>}
export function Modal({open,onClose,title,description,children,wide=false}:{open:boolean;onClose:()=>void;title:string;description?:string;children:React.ReactNode;wide?:boolean}){return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className={'cluvo-modal '+(wide?'wide':'')}><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>{description||'Bekijk de gegevens en bevestig je keuze.'}</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
export type FormField={key:string;label:string;type?:string;options?:any[];value?:any;required?:boolean;hint?:string};
export function FormModal({title,description,fields,onSave,onClose,submit='Opslaan'}:{title:string;description?:string;fields:FormField[];onSave:(values:any)=>void;onClose:()=>void;submit?:string}){const [v,setV]=useState<any>(Object.fromEntries(fields.map(f=>[f.key,f.value??(f.type==='multi'?[]:f.type==='check'?false:'')])));return <Modal open onClose={onClose} title={title} description={description}><form onSubmit={e=>{e.preventDefault();onSave(v)}}><div className="form-grid">{fields.map(f=><Field key={f.key} label={f.label} hint={f.hint}>{f.type==='select'?<SelectBox value={v[f.key]} onChange={x=>setV({...v,[f.key]:x})} options={f.options||[]}/>:f.type==='multi'?<CheckList values={f.options||[]} selected={v[f.key]} onChange={x=>setV({...v,[f.key]:x})}/>:f.type==='textarea'?<Textarea required={f.required} value={v[f.key]} onChange={e=>setV({...v,[f.key]:e.target.value})}/>:f.type==='check'?<Toggle label={f.hint||'Ja'} checked={v[f.key]} onChange={x=>setV({...v,[f.key]:x})}/>:<Input type={f.type||'text'} required={f.required} value={v[f.key]} onChange={e=>setV({...v,[f.key]:e.target.value})}/>}</Field>)}</div><div className="modal-actions"><Btn variant="secondary" onClick={onClose}>Annuleren</Btn><Button type="submit" className="btn primary">{submit}</Button></div></form></Modal>}
export function DownloadButton({onClick,label='Exporteren'}:{onClick:()=>void;label?:string}){return <Btn variant="secondary" onClick={onClick}><Download size={16}/>{label}</Btn>}
export function download(name:string,body:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),300);}
export function csv(rows:any[][]){return '\uFEFF'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n')}
