import Link from 'next/link';
import {notFound,redirect} from 'next/navigation';
import {PageTitle,Panel} from '@/components/cluvo/ui';
import {AccountHelpBanner} from '@/components/app/help-provider';
import {AdminTable} from '@/components/admin/admin-table';
import {AdminForm,PendingAdminCommand} from '@/components/admin/admin-form';
import {LifecycleForm} from '@/components/admin/lifecycle-form';
import {SupportRequestForm} from '@/components/admin/support-request-form';
import {PlatformAccountForm} from '@/components/admin/platform-account-form';
import {platformRead,requirePlatform} from '@/lib/admin/server';
import {platformSections,platformSectionPermission,rows,str,num,adminPermissionLabel,type AdminRow} from '@/lib/admin/contracts';
import {adminPending} from '@/lib/admin/pending';
import type {AdminField} from '@/lib/admin/forms';

const columns:Record<string,string[]>={tenants:['name','status','contact_name','active_accounts','last_sync_at'],staff:['display_name','permission_key','tenant_scope_id','ends_at','revoked_at'],defaults:['setting_key','version','updated_at'],integrations:['tenant_name','provider','status','configured','last_success_at'],delivery:['tenant_name','channel','state','total'],support:['tenant_name','purpose','scope_kind','state','ends_at'],audit:['action','tenant_id','actor_auth_user_id','occurred_at','reason'],modules:['module_key','enabled','version'],administrators:['display_name','role_name','scope_kind','ends_at','invitation_status','expires_at']};
const option=(data:AdminRow[])=>data.filter(r=>str(r.id)).map(r=>({value:str(r.id),label:str(r.name)||str(r.display_name)||str(r.id)}));
export default async function PlatformPage({params,searchParams}:{params:Promise<{section?:string[]}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {section:path=[]}=await params;const query=await searchParams;
 if(!path.length){const ctx=await requirePlatform();const first=platformSections.find(([s])=>ctx.permissions.some(p=>p.key===platformSectionPermission[s]&&(!['staff','defaults'].includes(s)||p.tenant_id===null)));if(!first)notFound();redirect(`/platform/${first[0]}`);}
 const section=path[0];if(!platformSections.some(([s])=>s===section)||path.length>2)notFound();
 const tenantId=section==='tenants'?path[1]:undefined;
 if(path[1]&&!tenantId)notFound();
 const ctx=await platformRead(tenantId?'tenant':section,{tenant:tenantId??query.tenant,query:query.q,status:query.status,actor:query.actor,after:query.after,before:query.before,resource:query.resource});const data=rows(ctx.read.rows);const row=tenantId?data[0]:null;if(tenantId&&!row)notFound();
 const title=row?str(row.name):platformSections.find(([s])=>s===section)![1];
 const can=(key:string,tenant?:string)=>ctx.permissions.some(p=>p.key===key&&(p.tenant_id===null||p.tenant_id===tenant));
 const pending=await adminPending({tenant:'00000000-0000-4000-8000-000000000001',person:ctx.actor});
 const selectedTab=query.tab??'general';const tabs=[['general','Algemeen'],['administrators','Beheerders'],['modules','Modules'],['integrations','Integraties'],['usage','Gebruik'],['audit','Historie']].filter(([tab])=>tab==='general'||tab==='usage'||tab==='modules'||can(tab==='integrations'?'platform.integration.manage':tab==='audit'?'platform.audit.read':'platform.tenant.manage',tenantId));
 let detail:AdminRow[]=[];
 if(row&&!tabs.some(([tab])=>tab===selectedTab))notFound();
 if(row&&!['general','usage'].includes(selectedTab))detail=rows((await platformRead(selectedTab,{tenant:tenantId})).read.rows);
 const tenantChoices=section==='support'?option(rows((await platformRead('support_scopes')).read.rows)):can('platform.tenant.read')?option(rows((await platformRead('tenants')).read.rows)):[];
 return <div className="cluvo-admin"><PageTitle eyebrow={row?'Vereniging · platformbeheer':'Cluvo · platformbeheer'} title={title} description="Operationele gegevens binnen jouw expliciete platformrechten."/><AccountHelpBanner topicId={`admin.platform.${section}.v1`}/>{pending.map(p=><PendingAdminCommand key={p.key} surface="platform" commandKey={p.key} label={p.command} input={p.input}/>)}
 {row?<><nav className="admin-tabs" aria-label="Verenigingsdetails">{tabs.map(([tab,label])=><Link key={tab} href={`/platform/tenants/${tenantId}?tab=${tab}`} aria-current={selectedTab===tab?'page':undefined}>{label}</Link>)}</nav>
 {selectedTab==='general'&&<><Panel title="Identiteit en onboarding"><AdminTable data={[row]} columns={['name','status','contact_name','contact_email','active_accounts']}/><div className="admin-onboarding">{row.onboarding_steps&&typeof row.onboarding_steps==='object'?Object.entries(row.onboarding_steps).map(([key,value])=><p key={key}>{key}: <b>{value===true?'Afgerond':'Nog te controleren'}</b></p>):<p>Onboardingstappen zijn nog niet vastgelegd.</p>}</div></Panel>{can('platform.tenant.manage',tenantId)&&row.status==='preparing'&&<InitialOnboarding row={row} actor={ctx.actor}/>}{can('platform.tenant.manage',tenantId)&&<div className="admin-two-columns"><AdminForm surface="platform" action="update_tenant" resourceId={tenantId} version={num(row.version)} values={row}/><LifecycleForm tenant={tenantId!} version={num(row.version)} status={str(row.status)}/></div>}</>}
 {selectedTab==='integrations'&&<Panel title="Veilige controle en ondersteuning"><p>Een platformrecht geeft geen toegang tot integratiecredentials. Vraag benoemde, tijdelijke ondersteuning aan bij de vereniging voor een actuele verbindingstest. De bestaande Sportlink-controle en import behouden hun eigen autorisatie en laatst bekende wedstrijden.</p><Link className="btn secondary" href="/platform/support">Ondersteuning aanvragen</Link></Panel>}
 {selectedTab==='usage'&&<Panel title="Beperkte gebruiksmeting"><p>{String(row.active_accounts)} actieve persoonlijke accounts.</p><p>Bron: actuele verenigingslidmaatschappen. Huishouddossiers, intake en financiële inhoud worden hier niet geladen.</p><p>Laatste geslaagde synchronisatie: {row.last_sync_at?String(row.last_sync_at):'Onbekend'}</p></Panel>}
 {!['general','usage'].includes(selectedTab)&&<Panel title={tabs.find(([tab])=>tab===selectedTab)?.[1]}><AdminTable data={detail} columns={columns[selectedTab]??['name','status']}/>{selectedTab==='administrators'&&can('platform.tenant.manage',tenantId)&&detail.filter(i=>i.invitation_kind==='initial'&&['pending','expired'].includes(str(i.invitation_status))).map(i=><details key={str(i.id)} className="admin-details"><summary>{str(i.display_name)} · uitnodiging intrekken</summary><AdminForm surface="platform" action="cancel_administrator_invitation" resourceId={str(i.id)} version={num(i.version)} values={{tenant_id:tenantId}} options={{tenant_id:[{value:tenantId!,label:str(row.name)}]}}/></details>)}{selectedTab==='modules'&&can('platform.tenant.manage',tenantId)&&detail.map(m=><details key={str(m.module_key)} className="admin-details"><summary>{str(m.module_key)} · beschikbaarheid wijzigen</summary><AdminForm surface="platform" action="set_module" resourceId={str(m.id)||undefined} version={num(m.version)} options={{tenant_id:[{value:tenantId!,label:str(row.name)}],module_key:[{value:str(m.module_key),label:str(m.module_key)}]}} values={{...m,tenant_id:tenantId}}/></details>)}</Panel>}
 </>:<>
 {['tenants','staff','audit'].includes(section)&&<form className="admin-filters" method="get"><label className="field"><span>Zoeken</span><input name="q" defaultValue={query.q??''} maxLength={200}/></label>{section==='audit'&&<>{[['tenant','Vereniging-ID'],['actor','Actor-ID'],['resource','Resource-ID']].map(([name,label])=><label key={name} className="field"><span>{label}</span><input name={name} defaultValue={query[name]??''}/></label>)}<label className="field"><span>Vanaf</span><input type="date" name="after" defaultValue={query.after??''}/></label><label className="field"><span>Tot en met</span><input type="date" name="before" defaultValue={query.before??''}/></label></>}{section==='tenants'&&<label className="field"><span>Status</span><select name="status" defaultValue={query.status??''}><option value="">Alle statussen</option>{['preparing','active','suspended','archived'].map(s=><option key={s}>{s}</option>)}</select></label>}<button className="btn secondary" type="submit">Toepassen</button></form>}
 {section==='overview'?<div className="secure-stat-grid">{Object.entries(ctx.read.rows).map(([key,value])=><article key={key}><span>{{tenant_count:'Verenigingen',active:'Actief',preparing:'In voorbereiding',suspended:'Gepauzeerd',archived:'Gearchiveerd'}[key]??key}</span><strong>{String(value)}</strong><Link href={`/platform/tenants${key==='tenant_count'?'':`?status=${key}`}`}>Verenigingen bekijken →</Link></article>)}</div>:<Panel><AdminTable data={data} columns={columns[section]??['name','state']} href={section==='tenants'?r=>`/platform/tenants/${str(r.id)}`:undefined}/></Panel>}
 {section==='tenants'&&can('platform.tenant.manage')&&<AdminForm surface="platform" action="create_tenant"/>}
 {section==='staff'&&<><PlatformAccountForm action="grant_staff" options={{tenant_scope_id:tenantChoices}}/>{data.filter(r=>!r.revoked_at).map(r=><details key={str(r.id)} className="admin-details"><summary>{str(r.display_name)} · {str(r.permission_key)} intrekken</summary><AdminForm surface="platform" action="revoke_staff" resourceId={str(r.id)} version={num(r.version)}/></details>)}</>}
 {section==='support'&&<><SupportRequestForm tenants={tenantChoices} disabled={pending.length>0}/>{data.filter(r=>['requested','approved'].includes(str(r.state))).map(r=><details key={str(r.id)} className="admin-details"><summary>{str(r.purpose)} · beëindigen</summary><AdminForm surface="platform" action="revoke_support" resourceId={str(r.id)} version={num(r.version)}/></details>)}</>}
 {section==='defaults'&&<DefaultEditors data={data}/>}
 {section==='integrations'&&<Panel title="Verzending"><AdminTable data={rows((await platformRead('delivery')).read.rows)} columns={columns.delivery}/><p>Een provideracceptatie is geen bewijs van aflevering. Alleen een bewezen tijdelijke fout kan binnen het bestaande aantal pogingen opnieuw worden gecontroleerd.</p>{rows((await platformRead('delivery_targets')).read.rows).map(d=><details key={str(d.id)} className="admin-details"><summary>{str(d.tenant_name)} · {str(d.channel)} · {str(d.state)}</summary><AdminTable data={[d]} columns={['state','provider_status','attempts','next_attempt_at']}/>{d.can_retry===true&&<AdminForm surface="platform" action="retry_delivery" resourceId={str(d.id)} version={num(d.version)}/>}</details>)}</Panel>}
 {section==='overview'&&<Panel title="Actualiteit"><p>Bron: actuele native verenigingsstatus. Beschikbaarheid van infrastructuur wordt niet uit deze telling afgeleid.</p><Link href="/platform/integrations">Integratie- en verzendmetingen bekijken →</Link></Panel>}
 </>}
 <p className="admin-observed">Peildatum: {new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Amsterdam'}).format(new Date(ctx.read.observed_at))} · actuele Cluvoadministratie</p></div>;
}
function DefaultEditors({data}:{data:AdminRow[]}){const definitions:Record<string,AdminField[]>={organization:[{name:'timezone',label:'Tijdzone',value:'Europe/Amsterdam',required:true},{name:'locale',label:'Taal',value:'nl-NL',required:true}],planning:[{name:'cancellation_minutes',label:'Afmeldtermijn in minuten',type:'number',value:2880,min:0,max:44640,required:true},{name:'confirmation_days',label:'Bevestigen binnen dagen',type:'number',value:7,min:1,max:365,required:true},{name:'dispute_days',label:'Fout melden binnen dagen',type:'number',value:14,min:1,max:365,required:true}],communication:[{name:'reminder_days',label:'Eerste herinnering in dagen',type:'number',value:7,min:1,max:30,required:true},{name:'reminder_hours',label:'Tweede herinnering in uren',type:'number',value:24,min:1,max:720,required:true}],template:[{name:'subject',label:'Onderwerp',required:true},{name:'text',label:'Standaardtekst',type:'textarea',required:true},{name:'sender_name',label:'Afzendernaam',value:'Cluvo',required:true}]};return <><Panel title="Bereik van deze wijziging"><p>Deze instellingen zijn platformstandaarden voor nieuwe inrichting. Bestaande verenigingsafspraken, templates, minuten en boekingsvoorwaarden behouden hun eigen versie. Een vereniging past een afwijking via haar eigen bevoegde besluit toe.</p></Panel><div className="admin-two-columns">{Object.entries(definitions).map(([key,fields])=>{const row=data.find(r=>r.setting_key===key);return <AdminForm key={`${key}:${row?.version??0}`} surface="platform" action="save_default" title={`Platformstandaard · ${key}`} resourceId={row?str(row.id):undefined} version={num(row?.version)} fields={[...fields,{name:'reason',label:'Reden',type:'textarea',required:true}]} nestedFields={fields.map(f=>f.name)} payload={{setting_key:key}} values={row?.value_json as Record<string,unknown>|undefined}/>;})}</div></>;}

function InitialOnboarding({row,actor}:{row:AdminRow;actor:string}){const rights=['vacancy.manage','volunteer_role.manage','hour_dispute.review','organization.manage','organization.access.manage','shift.view','shift.book','shift.manage','attendance.confirm','club_cluster.manage','committee.workspace.view','committee.workspace.manage','team_task.view','team_task.manage','team_task.market.approve','team_task.market.publish','household.view','household.progress.view','household.invite_executor','household.review','obligation.review','exception.review','exception.finalize','policy.manage','policy.follow_up','development.manage','communication.manage','report.season.view','season.close','season.rollover','match.view','match.import','match.review','finance.assessment.view','finance.assessment.prepare','finance.assessment.approve','finance.assessment.finalize','finance.fund.manage'];const options={tenant_id:[{value:str(row.id),label:str(row.name)}],auth_user_id:[{value:actor,label:'Mijn eigen geverifieerde persoonlijke account'}],permission_keys:rights.map(value=>({value,label:adminPermissionLabel(value)}))};return <Panel title="Eerste inrichting met expliciet mandaat"><p>Deze benoeming is uitsluitend mogelijk zolang de nieuwe vereniging geen bestaande beheergrants of verplichtingen heeft. Selecteer organisatiebeheer en toegangsbeheer, plus de afzonderlijke werkzaamheden die je werkelijk wilt toekennen.</p><div className="admin-two-columns"><PlatformAccountForm action="onboard_administrator" tenant={str(row.id)} values={{tenant_id:row.id,permission_keys:['organization.manage','organization.access.manage']}} options={options} initialAccount={{value:actor,label:'Mijn eigen geverifieerde persoonlijke account'}}/><PlatformAccountForm action="invite_administrator" tenant={str(row.id)} values={{tenant_id:row.id,permission_keys:['organization.manage','organization.access.manage']}} options={options}/><AdminForm surface="platform" action="onboard_season" values={{tenant_id:row.id}} options={options}/></div></Panel>;}
