'use client';

import {useState} from 'react';
import {CommandForm, type CommandField} from './command-form';
import {hasUnresolvedMobileCommand, Pick} from './primitives';
import type {MobileSnapshot} from './types';

export function ClubTaskCreation({snapshot, onConfirmed}: {snapshot: MobileSnapshot; onConfirmed: () => void}) {
  const [mode, setMode] = useState('public');
  const [receivingTeam, setReceivingTeam] = useState<{id: string; version: number} | null>(null);
  const distributed = mode !== 'public';
  const fields: CommandField[] = [{name: 'title', label: 'Taaknaam', required: true}, {name: 'task_type_version_id', label: 'Categorie', type: 'select', required: true, options: (snapshot.taskTypes ?? []).map((type) => ({value: type.id, label: type.title}))}, {name: 'starts_at', label: 'Begint op', type: 'datetime-local', required: true}, {name: 'ends_at', label: 'Eindigt op', type: 'datetime-local', required: true}, {name: 'capacity', label: 'Aantal plaatsen', type: 'number', min: 1, max: 30, value: 1, required: true}, {name: 'minimum_age', label: 'Minimumleeftijd', type: 'number', min: 16, max: 100, value: 16}, {name: 'qualification_type_id', label: 'Vereist certificaat (optioneel)', type: 'select', options: [{value: '', label: 'Geen certificaat vereist'}, ...(snapshot.qualificationTypes ?? []).map((type) => ({value: type.id, label: type.name}))]}, {name: 'min_qualified_count', label: 'Minimaal aantal bevoegde uitvoerders', type: 'number', min: 0, max: 30, value: 0}, {name: 'buddy_allowed', label: 'Begeleiding met een bevoegd maatje toestaan', type: 'checkbox'}, {name: 'repeat_count', label: 'Herhalen', type: 'select', value: '1', options: [{value: '1', label: 'Eenmalig'}, {value: '4', label: '4 weken'}, {value: '8', label: '8 weken'}]}, {name: 'instructions', label: 'Praktische instructies', type: 'textarea', required: true}, ...(distributed ? [{name: 'self_until', label: 'Zelf inschrijven tot', type: 'datetime-local' as const, required: true}, {name: 'assign_until', label: 'Teamouder verdeelt tot', type: 'datetime-local' as const, required: true}, {name: 'counts_for_team', label: 'Telt mee voor het teamdoel', type: 'checkbox' as const, value: true}] : [])];
  return <><Pick label="Verdelingswijze" value={mode} onChange={(value) => {if (!hasUnresolvedMobileCommand()) setMode(value);}} options={[{value: 'public', label: 'Vrije verenigingsmarkt'}, ...(snapshot.canManageClubClusters === true && snapshot.receivingTeams?.length ? [{value: 'self', label: 'Besloten teammarkt, daarna verdelen'}, {value: 'assign', label: 'Teamouder wijst direct toe'}] : [])]} />{distributed && <Pick label="Ontvangend team" value={receivingTeam?.id ?? ''} onChange={(value) => {if (hasUnresolvedMobileCommand()) return; const team = snapshot.receivingTeams?.find((item) => item.id === value); setReceivingTeam(team ? {id: team.id, version: team.version} : null);}} options={(snapshot.receivingTeams ?? []).map((item) => ({value: item.id, label: item.name}))} />}{distributed && <p className="notice blue">De plaatsen worden direct voor het gekozen team gereserveerd. De teamouder verdeelt ze over leden; ieder huishouden bevestigt zelf de uitvoerder.</p>}<CommandForm snapshot={snapshot} command="create_club_task" resourceId={snapshot.workspace.tenant_id} payload={{season_id: snapshot.season?.id, distribution_mode: mode, ...(distributed ? {receiving_team_id: receivingTeam?.id, receiving_team_expected_version: receivingTeam?.version} : {})}} fields={fields} transform={(values) => ({...values, repeat_count: Number(values.repeat_count), qualification_type_id: values.qualification_type_id || null})} disabledReason={!snapshot.season ? 'Kies het seizoen voor deze taak.' : !snapshot.taskTypes?.length ? 'Er is geen gepubliceerd taaktype beschikbaar in je actuele commissiescope.' : distributed && snapshot.canManageClubClusters !== true ? 'Het verdelen van clubplaatsen vraagt een actuele clubclusterbevoegdheid. Kies de vrije verenigingsmarkt.' : distributed && !receivingTeam ? 'Kies het concrete ontvangende team.' : undefined} submit={distributed ? 'Publiceer en reserveer deze teamplaatsen' : 'Publiceer op de verenigingsmarkt'} onConfirmed={onConfirmed} /></>;
}
