import type {WorkspaceContext} from '@/lib/auth/workspace';

export const MOBILE_SCREENS = ['home', 'tasks', 'agenda', 'teams', 'more', 'actions', 'notifications', 'manage', 'profile', 'household', 'policies', 'courses', 'opportunities', 'messages', 'settings', 'help', 'install', 'reports', 'finance', 'committees'] as const;
export type MobileScreen = typeof MOBILE_SCREENS[number];
export type MobileResource = {id: string; version: number};
export type MobilePerson = MobileResource & {name: string; verified: boolean; adult: boolean; ageBand?: string; canExecute: boolean};
export type MobileTask = MobileResource & {title: string; category: string; kind: 'club' | 'team'; startsAt: string; endsAt: string; location: string; minutes: number; capacity: number; freePlaces: number; instructions: string; minAge: number; qualification: string; cancelDays: number; teamId?: string; positionId?: string; positions?: {id: string; ordinal: number; allocationId?: string}[]; instructionVersionId?: string; taskTypeVersionId?: string; canBook: boolean; canWaitlist?: boolean; canManage?: boolean; canConfirm: boolean; state: string; requestedMinutes?: number; matchReviewed?: boolean};
export type MobilePlanningTask = MobileResource & {state: 'draft' | 'published'; committeeId: string; committeeName: string; category: string; title: string; startsAt: string; endsAt: string; location: string; minutes: number; positions: number};
export type MobileBooking = MobileResource & {taskId: string; positionId?: string; executorId: string; executorName: string; householdId: string; state: string; minutes: number; startsAt?: string; endsAt?: string; instructions?: string; location?: string; cancellationDeadline?: string; teamId?: string; memberName?: string; canCancel: boolean; canReplace: boolean; canPrepare: boolean; canFeedback: boolean; canConfirm: boolean; replacementRequested: boolean};
export type MobileAllocation = MobileResource & {taskId: string; teamId: string; memberId?: string; memberName?: string; position: number; positionId?: string; clusterId?: string; clusterVersion?: number; selfUntil?: string; assignUntil?: string; canChoose: boolean; canAssign: boolean; canRequestReserve?: boolean; bookingId?: string; bookingVersion?: number; bookingState?: string; executorName?: string; countsForTeam: boolean};
export type MobileCommitteeAllocation = MobileResource & {taskId: string; teamId: string; committeeId: string; clusterId: string; clusterVersion: number; positionId: string; position: number; title: string; startsAt: string; endsAt: string; state: string; selfUntil: string; assignUntil: string; canRequestReserve: boolean};
export type MobileTeamMember = MobileResource & {name: string; householdId: string; goal: number; goalVersion?: number; completed: number; planned: number; assigned: number; unallocated: number; canAdjust: boolean};
export type MobileTeam = MobileResource & {name: string; parentName: string; goal: number; goalVersion?: number; handoverVersion?: number; canManage: boolean; members: MobileTeamMember[]};
export type MobileProgress = {confirmed: number; planned: number; pending: number; target: number; winterTarget: number; winterConfirmed: number; remaining: number; exempt: boolean};
export type MobileActionDetail = {kind: 'work_card' | 'subtask' | 'card_mention' | 'event_mention' | 'team_task' | 'policy_question'; resourceId: string; resourceVersion?: number; parentVersion?: number; title: string; text: string; state: string; dueAt?: string; parentTitle: string; resolution?: string; creditMinutes?: number; parentKind: 'card' | 'event' | 'team' | 'policy'; parentId: string; parentHref?: string};
export type MobileAction = MobileResource & {title: string; detail: string; label: string; due?: string; href: string; detailResource?: MobileActionDetail};
export type MobileNotification = MobileResource & {title: string; text: string; kind: string; read: boolean; href: string};
export type MobileCalendarEvent = MobileResource & {title: string; startsAt: string; endsAt: string | null; location: string; fieldName?: string; lockerRoom?: string; state?: string; kind: 'task' | 'match' | 'event' | 'assignment'; personId?: string; personName?: string; teamName?: string; taskId?: string; bookingId?: string; allocationId?: string; description: string; canJoin: boolean; joined: boolean; attendees: number};
export type MobilePolicy = MobileResource & {title: string; publishedAt: string; text: string; accepted: boolean; subjects: {id: string; name: string; accepted: boolean; canAccept?: boolean; needsOpening?: boolean; assignmentId?: string; assignmentVersion?: number; capacity?: 'self' | 'guardian'}[]};
export type MobileCourse = MobileResource & {title: string; startsAt: string; qualification: string; capacity: number; enrolledCount: number; enrolled: boolean};
export type MobileQualification = MobileResource & {title: string; expiresAt?: string; valid: boolean};
export type MobileOpportunity = MobileResource & {title: string; committee: string; expectedMinutes: number | null; commitment: string; description: string; exemptionPossible: boolean; interested: boolean};
export type MobileChannel = MobileResource & {name: string; kind: 'team' | 'committee'};
export type MobileMessage = MobileResource & {channelId: string; authorName: string; own: boolean; text: string; sentAt: string};
export type MobileQuestion = MobileResource & {householdId?: string; subject: string; text: string; answer?: string; history?: {state: string; at: string}[]; state: string; own: boolean; canReview: boolean};
export type MobileFeedback = MobileResource & {taskId: string; taskTitle: string; text: string; clarity: string; canImprove: boolean};
export type MobileCommittee = MobileResource & {name: string; canManage: boolean};
export type MobileDocument = MobileResource & {committeeId?: string; title: string; text: string; revision?: number; downloadHref?: string; checklist: string[]};
export type MobileCard = MobileResource & {committeeId: string; boardId?: string; columnId?: string; title: string; text: string; state: string; canManageDetails?: boolean; assigneeIds?: string[]; deadline: string; assignees: string[]; canEdit: boolean; checks: {id: string; version?: number; text: string; done: boolean}[]; comments: {id: string; version?: number; own?: boolean; authorName: string; text: string; sentAt: string}[]};
export type MobileHandover = MobileResource & {teamId: string; fromName: string; toName: string; note: string; successorId?: string; checks: string[]; checkValues?: boolean[]; state: string; canAccept: boolean; canPrepare: boolean};
export type MobileFinanceEntry = MobileResource & {title: string; amountCents: number; kind: 'income' | 'expense' | 'reservation'; state: string; availableDelta?: number; reservedDelta?: number; spentDelta?: number};
export type MobileReport = MobileResource & {name: string; progress: MobileProgress};
export type MobileProfile = MobileResource & {experience: string; preferences: string[]; talents: string[]; availability: string[]; monthlyMinutes: number; boundaries: string; reserve: boolean; buddy: boolean};
export type MobileCapabilities = Partial<Record<MobileScreen, {available: boolean; reason?: string}>>;
export type MobileSnapshot = {
  workspace: WorkspaceContext;
  workspaces: {slug: string; name: string}[];
  season: {id: string; name: string} | null;
  seasons?: {id: string; name: string}[];
  households?: {id: string; name: string}[];
  householdMemberIds?: string[];
  qualificationTypes?: {id: string; name: string}[];
  matches?: {id: string; name: string}[];
  taskTypes?: {id: string; title: string; category: string}[];
  handoverCandidates?: {id: string; name: string; teamId: string}[];
  transferOffers?: (MobileResource & {taskId: string; positionId?: string; expiresAt: string})[];
  buddies?: {bookingId: string; version: number; personId: string; name: string; taskId: string; qualified: boolean}[];
  reserveCandidates?: {allocationId: string; personId: string; name: string; reason?: string}[];
  reserveRequests?: (MobileResource & {allocationId: string; positionId: string; taskId: string; memberId?: string; canBook: boolean})[];
  teamCreditRequests?: (MobileResource & {teamId: string; title: string; requestedMinutes: number; approvedMinutes: number | null; state: string; refereeNeeded: boolean; matchId?: string; matchReviewed: boolean; canReviewMatch: boolean; canReviewVolunteer: boolean; canPublish: boolean})[];
  suitability?: {positionId: string; taskId: string; personId: string; obligationId: string; eligible: boolean; executorEligible?: boolean; capacityFull?: boolean; reason: string; eligibleWithBuddy?: boolean; canWaitlist?: boolean; canTransfer?: boolean}[];
  ledgerHistory?: {id: string; minutesDelta: number; performedAt: string; postedAt: string; kind: string; bookingId?: string; reversesEntryId?: string; reason: string; evidenceKind: string; evidenceHref: string}[];
  assigneeCandidates?: {committeeId: string; personId: string; name: string}[];
  instructionTargets?: {sourceTaskId: string; taskId: string; version: number; title: string; startsAt: string}[];
  receivingTeams?: (MobileResource & {name: string})[];
  canManageClubClusters?: boolean;
  reservePreview?: {positionId: string; taskId: string; canReserve: boolean; reason: string}[];
  committeeAllocations?: MobileCommitteeAllocation[];
  committeeClusters?: (MobileResource & {teamId: string; committeeId: string; title: string; selfUntil: string; assignUntil: string; canFollowup: boolean})[];
  distributionProposals?: {teamId: string; assignments: {allocationId: string; expectedVersion: number; memberId: string; reason: string}[]}[];
  pendingCommands?: {idempotencyKey: string; command: string}[];
  helpSeen?: string[];
  adminAccess?: {club:boolean;platform:boolean};
  executors?: {personId: string; obligationId: string}[];
  preferenceVersion?: number;
  serverPreferences?: {email?: boolean; push?: boolean; inbox?: boolean; reminders?: boolean; team?: boolean; news?: boolean};
  timezone: string;
  readAt: string;
  pushPublicKey?: string | null;
  modules?: Record<string, boolean>;
  capabilities: MobileCapabilities;
  commands: string[];
  profile: MobileProfile | null;
  household: (MobileResource & {name: string; canInvite: boolean; obligationId?: string}) | null;
  progress: MobileProgress | null;
  people: MobilePerson[];
  tasks: MobileTask[];
  committeePlanning?: MobilePlanningTask[];
  bookings: MobileBooking[];
  allocations: MobileAllocation[];
  teams: MobileTeam[];
  actions: MobileAction[];
  notifications: MobileNotification[];
  agenda: MobileCalendarEvent[];
  policies: MobilePolicy[];
  courses: MobileCourse[];
  qualifications: MobileQualification[];
  opportunities: MobileOpportunity[];
  channels: MobileChannel[];
  messages: MobileMessage[];
  questions: MobileQuestion[];
  feedback: MobileFeedback[];
  committees: MobileCommittee[];
  boards?: (MobileResource & {committeeId: string; name: string; columns: {id: string; title: string}[]})[];
  cards: MobileCard[];
  documents: MobileDocument[];
  handovers: MobileHandover[];
  reports: MobileReport[];
  finance: MobileFinanceEntry[];
  preferences: {email: boolean; reminders: boolean; team: boolean; news: boolean};
  canManageClubContact?: boolean;
  contact: {name: string; description: string; version?: number; email?: string; phone?: string} | null;
};
export type MobileCommandInput = {club: string; command: string; resourceId?: string; idempotencyKey: string; expectedVersion: number; payload: Record<string, unknown>};
export type MobileCommandResult = {status: 'confirmed' | 'rejected' | 'unknown'; message: string; idempotencyKey: string};
