export type HelpTopic = {id: string; title: string; text: string};
type Entry = readonly [id: string, title: string, text: string];
const topics = (entries: readonly Entry[]) => Object.fromEntries(entries.map(([id,title,text]) => [id,{id,title,text}])) as Record<string,HelpTopic>;

export const HELP_TOPICS = topics([
  ['page.overzicht','Jouw startpunt in Cluvo','Hier zie je wat er speelt in jouw huishouden, team en vereniging. Open een actie om die af te handelen, of kies een onderdeel in het menu.'],
  ['page.taken','Kies een verenigingstaak','Op deze takenmarkt kun je zelf een open verenigingstaak kiezen. Filter op wat bij je past, open een taak en kies wie uit jouw huishouden deze uitvoert.'],
  ['page.diensten','Jouw taken en afspraken','Hier staan je verenigingstaken en teamtaken. Bekijk komende taken, kies een uitvoerder voor een toegewezen plek of vraag een overname als je niet kunt.'],
  ['page.gezin','Alles voor je gezin bij elkaar','Deze agenda brengt de taken en wedstrijden van jouw huishouden samen. Open een afspraak voor de details en controleer de waarschuwing wanneer tijden overlappen.'],
  ['page.ruilmarkt','Een taak overnemen of ruilen','Hier vind je verenigingstaken waarvoor iemand een vervanger zoekt. Kies een taak, selecteer de uitvoerder en bevestig de overname of ruil. Tot dat moment blijft de oorspronkelijke afspraak staan.'],
  ['page.planbord','Het rooster van de vereniging','Kies een commissie en datum om de verenigingstaken te plannen. Voeg taken toe, gebruik een sjabloon of verplaats een tijdblok. Controleer de wijziging voordat je die bevestigt.'],
  ['page.huishoudens','Samen bijdragen als huishouden','Hier bekijk je wie bij een huishouden hoort en hoeveel verenigingsuren zijn bevestigd. Zoek een huishouden en open het dossier voor personen, afspraken en aanvragen.'],
  ['page.intake','Vertel wat bij jou past','Met je profiel kan de vereniging passende taken voorstellen. Vul per persoon de talenten, voorkeuren en beschikbaarheid in en sla je gegevens op.'],
  ['page.commissies','Samenwerken in een commissie','Kies een commissie om het werk, de mensen en de praktische kennis te bekijken. Gebruik de tabbladen om een lid toe te voegen of documenten en instructies te delen.'],
  ['page.kanban','Van actie naar afgerond werk','Op het kanbanbord staat wie welke actie oppakt. Voeg een kaart toe, open die voor afspraken en verplaats de kaart naar de volgende kolom als het werk verder is.'],
  ['page.teams','Taken organiseren binnen het team','Kies je team om verenigingstaken en eigen teamtaken te bekijken. Leden kunnen een open plek kiezen; de teamouder kan taken verdelen en de voortgang per lid volgen.'],
  ['page.wedstrijden','Wedstrijden en bijbehorende taken','Hier zie je wanneer en waar teams spelen. Filter op een team of jouw gezin en controleer een wedstrijdwijziging wanneer die invloed heeft op de planning.'],
  ['page.agenda','De jaaragenda van je club','Deze kalender toont activiteiten, wedstrijden en verenigingstaken samen. Kies een maand of soort afspraak en open een kalenderitem voor de details.'],
  ['page.berichten','Berichten en meldingen op één plek','Open een gesprek om mee te praten of bekijk de meldingen voor jouw taken. Bij Voorkeuren kies je over welke onderwerpen je een melding wilt ontvangen.'],
  ['page.acties','Weet wat jouw volgende stap is','Bovenaan staan acties die jouw aandacht vragen. Open een actie om deze af te handelen; gebruik het persoonlijke kanbanbord voor je overige afspraken.'],
  ['page.beleid','De afspraken van de vereniging','Hier staan de geldende afspraken en jouw bevestigingen. Lees een document, stel zo nodig een vraag en bevestig daarna de versie die je hebt gelezen.'],
  ['page.waardering','Aandacht voor de mensen in de club','Hier kun je inzet waarderen en een moment van aandacht vastleggen. Bekijk ook de terugblik na een uitgevoerde taak om te delen wat goed ging en wat beter kan.'],
  ['page.opleidingen','Leren en hulp krijgen bij een taak','Bekijk een opleiding, zoek een ervaren maatje of meld je aan voor de reservepool. Bij Kwalificaties zie je welke bevoegdheden zijn vastgelegd.'],
  ['page.vacatures','Een vaste vrijwilligersfunctie vinden','Hier staan functies waarmee je vaker kunt bijdragen aan de vereniging. Open een functie, lees wat erbij hoort en geef je belangstelling door als die bij je past.'],
  ['page.rapportages','Zien waar de club hulp kan gebruiken','Deze overzichten tonen de bezetting, huishouduren en het aanbod aan taken. Gebruik de filters en export om met de commissie te bepalen waar actie nodig is.'],
  ['page.financien','Bijdragen en besteding volgen','Hier zie je de vrijwilligerspot, de seizoensafrekening en financiële afspraken. Kies een tabblad voor het juiste overzicht en open een regel om die te beoordelen.'],
  ['page.templates','Gericht communiceren met je club','Maak een bericht met een bewaard template of kies een passende groep ontvangers. Controleer altijd het voorbeeld en de geselecteerde groep voordat je de verzending in de demo vastlegt.'],
  ['page.instellingen','De clubafspraken instellen','Kies links het onderdeel dat je wilt aanpassen, zoals uren, rollen of het seizoen. Controleer de waarden en sla ze op; de andere werkruimtes gebruiken deze instellingen.'],

  ['panel.next-actions','Begin met de open acties','Dit zijn de stappen die jij nu kunt zetten, zoals een uitvoerder kiezen of een uitvoering bevestigen. Druk op de knop naast de actie om meteen naar de juiste functie te gaan.'],
  ['panel.matches','De komende wedstrijden','Hier zie je de eerstvolgende wedstrijden die bij je gezin horen. Open het wedstrijdoverzicht voor alle teams, locaties en tijden.'],
  ['panel.upcoming','Wat komt er binnenkort aan?','Dit overzicht helpt je vooruit te kijken naar taken en activiteiten. Open de agenda of een taak om de datum, locatie en afspraken te bekijken.'],
  ['panel.household','De inzet van jouw huishouden','Bevestigde uren tellen mee voor het huishoudelijke doel; geplande uren zijn nog niet uitgevoerd. Open het huishouddossier voor de personen en afspraken die hierbij horen.'],
  ['panel.dashboard-advice','Taken die aandacht vragen','Hier staan passende taken of plekken die nog hulp nodig hebben. Open de takenmarkt om te bekijken wat jij kunt doen en een geschikte taak te kiezen.'],
  ['panel.work-together','Lopende acties in de club','Hier zie je het werk waar mensen samen aan bezig zijn. Open een kaart of het kanbanbord om de verantwoordelijke, deadline en vervolgstap te bekijken.'],
  ['panel.my-interest','Jouw belangstelling voor een functie','Dit overzicht bewaart voor welke vaste functies je belangstelling hebt getoond. Bekijk de status om te zien of de commissie je aanvraag nog bespreekt.'],
  ['panel.committee-work','Het werk van deze commissie','Hier zie je de actuele acties en afspraken van de gekozen commissie. Open een kaart om de details te lezen of ga naar het bord om het werk te verdelen.'],
  ['panel.committee-members','Wie doet mee in de commissie?','Hier vind je de leden en hun rol. Kies Commissielid toevoegen om iemand aan de commissie te koppelen en leg de rol vast.'],
  ['panel.instructions','Praktische kennis bewaren','Hier vind je uitleg die helpt om het werk goed uit te voeren. Open een instructie om die te lezen of voeg kennis toe voor de volgende vrijwilliger.'],
  ['panel.documents','Documenten van de commissie','Bewaar hier de documenten die de commissie nodig heeft. Open een document om het te lezen of gebruik Kennis toevoegen om iets nieuws vast te leggen.'],
  ['panel.notification-preferences','Kies welke meldingen bij je passen','Zet per onderwerp aan of uit of je hierover een melding wilt krijgen. Je voorkeuren helpen om berichten relevant te houden.'],
  ['panel.template','Een berichttemplate gebruiken','Een template geeft je een vaste basis voor een bericht. Pas de tekst aan bij Bewerken en controleer bij Voorbeeld hoe het bericht wordt weergegeven.'],
  ['panel.send-rules','Een bericht op het juiste moment','Hier stel je in bij welke gebeurtenis een bericht klaar moet staan. Kies het onderwerp en de regel; controleer daarna het bijbehorende template.'],
  ['panel.segments','De juiste mensen vinden','Filter op talenten, voorkeuren of andere kenmerken om een passende groep te vinden. Controleer de uitkomst en bewaar de groep als je die vaker wilt gebruiken.'],
  ['panel.saved-segments','Een bewaarde groep opnieuw gebruiken','Deze groepen bewaren je eerdere selectie. Kies een groep om de mensen te bekijken of die groep opnieuw voor een bericht te gebruiken.'],
  ['panel.send-log','Eerdere demo-verzendingen bekijken','Hier zie je welke berichten in het prototype zijn vastgelegd en voor welke groep. Open een regel om de inhoud en het resultaat terug te lezen.'],
  ['panel.club-settings','De basisgegevens van de club','Pas hier de gegevens en afspraken van dit onderdeel aan. Controleer de ingevulde waarden en kies Opslaan om ze in de demo te gebruiken.'],
  ['panel.hours-settings','Het urenbeleid van de vereniging','Stel het urendoel, winterdoel en de termijnen in. Controleer ook de financiële bijdrage en kies Instellingen opslaan. Deze afspraken gelden voor de huishoudelijke verenigingsinzet.'],
  ['panel.association-tasks','De afspraken uit de verenigingstakenmarkt','Kies Komend voor geplande taken, Te bevestigen voor taken die gecontroleerd moeten worden of Historie voor eerdere registraties. Open een taak voor de details of gebruik de actieknoppen naast de afspraak.'],
  ['panel.roster','Het rooster lezen en aanpassen','Groen betekent dat een plaats is gevuld; blauw is open en geel is een concept. Klik op een blok om de taak te bewerken. In de dagweergave kun je een blok slepen of de rechterrand verschuiven en daarna de wijziging bevestigen.'],
  ['panel.volunteer-roles','Wanneer een vaste rol voldoende inzet is','Hier bepaal je welke vaste vrijwilligersrollen meetellen als voldoende bijdrage. Voeg een rol toe en geef aan welke afspraak voor die rol geldt.'],
  ['panel.appointments','Vaste rollen toekennen en volgen','Dit overzicht toont wie een vaste vrijwilligersrol vervult. Controleer de aanstelling en leg wijzigingen vast vanuit het huishouddossier.'],
  ['panel.match-sync','Wedstrijdwijzigingen controleren','Hier kun je de wedstrijdgegevens in de demo bijwerken. Start de controle en beoordeel daarna de wijzigingen die gevolgen hebben voor taken of afspraken.'],
  ['panel.import','Leden eerst controleren, daarna toevoegen','Met de import voeg je ledengegevens toe na een controle van de kolommen en gevonden verschillen. Gebruik de voorbeeldimport en controleer de uitkomst voordat je die bevestigt.'],
  ['panel.sign-in','Aanmelden via e-mail en een code','Deze functie laat zien hoe iemand met een eenmalige code kan aanmelden. Vul een e-mailadres in en doorloop de demonstratie met de getoonde voorbeeldcode.'],
  ['panel.install','Cluvo snel openen op je telefoon','Je kunt Cluvo als snelkoppeling op je beginscherm zetten. Gebruik de installatieknop als je browser die aanbiedt; anders volg je de aanwijzingen voor jouw telefoon.'],
  ['panel.demo-reset','De voorbeeldgegevens herstellen','Hier kun je opnieuw beginnen met de oorspronkelijke voorbeeldgegevens. Kies Herstellen en bevestig je keuze. De uitleg die je al hebt gesloten blijft voor jou onthouden.'],
  ['panel.new-season','De afspraken voor een nieuw seizoen','Bereid het nieuwe seizoen voor met de juiste doelen en datums. Open Seizoensvoorbereiding, controleer de instellingen en bevestig ze wanneer alles klopt.'],
  ['panel.season-history','Vorige seizoenen teruglezen','Hier staan bewaarde standen van eerdere seizoenen. Gebruik dit overzicht om terug te kijken zonder de huidige seizoensafspraken te veranderen.'],
  ['panel.audit','Terugzien wat is gewijzigd','Deze historie toont welke handelingen in het prototype zijn gedaan en door welke voorbeeldpersoon. Lees de regels om een wijziging of afspraak terug te vinden.'],
  ['panel.clusters','Verenigingstaken aan een team geven','Bundel vrije plaatsen in een cluster en wijs dat toe aan een team. Kies of leden zelf inschrijven, de teamouder verdeelt of beide. Het huishouden bevestigt daarna de uitvoerder.'],
  ['panel.team-planning','Van toewijzing naar bevestigde uitvoerder','Hier zie je per plaats wie aan de beurt is en wie de taak uitvoert. Wijs een open plaats toe aan een lid of kies als huishouden de uitvoerder; alleen een bevestigde uitvoerder maakt de plek bemenst.'],
  ['panel.team-progress','Het teamdoel per lid volgen','Vergelijk het seizoensdoel met de uitgevoerde, ingeplande en toegewezen taken. Als teamouder kun je het doel per lid aanpassen. Alleen een bevestigde uitvoering telt als voltooid.'],
  ['panel.team-households','Verenigingsuren per huishouden','Dit overzicht telt de verenigingsuren voor elk huishouden één keer, ook als kinderen in meerdere teams spelen. Gebruik de resterende uren om samen de inzet te plannen.'],
  ['panel.choose-executor','Kies wie de toegewezen taak doet','Er is een plaats aan jouw huishouden toegewezen, maar de uitvoerder is nog niet bevestigd. Kies Uitvoerder kiezen, selecteer een geschikt gezinslid en bevestig de afspraak.'],
  ['panel.my-team-tasks','Taken die via het team zijn geregeld','Hier staan de teamafspraken en de gekozen uitvoerders. Wissel tussen Komend en Historie. Vraag een overname als je niet kunt; de afspraak blijft staan tot een vervanger bevestigt.'],
  ['panel.team-actions','Open stappen voor het team','Dit overzicht toont teamtaken die nog een keuze of oplossing nodig hebben. Open de actie om een uitvoerder te kiezen, een plaats te verdelen of een verhindering op te lossen.'],
  ['panel.my-teams','Naar jouw teamwerkruimte','Hier zie je de teams en hun seizoensdoel. Kies Mijn teams openen om taken te bekijken, te verdelen of de voortgang per lid te volgen.'],
  ['panel.distribution-settings','Kies hoe de vereniging taken verdeelt','Met de vrije takenmarkt kiezen mensen zelf een taak. Met teamtoewijzing krijgt een team een cluster. Stel hier de standaard in; per taak of cluster kun je een andere keuze maken.'],
  ['panel.smart-distribution','Een passend verdeelvoorstel','Cluvo stelt een verdeling voor op basis van beschikbaarheid, geschiktheid en eerdere inzet. Controleer de voorstellen, pas de leden zo nodig aan en bevestig. De huishoudens kiezen daarna zelf de uitvoerder.'],
  ['panel.follow-up','Open plaatsen op tijd oplossen','Eerst kunnen leden zelf inschrijven, daarna verdeelt de teamouder en zo nodig helpt de commissie. Bekijk de fase, pas deadlines aan of open de verdeling. In deze demo start je de controle met Opvolging controleren.'],
  ['panel.handover','Het team zorgvuldig overdragen','Bewaar de afspraken, controleer de checklist en kies de volgende teamouder. Zet de overdracht klaar; pas wanneer de opvolger deze aanvaardt, gaat de verantwoordelijkheid over.'],
  ['panel.feedback-inbox','Leren van de ervaringen van vrijwilligers','Hier lees je de terugblikken op taken waarvoor jij verantwoordelijk bent. Open een reactie en verbeter waar nodig de instructie voor een volgende uitvoering.'],
  ['panel.personal-feedback','Na een taak kort terugblikken','Vertel na een uitgevoerde taak of je die nog eens wilt doen en of de uitleg duidelijk was. Kies Terugblikken bij een taak en beantwoord de twee korte vragen.'],
  ['panel.family-hours','Uren en teamtaken blijven apart','Bevestigde verenigingsuren tellen één keer voor jullie huishouden. De teamdoelen tellen taken per kind. Bekijk beide standen om te zien wat nog nodig is.'],
  ['panel.policy-confirmations','Jouw gelezen afspraken','Hier zie je welke beleidsversies je hebt bevestigd. Open het document wanneer je de afspraak wilt teruglezen of een nieuwe versie wilt bekijken.'],
  ['panel.training-buddy','Een eerste taak samen doen','Een ervaren maatje helpt je bij een taak waarvoor je nog ervaring of een bevoegdheid opbouwt. Bekijk de beschikbare begeleiding en kies een passende eerste verenigingstaak.'],
  ['panel.reserve','Af en toe extra helpen','De reservepool is voor mensen die vrijwillig willen bijspringen als er een plek open blijft. Zet je beschikbaarheid aan als je hiervoor benaderd wilt worden.'],
  ['panel.qualifications','Bevoegdheden bijhouden','Hier zie je de vastgelegde kwalificaties en wanneer ze opnieuw gecontroleerd moeten worden. Voeg als verantwoordelijke een kwalificatie toe en controleer de geldigheid.'],
  ['panel.budget','Waar de vrijwilligerspot naartoe gaat','Dit overzicht laat zien welke bedragen voor welk doel zijn gereserveerd. Bekijk de posten of voeg als verantwoordelijke een nieuwe budgetpost toe.'],
  ['panel.committee-capacity','Bezetting per commissie vergelijken','Hier zie je hoeveel verenigingstaken zijn bemenst en waar nog plekken open zijn. Gebruik dit overzicht om hulp te richten op de commissies die die nodig hebben.'],
  ['panel.winter-target','De voortgang richting het winterdoel','Dit overzicht vergelijkt de bevestigde huishouduren met het afgesproken winterdoel. Bekijk huishoudens die nog inzet nodig hebben en plan samen passende taken.'],
  ['panel.supply','Is er genoeg passend aanbod?','Hier vergelijk je het beschikbare takenaanbod met de inzet die nog nodig is. Gebruik de uitkomst om extra taken te plannen of het bestaande aanbod beter te verdelen.'],
  ['panel.volunteer-care','Aandacht waar dat nodig is','Hier zie je signalen die helpen om vrijwilligers te ondersteunen en te waarderen. Bekijk wat aandacht vraagt en maak samen een passende vervolgafspraak.'],

  ['team.market','De besloten teamtakenmarkt','Deze taken zijn alleen voor dit team: eigen teamtaken en verenigingstaken die aan het team zijn gegeven. Open een vrije plek, kies namens welk lid je meedoet en bevestig wie uit het huishouden de taak uitvoert.'],
  ['team.advisor','Welk team past bij het cluster?','Selecteer eerst de vrije plaatsen hierboven. Vergelijk daarna de teams en de redenen bij het voorstel. Kies het gewenste team; de uiteindelijke uitvoerders worden later door de huishoudens bevestigd.'],
  ['family.timeline','Jullie afspraken in tijdsvolgorde','Taken en wedstrijden van het hele huishouden staan hier bij elkaar. Kies Komend of Historie en open een afspraak om de uitvoerder, taakstatus of locatie te bekijken.'],
  ['family.member-goals','Het doel van ieder kind','Elk kind heeft een eigen teamdoel voor dit seizoen. Kijk naar uitgevoerd, ingepland en nog toegewezen om te zien welke taken al geregeld zijn en welke nog aandacht vragen.'],
  ['households.winter','Het winterdoel halen','Hier zie je welke huishoudens nog uren nodig hebben voor het winterdoel. Kies Inplannen bij een huishouden, selecteer geschikte vrije taken en controleer het voorstel.'],
  ['households.exemptions','Vrijstellingen zorgvuldig vastleggen','Hier staan huishoudens met een afwijkende afspraak. Open het dossier om de geldende afspraak te bekijken of een nieuwe aanvraag te beoordelen.'],
  ['households.requests','Aanvragen samen beoordelen','Dit zijn verzoeken om een afwijkende afspraak of wijziging. Lees de toelichting en leg je beoordeling vast; het dossier bewaart de voortgang van het verzoek.'],
  ['household.overview','Het huishoudelijke dossier','Hier staan het urendoel, de voortgang en de acties voor dit huishouden. Gebruik de tabbladen om personen, afspraken en eerdere wijzigingen te bekijken.'],
  ['household.people','Wie hoort bij dit huishouden?','Hier beheer je de personen die namens dit huishouden taken kunnen uitvoeren. Nodig een extra persoon uit en controleer de koppeling voordat je een wijziging bevestigt.'],
  ['household.agreements','Afspraken voor dit huishouden','Hier staan de vaste rollen en eventuele afwijkende afspraken. Vraag een passende afspraak aan of leg als verantwoordelijke een vaste rol vast.'],
  ['household.history','De historie van het huishouden','Hier lees je eerdere registraties en wijzigingen terug. Gebruik dit overzicht om te begrijpen hoe de huidige afspraken en urenstand zijn ontstaan.'],
  ['messages.conversations','Een gesprek voeren','Kies links het gesprek dat je wilt openen. Lees de eerdere berichten, schrijf je reactie onderaan en druk op de verzendknop om die in het gesprek te plaatsen.'],
  ['messages.notifications','Jouw meldingen afhandelen','Hier staan meldingen die voor jouw huishouden, team of rol bedoeld zijn. Gebruik Openen om de bijbehorende actie te bekijken en markeer gelezen meldingen als afgehandeld.'],
  ['policy.read','Een afspraak lezen en bevestigen','Lees de inhoud van deze beleidsversie. Als je vragen hebt, stel die eerst. Bevestig daarna met de bevestigingsknop dat je deze versie hebt gelezen.'],
  ['policy.acceptance','Wie heeft de afspraken gelezen?','Hier volg je welke huishoudens of personen de geldende beleidsversie hebben bevestigd. Gebruik dit overzicht om ontbrekende bevestigingen gericht op te volgen.'],
  ['policy.history','Eerdere beleidsversies terugzien','Hier staan de eerder gepubliceerde afspraken. Open een versie om de inhoud en ingangsdatum terug te lezen.'],
  ['finance.settlement','De seizoensafrekening controleren','Dit overzicht vergelijkt de huishoudelijke inzet met de financiële afspraak voor het seizoen. Controleer de regels en open een onbetaalde afspraak als een correctie nodig is.'],
  ['finance.agreements','Financiële afspraken teruglezen','Hier staan de afspraken die gelden voor de bijdrage en afrekening. Bekijk de bedragen en voorwaarden voordat je een regeling toepast of bespreekt.'],

  ['dialog.task-book','Een verenigingstaak boeken','Lees de tijd, locatie en instructies. Kies een geschikte uitvoerder uit jouw huishouden en bevestig de inschrijving. Als er geen vrije plek is, kun je de wachtlijst gebruiken.'],
  ['dialog.task-edit','Een verenigingstaak maken of aanpassen','Vul de datum, tijden, bezetting en voorwaarden in en schrijf een praktische instructie. Bewaar de taak als concept of publiceer wanneer de gegevens en afspraken kloppen.'],
  ['dialog.team-book','Een uitvoerder voor de teamtaak kiezen','Kies eerst voor welk lid de taak meetelt en daarna wie uit het huishouden deze uitvoert. Controleer de geschiktheid, tijd en instructies en bevestig de afspraak.'],
  ['dialog.cluster','Een cluster aan een team geven','Selecteer de vrije plaatsen die bij elkaar horen, kies een team en stel de manier van verdelen en deadline in. Controleer het totaal en druk op Cluster toewijzen.'],
  ['dialog.assign','Een taak aan een lid toewijzen','Kies het lid namens wie het huishouden deze plaats oppakt. Controleer het voorstel en bevestig de toewijzing. Het huishouden kiest daarna zelf de werkelijke uitvoerder.'],
  ['dialog.team-goal','Het teamdoel instellen','Vul in hoeveel taken ieder lid dit seizoen hoort te doen en sla het doel op. Dit aantal staat los van de verenigingsuren die voor het huishouden gelden.'],
  ['dialog.member-goal','Een passend doel voor één lid','Vul het aantal taken en de reden voor de afwijking in. Na opslaan geldt dit doel alleen voor dit lid, binnen dit team en dit seizoen.'],
  ['dialog.team-task','Een eigen teamtaak toevoegen','Kies de soort taak, datum, bezetting en instructies. Geef aan of de taak meetelt voor het teamdoel en publiceer. Verenigingsuren tellen pas mee na de vereiste goedkeuring.'],
  ['dialog.hours-approval','Verenigingsuren voor een teamtaak','Controleer de taak en het gevraagde aantal minuten voordat je goedkeurt. Fluiten en grensrechter vragen eerst beoordeling door wedstrijdzaken.'],
  ['dialog.issue','Doorgeven dat een taak niet lukt','Beschrijf kort wat er nodig is en verstuur de melding. Bij een overname blijft de bestaande afspraak staan totdat een geschikte vervanger die heeft bevestigd.'],
  ['dialog.follow-up','Wanneer wie aan zet is','Kies tot wanneer leden zelf mogen inschrijven en wanneer de teamouder klaar moet zijn met verdelen. Houd beide datums vóór de taakdatum en sla de afspraken op.'],
  ['dialog.feedback','Twee korte vragen na de taak','Geef aan of je deze taak nog eens wilt doen en of de instructies duidelijk waren. Je kunt een praktische tip toevoegen en daarna je terugblik bewaren.'],
  ['dialog.instructions','De volgende vrijwilliger op weg helpen','Pas de instructie aan met een korte, praktische uitleg. Kies of je die ook voor vergelijkbare komende taken wilt gebruiken en sla de tekst op.'],
  ['dialog.confirm','Vastleggen wat is uitgevoerd','Controleer de persoon, taak en uren. Kies Uitvoering bevestigen als de taak is gedaan of Niet verschenen als dat niet zo is. Alleen bevestigde uitvoering telt mee.'],
  ['dialog.no-show','Een gemiste taak registreren','Vul een korte toelichting in en bevestig wat er is gebeurd. Een taak die niet is uitgevoerd levert geen bevestigde uren op.'],
  ['dialog.swap','Een overname aanbieden','Voeg zo nodig een toelichting toe en bevestig dat je een vervanger zoekt. Jij blijft ingeschreven tot een geschikte vervanger de taak definitief overneemt.'],
  ['dialog.cancel','Een afmelding doorgeven','Controleer de afmeldtermijn en geef je toelichting. Bevestig de afmelding; een late afmelding wordt ter beoordeling doorgegeven.'],
  ['dialog.sick','Een verhindering doorgeven','Geef kort door dat je niet kunt en wat er geregeld moet worden. Medische details zijn niet nodig. Bevestig de melding zodat de coördinator kan helpen.'],
  ['dialog.hours-check','Een urenafspraak laten controleren','Beschrijf welke registratie volgens jou niet klopt en verstuur de melding. De verantwoordelijke kan de afspraak beoordelen en een correctie vastleggen.'],
  ['dialog.swap-confirm','Een taak definitief overnemen of ruilen','Kies wie de taak gaat doen. Voor een ruil kies je ook een eigen taak; bij alleen overnemen laat je dat veld leeg. Bevestig pas als de betrokken uitvoerders akkoord zijn.'],
  ['dialog.planning-change','Een roosterwijziging controleren','Vergelijk de oude en nieuwe tijden en kijk wie door de wijziging geraakt wordt. Bevestig als de afspraak klopt of kies Annuleren om de oorspronkelijke planning te behouden.'],
  ['dialog.roster-template','Een rooster als concept klaarzetten','Kies het sjabloon, de startdatum en het aantal weken. Maak het conceptrooster en controleer daarna de taken in het planbord voordat je ze publiceert.'],
  ['dialog.help-request','Hulp bij een passende taak','Vertel kort welke hulp je nodig hebt om een taak te vinden of uit te voeren. Verstuur je vraag zodat de commissie met je kan meedenken.'],
  ['dialog.household-new','Een huishouddossier toevoegen','Vul de basisgegevens van het huishouden en de contactpersoon in. Controleer de gegevens en sla op om het dossier in de demo te openen.'],
  ['dialog.winter-plan','Passende taken voor het winterdoel','Bekijk welke vrije taken geschikt zijn voor dit huishouden en selecteer de gewenste plaatsen. Controleer de gekozen uitvoerders en bevestig het voorstel.'],
  ['dialog.household-person','Een persoon aan het huishouden koppelen','Vul de gegevens van de persoon in en controleer de huishoudkoppeling. Bevestig de uitnodiging zodat deze persoon namens het huishouden kan meedoen.'],
  ['dialog.household-request','Een afwijkende afspraak aanvragen','Beschrijf welke afspraak nodig is en voeg een korte reden toe. Verstuur de aanvraag; de verantwoordelijken beoordelen die voordat de afspraak geldt.'],
  ['dialog.appointment','Een vaste vrijwilligersrol vastleggen','Kies de persoon en de vaste rol en leg de looptijd vast. Na opslaan is de aanstelling terug te zien bij de afspraken van het huishouden.'],
  ['dialog.household-change','Een huishoudwijziging laten beoordelen','Geef aan wat er in het huishouden verandert en waarom. Verstuur de wijziging ter beoordeling voordat de nieuwe afspraak wordt toegepast.'],
  ['dialog.vacancy','Belangstelling voor deze functie','Lees wat de functie vraagt en wat erbij hoort. Voeg een korte motivatie toe en geef je belangstelling door; de commissie kan die daarna met je bespreken.'],
  ['dialog.committee-member','Iemand aan een commissie toevoegen','Kies de persoon en de rol binnen de commissie. Sla op om die persoon aan de samenstelling toe te voegen.'],
  ['dialog.knowledge-new','Praktische kennis delen','Geef het document of de instructie een duidelijke titel en vul de inhoud in. Sla de kennis op zodat andere commissieleden die kunnen terugvinden.'],
  ['dialog.knowledge-read','Een document of instructie lezen','Lees hier de kennis die voor deze commissie is bewaard. Gebruik de praktische afspraken bij je taak en sluit het venster wanneer je klaar bent.'],
  ['dialog.card-new','Een nieuwe actie op het bord','Vul de actie, verantwoordelijke en deadline in en kies de juiste kolom. Sla de kaart op zodat iedereen kan zien wat er moet gebeuren.'],
  ['dialog.column','Een werkstap aan het bord toevoegen','Geef de kolom een korte naam die de stap in jullie werk beschrijft. Na opslaan kun je kaarten naar deze kolom verplaatsen.'],
  ['dialog.card','Afspraken bij een actie bijhouden','Bekijk de verantwoordelijke en deadline, werk de checklist bij en plaats zo nodig een reactie. Gebruik de kolom om aan te geven hoe ver de actie is.'],
  ['dialog.match-change','Gevolgen van een wedstrijdwijziging','Bekijk wat er aan de wedstrijd verandert en welke taken of personen worden geraakt. Leg je beoordeling vast zodat de planning gericht kan worden aangepast.'],
  ['dialog.calendar-item','Een afspraak in de jaaragenda','Hier lees je de datum, locatie en verdere details van deze afspraak. Gebruik deze informatie om de afspraak in je eigen planning mee te nemen.'],
  ['dialog.calendar-new','Een clubactiviteit toevoegen','Vul de titel, datum, tijd en locatie in. Geef een korte omschrijving en sla de activiteit op zodat die in de jaaragenda verschijnt.'],
  ['dialog.template-new','Een basis voor herhaalde berichten','Geef het template een herkenbare naam, onderwerp en berichttekst. Sla het op en controleer daarna het voorbeeld voordat je het gebruikt.'],
  ['dialog.role-new','Een vaste vrijwilligersrol instellen','Vul de naam en afspraken van de rol in. Geef aan of de rol voldoende inzet vormt en sla op om die bij een aanstelling te kunnen kiezen.'],
  ['dialog.reset','De voorbeeldgegevens opnieuw klaarzetten','Bevestig als je de huidige demo-afspraken wilt vervangen door de oorspronkelijke voorbeelden. Uitlegbanners die je al hebt gesloten blijven voor jouw gebruiker onthouden.'],
  ['dialog.season','Het volgende seizoen voorbereiden','Vul het seizoen, de doelen en de belangrijke datums in. Controleer de afspraken en bevestig de voorbereiding wanneer alles klopt.'],
  ['dialog.policy-new','Een nieuwe versie van een afspraak','Vul de nieuwe inhoud en ingangsdatum in. Controleer de tekst en publiceer de versie zodat leden deze kunnen lezen en bevestigen.'],
  ['dialog.policy-question','Een vraag over de afspraken stellen','Omschrijf welke afspraak of passage je wilt bespreken en verstuur je vraag. De verantwoordelijke kan daarna een toelichting geven.'],
  ['dialog.appreciation','Een moment van aandacht vastleggen','Kies voor wie het moment is, omschrijf de aanleiding en leg vast wie het oppakt. Sla op zodat de aandacht een concrete vervolgactie krijgt.'],
  ['dialog.qualification','Een kwalificatie vastleggen','Kies de persoon en de behaalde kwalificatie en vul de geldigheidsdatum in. Sla op zodat bij het boeken van taken de bevoegdheid gecontroleerd kan worden.'],
  ['dialog.finance-correction','Een financiële afspraak corrigeren','Controleer de bestaande onbetaalde afspraak en vul het juiste bedrag en de reden in. Bevestig de correctie zodat deze herleidbaar blijft.'],
  ['dialog.budget','Een besteding in de pot opnemen','Vul het doel, het bedrag en de toelichting van de budgetpost in. Sla op om de geplande besteding in het overzicht op te nemen.'],
  ['dialog.family-detail','De afspraak van je gezin bekijken','Controleer de tijd, locatie en wie de taak uitvoert. Gebruik de beschikbare actie om een uitvoerder te kiezen, een overname te vragen of na afloop terug te blikken.'],
  ['dialog.search','Snel naar een werkruimte of taak','Typ een naam of onderwerp, zoals planbord of bar. Kies een resultaat om direct de bijbehorende werkruimte te openen.'],
  ['dialog.phone','Cluvo in de mobiele weergave','Hier kun je dezelfde werkruimte op telefoonformaat proberen. Open het menu om te navigeren en gebruik de knoppen zoals je dat op je telefoon zou doen.'],
  ['dialog.discover','Het prototype uitproberen','Wissel bovenin van voorbeeldpersoon en rol om verschillende werkruimtes te bekijken. Probeer een taak, teamverdeling of actie; jouw demogegevens blijven op dit apparaat bewaard.'],
]);

export const PANEL_HELP: Record<string,string> = {
  'Dit vraagt je aandacht':'panel.next-actions','Komende wedstrijden':'panel.matches',
  'Binnenkort op de club':'panel.upcoming','Jouw huishouden':'panel.household',
  'Past bij jouw talenten':'panel.dashboard-advice','Aandacht voor de komende dagen':'panel.dashboard-advice',
  'Samen aan de slag':'panel.work-together','Jouw belangstelling':'panel.my-interest',
  'Samenstelling':'panel.committee-members','Zo doen we het samen':'panel.instructions','Documentenbibliotheek':'panel.documents',
  'Jouw meldingsvoorkeuren':'panel.notification-preferences','Een bericht met een reden':'panel.send-rules',
  'Vind mensen op hun talent':'panel.segments','Bewaarde segmenten':'panel.saved-segments','Lokale verzenddemonstraties':'panel.send-log',
  'Rollen die voldoende inzet vormen':'panel.volunteer-roles','Actieve aanstellingen':'panel.appointments',
  'Wedstrijdsynchronisatie':'panel.match-sync','Gecontroleerde ledenimport':'panel.import','E-mail & eenmalige code':'panel.sign-in',
  'Cluvo op je beginscherm':'panel.install','Demo opnieuw beginnen':'panel.demo-reset','Een nieuw seizoen voorbereiden':'panel.new-season',
  'Vereniging':'panel.club-settings','Uren & termijnen':'panel.hours-settings',
  'Bewaarde seizoensstanden':'panel.season-history','Wijzigingshistorie':'panel.audit',
  'Verenigingstaken verdelen':'panel.clusters','Wie pakt welke plek op?':'panel.team-planning','Teamtaken per lid':'panel.team-progress',
  'Verenigingsinzet van de teamhuishoudens':'panel.team-households','Kies wie de toegewezen taak uitvoert':'panel.choose-executor',
  'Taken via mijn teams':'panel.my-team-tasks','Teamtaken die aandacht vragen':'panel.team-actions','Samen rondom mijn teams':'panel.my-teams',
  'Verdeling van verenigingstaken':'panel.distribution-settings','Samen eerlijk verdelen':'panel.smart-distribution',
  'Op tijd samen oplossen':'panel.follow-up','Overdracht van de teamouder':'panel.handover',
  'Leren van taakervaringen':'panel.feedback-inbox','Een korte terugblik op jouw inzet':'panel.personal-feedback',
  'Verenigingsuren van ons huishouden':'panel.family-hours','Jouw bevestigingen':'panel.policy-confirmations',
  'Een eerste verenigingstaak met een maatje':'panel.training-buddy','Reservepool':'panel.reserve',
  'Kwalificaties en herbevestiging':'panel.qualifications','Waar we samen in investeren':'panel.budget',
  'Bezetting per commissie':'panel.committee-capacity','Winterdoel per huishouden':'panel.winter-target',
  'Voldoende passend aanbod?':'panel.supply','Aandacht voor onze vrijwilligers':'panel.volunteer-care',
};

export const DIALOG_HELP: Record<string,string> = {
  'Nieuwe verenigingstaak':'dialog.task-edit','Verenigingstaak aanpassen':'dialog.task-edit',
  'Cluster aan een team toewijzen':'dialog.cluster','Plaats aan een lid toewijzen':'dialog.assign',
  'Seizoensdoel voor het team':'dialog.team-goal','Teamtaak op de teamtakenmarkt':'dialog.team-task','Praktische teamtaak':'dialog.team-task',
  'Verenigingsuren goedkeuren':'dialog.hours-approval','Verhindering of overname melden':'dialog.issue','Opvolgafspraken':'dialog.follow-up',
  'Hoe ging deze taak?':'dialog.feedback','Een duidelijkere taakinstructie':'dialog.instructions',
  'Uitvoering controleren':'dialog.confirm','Uitvoering bevestigen':'dialog.confirm','Niet verschenen':'dialog.no-show',
  'Overname aanbieden':'dialog.swap','Afmelden':'dialog.cancel','Ziekmelding':'dialog.sick','Urencontrole':'dialog.hours-check',
  'Overnemen of wederzijds ruilen':'dialog.swap-confirm','Planningwijziging controleren':'dialog.planning-change',
  'Roostersjabloon toepassen':'dialog.roster-template','We denken met je mee':'dialog.help-request',
  'Nieuw huishouddossier':'dialog.household-new','Wintertekort passend inplannen':'dialog.winter-plan',
  'Extra persoon uitnodigen':'dialog.household-person','Een passende afspraak aanvragen':'dialog.household-request',
  'Vaste vrijwilligersrol toekennen':'dialog.appointment','Huishoudwijziging ter beoordeling':'dialog.household-change',
  'Commissielid toevoegen':'dialog.committee-member','Kennis toevoegen':'dialog.knowledge-new','Nieuwe kanbankaart':'dialog.card-new',
  'Kolom toevoegen':'dialog.column','Wedstrijdwijziging beoordelen':'dialog.match-change','Activiteit in de jaaragenda':'dialog.calendar-new',
  'Nieuw communicatietemplate':'dialog.template-new','Vrijwilligersrol toevoegen':'dialog.role-new',
  'Voorbeeldgegevens herstellen?':'dialog.reset','Seizoensvoorbereiding':'dialog.season',
  'Nieuwe beleidsversie publiceren':'dialog.policy-new','Vraag over het beleid':'dialog.policy-question','Een moment van aandacht':'dialog.appreciation',
  'Kwalificatie vastleggen':'dialog.qualification','Onbetaalde afspraak corrigeren':'dialog.finance-correction','Budgetpost toevoegen':'dialog.budget',
  'Zoeken in Cluvo':'dialog.search','Cluvo op je telefoon':'dialog.phone','Ontdek Cluvo':'dialog.discover',
};

export function panelHelpId(title?: string) {
  if (title?.startsWith('Dit speelt bij ')) return 'panel.committee-work';
  return title ? PANEL_HELP[title] : undefined;
}

export function dialogHelpId(title: string) {
  if (title.startsWith('Doel voor ')) return 'dialog.member-goal';
  return DIALOG_HELP[title];
}

export const VIEW_HELP: Record<string,Record<string,string>> = {
  households:{Wintercontrole:'households.winter',Vrijstellingen:'households.exemptions',Aanvragen:'households.requests'},
  household:{Overzicht:'household.overview',Personen:'household.people',Afspraken:'household.agreements',Historie:'household.history'},
  messages:{Gesprekken:'messages.conversations',Meldingen:'messages.notifications'},
  policy:{Acceptatieoverzicht:'policy.acceptance',Versiehistorie:'policy.history'},
  finance:{Seizoensafrekening:'finance.settlement','Financiële afspraken':'finance.agreements'},
};
