'use server';
import {revalidatePath} from 'next/cache';
import {z} from 'zod';
import {clubAdminSchemas,platformSchemas,type AdminCommand,type AdminResult} from './contracts';
import {requireClubAdmin,requirePlatform} from './server';
import {adminRemember,adminForget,adminPending} from './pending';
import {adminAccessSignature} from './access-signature';
import {createSupabaseServerClient} from '@/lib/supabase/server';
const scopePlatform='00000000-0000-4000-8000-000000000001';
export async function adminAccessStatusAction(input:{surface:'club'|'platform';club?:string}):Promise<{signature?:string}>{
 const parsed=z.object({surface:z.enum(['club','platform']),club:z.string().min(1).max(80).optional()}).strict().safeParse(input);if(!parsed.success||parsed.data.surface==='club'&&!parsed.data.club)return {};
 const client=await createSupabaseServerClient();const {data,error}=await client.schema('api').rpc(parsed.data.surface==='platform'?'platform_access':'club_admin_access',parsed.data.surface==='platform'?{}:{p_slug:parsed.data.club});
 if(error)throw new Error('ADMIN_ACCESS_UNAVAILABLE');if(data?.authorized!==true)return {};return {signature:adminAccessSignature(parsed.data.surface,data)};
}
const inputSchema=z.object({surface:z.enum(['club','platform']),club:z.string().min(1).max(80).optional(),action:z.string().min(1).max(60),resourceId:z.string().uuid(),version:z.number().int().min(0).max(Number.MAX_SAFE_INTEGER),key:z.string().uuid(),payload:z.record(z.unknown())}).strict();
const messages:Record<string,string>={DELIVERY_RETRY_NOT_PROVEN_SAFE:'Opnieuw verzenden is niet aantoonbaar veilig. Controleer de oorspronkelijke provideruitkomst; een onbekende of geaccepteerde verzending wordt niet herhaald.',LAST_ACCESS_MANAGER:'Benoem eerst een andere bevoegde toegangsbeheerder voordat je het laatste verenigingsmandaat intrekt.',MODULE_UNAVAILABLE:'De vereniging heeft deze module gepauzeerd voor nieuwe werkzaamheden. Bestaande afspraken en historie blijven beschikbaar.',QUALIFICATION_REVIEW_REQUIRED:'Controleer het werkelijk behaalde resultaat, de persoon en de geldigheidsdatums.',FORBIDDEN:'Je hebt geen actuele bevoegdheid voor deze handeling.',STALE_VERSION:'Deze gegevens zijn gewijzigd. Vernieuw de pagina en controleer je keuze.',IDEMPOTENCY_CONFLICT:'Deze opdracht-ID hoort bij een eerdere keuze. Controleer eerst de opgeslagen uitkomst.',SELF_GRANT_REFUSED:'Je kunt jezelf geen extra rechten toekennen.',CANNOT_DELEGATE_PERMISSION:'Deze rol gaat buiten jouw eigen bevoegdheid of looptijd.',IMPACT_CHANGED:'De gevolgen zijn gewijzigd. Bekijk een nieuwe impactcontrole.',ONBOARDING_INCOMPLETE:'Richt eerst de beheerder en een actief seizoen in.',TEAM_PARENT_REQUIRES_HANDOVER:'Teamouderrechten volgen de benoemde en geaccepteerde overdracht.',SEASON_AGREEMENTS_FROZEN:'Bestaande seizoensafspraken zijn vastgelegd. Gebruik de besluit- of correctieroute.',COURSE_AGREEMENTS_FROZEN:'Er zijn inschrijvingen. Maak een nieuw cursusmoment en volg de bestaande afspraken op.'};
function parse(input:AdminCommand){const parsed=inputSchema.safeParse(input);if(!parsed.success)return null;const schema=(input.surface==='platform'?platformSchemas:clubAdminSchemas)[input.action];const payload=schema?.safeParse(input.payload);return payload?.success?{...parsed.data,payload:payload.data}:null;}
async function context(input:AdminCommand){if(input.surface==='platform'){const ctx=await requirePlatform();return {...ctx,scope:{tenant:scopePlatform,person:ctx.actor}};}if(!input.club)throw new Error('INVALID_COMMAND');const ctx=await requireClubAdmin(input.club);return {...ctx,scope:{tenant:ctx.access.tenant_id,person:ctx.actor}};}
function unknown(key:string):AdminResult{return {status:'unknown',key,message:'De uitkomst is nog onbekend. Controleer dezelfde opdracht; maak geen nieuwe wijziging.'};}
function refresh(input:AdminCommand){revalidatePath('/platform','layout');if(input.club){revalidatePath(`/c/${input.club}`,'layout');revalidatePath(`/app/c/${input.club}`,'layout');}revalidatePath('/workspaces');}
export async function adminPrepareAction(input:AdminCommand):Promise<{ok:boolean;message?:string}>{const parsed=parse(input);if(!parsed)return {ok:false,message:'Controleer de ingevulde velden.'};const ctx=await context(parsed);if((await adminPending(ctx.scope)).some(r=>r.key!==parsed.key))return {ok:false,message:'Controleer eerst de nog onbekende uitkomst van je eerdere opdracht.'};const {data,error}=await ctx.client.schema('api').rpc('admin_prepare_command',{p_surface:parsed.surface,p_tenant:parsed.surface==='platform'?null:ctx.scope.tenant,p_action:parsed.action,p_resource:parsed.resourceId,p_expected_version:parsed.version,p_payload:parsed.payload,p_key:parsed.key});if(error){if(!/^[0-9A-Z]{5}$/.test(error.code??''))throw new Error('UNKNOWN_PREPARATION');return {ok:false,message:messages[error.message]??'De opdracht kan nog niet worden voorbereid. Controleer de eerdere uitkomst en je bevoegdheid.'};}if(data?.ok!==true)throw new Error('UNKNOWN_PREPARATION');await adminRemember(ctx.scope,parsed.key,parsed.action);return {ok:true};}
export async function adminCommandAction(input:AdminCommand):Promise<AdminResult>{
 const parsed=parse(input);if(!parsed)return {status:'rejected',key:input.key,message:'Controleer de ingevulde velden.'};
 const ctx=await context(parsed);if(!(await adminPending(ctx.scope)).some(r=>r.key===parsed.key&&r.command===parsed.action))return adminStatusAction({surface:parsed.surface,club:parsed.club,key:parsed.key});
 try{
  const {data,error}=await ctx.client.schema('api').rpc(parsed.surface==='platform'?'platform_command':'club_admin_command',parsed.surface==='platform'?{p_action:parsed.action,p_resource_id:parsed.resourceId,p_expected_version:parsed.version,p_payload:parsed.payload,p_idempotency_key:parsed.key}:{p_tenant:ctx.scope.tenant,p_action:parsed.action,p_resource:parsed.resourceId,p_expected_version:parsed.version,p_payload:parsed.payload,p_idempotency_key:parsed.key});
  if(error){if(!/^[0-9A-Z]{5}$/.test(error.code??''))return unknown(parsed.key);const stopped=await ctx.client.schema('api').rpc('admin_cancel_command',{p_surface:parsed.surface,p_tenant:parsed.surface==='platform'?null:ctx.scope.tenant,p_key:parsed.key});if(stopped.error||stopped.data?.state!=='cancelled')return unknown(parsed.key);await adminForget(ctx.scope,parsed.key);return {status:'rejected',key:parsed.key,message:messages[error.message]??'Deze keuze is afgewezen. Controleer je gegevens en bevoegdheid.'};}
  if(data?.ok!==true)return unknown(parsed.key);await adminForget(ctx.scope,parsed.key);refresh(parsed);return {status:'confirmed',key:parsed.key,message:'De wijziging is opgeslagen.'};
 }catch{return unknown(parsed.key);}
}
export async function adminCancelAction(input:{surface:'club'|'platform';club?:string;key:string}):Promise<AdminResult>{if(!z.string().uuid().safeParse(input.key).success)return unknown(input.key);const ctx=await context({...input,action:'cancel',resourceId:scopePlatform,version:0,payload:{}});const {data,error}=await ctx.client.schema('api').rpc('admin_cancel_command',{p_surface:input.surface,p_tenant:input.surface==='platform'?null:ctx.scope.tenant,p_key:input.key});if(error||!['cancelled','confirmed'].includes(data?.state))return unknown(input.key);await adminForget(ctx.scope,input.key);refresh({...input,action:'cancel',resourceId:scopePlatform,version:0,payload:{}});return {status:data.state==='confirmed'?'confirmed':'rejected',key:input.key,message:data.state==='confirmed'?'De oorspronkelijke wijziging was al bevestigd en blijft behouden.':'De voorbereide opdracht is ingetrokken. Een later verzoek met deze ID wordt afgewezen.'};}
export async function adminStatusAction(input:{surface:'club'|'platform';club?:string;key:string}):Promise<AdminResult>{
 if(!z.string().uuid().safeParse(input.key).success)return unknown(input.key);
 const ctx=await context({...input,action:'status',resourceId:scopePlatform,version:0,payload:{}});
 try{const {data,error}=await ctx.client.schema('api').rpc(input.surface==='platform'?'platform_command_status':'club_admin_command_status',input.surface==='platform'?{p_idempotency_key:input.key}:{p_tenant:ctx.scope.tenant,p_idempotency_key:input.key});
 if(error||data?.state!=='confirmed')return unknown(input.key);await adminForget(ctx.scope,input.key);refresh({...input,action:'status',resourceId:scopePlatform,version:0,payload:{}});return {status:'confirmed',key:input.key,message:'De eerdere wijziging is bevestigd en opgeslagen.'};}catch{return unknown(input.key);}
}
export async function platformImpactAction(input:{tenant:string;status:string}){const {client}=await requirePlatform();if(!z.string().uuid().safeParse(input.tenant).success||!['preparing','active','suspended','archived'].includes(input.status))return null;const {data,error}=await client.schema('api').rpc('platform_tenant_impact',{p_tenant:input.tenant,p_status:input.status});return error?null:data as Record<string,unknown>;}
export async function platformAccountChoiceAction(input:{email:string;purpose:'staff'|'initial_administrator';tenant?:string}):Promise<{choice?:{value:string;label:string};message:string}>{
 const parsed=z.object({email:z.string().trim().email().max(254),purpose:z.enum(['staff','initial_administrator']),tenant:z.string().uuid().optional()}).strict().safeParse(input);
 if(!parsed.success)return {message:'Vul het persoonlijke e-mailadres volledig in.'};
 const {client}=await requirePlatform();const {data,error}=await client.schema('api').rpc('platform_account_choice',{p_email:parsed.data.email,p_purpose:parsed.data.purpose,p_tenant:parsed.data.tenant??null});
 if(error)return {message:'Dit account kan binnen deze benoemingsroute niet worden geselecteerd. Controleer je actuele mandaat en de onboardingstatus.'};
 const choice=z.object({found:z.literal(true),auth_user_id:z.string().uuid(),label:z.string().min(1).max(254)}).safeParse(data);
 return choice.success?{choice:{value:choice.data.auth_user_id,label:choice.data.label},message:'Geverifieerd account geselecteerd. Controleer de afzonderlijke rechten en einddatum voordat je benoemt.'}:{message:'Geen beschikbaar geverifieerd account gevonden. Laat de persoon eerst de bestaande persoonlijke accountverificatie afronden.'};
}

export async function platformSupportScopesAction(tenant:string):Promise<Array<{value:string;label:string}>>{
 if(!z.string().uuid().safeParse(tenant).success)return [];
 const {client}=await requirePlatform();const {data,error}=await client.schema('api').rpc('platform_read',{p_section:'support_scopes',p_tenant:tenant});
 if(error)return [];
 return z.array(z.object({id:z.string().uuid(),name:z.string(),scope_kind:z.string()})).parse(data?.rows??[]).filter(r=>r.scope_kind==='committee').map(r=>({value:r.id,label:r.name}));
}
