'use client';
import {useId,useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {adminPrepareAction,adminCommandAction,adminStatusAction,adminCancelAction} from '@/lib/admin/actions';
import type {AdminCommand,AdminResult} from '@/lib/admin/contracts';
import {adminForms,type AdminField} from '@/lib/admin/forms';
import {resolveClubTimestamp} from '@/lib/pwa/time.mjs';
import {prepareClubLogo,LogoInput} from './logo-input';
import {Button,Field} from '@/components/cluvo/ui';
import {useHydrated} from './use-hydrated';

function wall(value:unknown,timezone:string){if(typeof value!=='string'||!value.includes('T'))return String(value??'');const parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).map(p=>[p.type,p.value]));return `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;}
export function AdminForm({surface,club,action,resourceId,version=0,values={},options={},timezone='Europe/Amsterdam',fields:customFields,title:customTitle,payload={},nestedFields=[]}:{surface:'club'|'platform';club?:string;action:string;resourceId?:string;version?:number;values?:Record<string,unknown>;options?:Record<string,{value:string;label:string}[]>;timezone?:string;fields?:AdminField[];title?:string;payload?:Record<string,unknown>;nestedFields?:string[]}){
 const config=adminForms[action];const fields=customFields??config?.fields??[];
 const ready=useHydrated();
 const prefix=useId();const formRef=useRef<HTMLFormElement>(null);const router=useRouter();const [pending,setPending]=useState(false);const [command,setCommand]=useState<AdminCommand|null>(null);const [result,setResult]=useState<AdminResult|null>(null);
 const frozen=result?.status==='unknown'||result?.status==='confirmed';
 return <section className="admin-form-panel" data-ready={ready}><h3>{customTitle??config?.title??'Wijziging bevestigen'}</h3>{config?.hint&&<p className="admin-form-hint">{config.hint}</p>}<form ref={formRef} onSubmit={async e=>{e.preventDefault();if(pending||frozen)return;const data=new FormData(e.currentTarget);const next:Record<string,unknown>={...payload};
 let issued:AdminCommand|null=null;setPending(true);try{for(const f of fields){const raw=data.get(f.name);next[f.name]=f.type==='logo'?(raw instanceof File&&raw.size?await prepareClubLogo(raw):String(values[f.name]??f.value??'/brand/cluvo-logo.png')):f.type==='checkbox'?data.has(f.name):f.type==='ids'?data.getAll(f.name).map(String):f.nullable&&(raw===null||raw==='')?null:f.type==='number'?Number(raw):f.type==='datetime-local'&&raw?resolveClubTimestamp(String(raw),timezone):String(raw??'');}
 if(nestedFields.length){next.value=Object.fromEntries(nestedFields.map(k=>[k,next[k]]));for(const k of nestedFields)delete next[k];}
 const input:AdminCommand={surface,club,action,resourceId:resourceId??crypto.randomUUID(),version,key:command?.key??crypto.randomUUID(),payload:next};issued=input;setCommand(input);setPending(true);setResult(null);
 const prepared=await adminPrepareAction(input);if(!prepared.ok){setResult({status:'rejected',key:input.key,message:prepared.message??'Controleer je gegevens.'});setCommand(null);return;}
 const outcome=await adminCommandAction(input);setResult(outcome);if(outcome.status==='confirmed')router.refresh();if(outcome.status==='rejected')setCommand(null);
 }catch(error){setResult({status:issued?'unknown':'rejected',key:issued?.key??'',message:issued?'De uitkomst is nog onbekend. Controleer dezelfde opdracht.':error instanceof Error&&error.message==='INVALID_LOGO'?'Kies een geldig PNG-, JPEG- of WebP-logo van maximaal 2 MB.':'Controleer de datum, tijd en ingevulde velden.'});}finally{setPending(false);}}}>
 <fieldset disabled={!ready||pending||frozen}><legend className="sr-only">{customTitle??config?.title}</legend><div className="admin-form-grid">{fields.map(f=>{const key=`${prefix}-${f.name}`;const v=values?.[f.name]??f.value;const choices=options[f.name]??f.options??[];
 if(f.type==='checkbox')return <label key={f.name} className="admin-check" htmlFor={key}><input id={key} name={f.name} type="checkbox" defaultChecked={v===true} required={f.required}/><span>{f.label}</span></label>;
 if(f.type==='ids')return <fieldset key={f.name} className="admin-check-group"><legend>{f.label}</legend>{choices.map(o=><label key={o.value} className="admin-check"><input name={f.name} type="checkbox" value={o.value} defaultChecked={Array.isArray(v)&&v.includes(o.value)}/>{o.label}</label>)}{!choices.length&&<p>Er zijn nog geen bevoegde keuzes beschikbaar.</p>}</fieldset>;
 return <Field key={f.name} label={f.label+(f.type==='datetime-local'?` (${timezone})`:'')} hint={f.hint}>{f.type==='logo'?<LogoInput id={key} name={f.name} value={v}/>:f.type==='textarea'?<textarea id={key} name={f.name} defaultValue={String(v??'')} required={f.required} maxLength={f.name==='exact_body'?32000:4000}/>:f.type==='select'?<select aria-label={f.label} id={key} name={f.name} defaultValue={String(v??'')} required={f.required}><option value="">{f.nullable?'Geen / geheel bereik':'Kies een optie'}</option>{choices.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select>:<input id={key} name={f.name} type={f.type??'text'} defaultValue={f.type==='datetime-local'?wall(v,timezone):String(v??'')} min={f.min} max={f.max} required={f.required} maxLength={254}/>}</Field>;
 })}</div><Button className="btn primary" type="submit">{pending?'Opslaan…':config?.submit??'Wijziging bevestigen'}</Button></fieldset>
 </form>{result&&<p role={result.status==='rejected'?'alert':'status'} className={`admin-result ${result.status}`}>{result.message}</p>}{result?.status==='unknown'&&command&&<PendingAdminCommand surface={surface} club={club} commandKey={command.key} label={action} input={command} onResolved={r=>{setResult(r);if(r.status==='rejected')setCommand(null);}}/>}{result?.status==='confirmed'&&!resourceId&&<Button className="btn secondary" onClick={()=>{formRef.current?.reset();setCommand(null);setResult(null);formRef.current?.querySelector<HTMLInputElement>('input:not([type="hidden"]),textarea,select')?.focus();}}>Nieuwe invoer</Button>}{result?.status==='rejected'&&<Button className="btn secondary" onClick={()=>router.refresh()}>Actuele gegevens laden</Button>}</section>;
}
export function PendingAdminCommand({surface,club,commandKey,label,input,onResolved}:{surface:'club'|'platform';club?:string;commandKey:string;label:string;input?:AdminCommand;onResolved?:(result:AdminResult)=>void}){
 const [result,setResult]=useState<AdminResult|null>(null);const [pending,setPending]=useState(false);const router=useRouter();
 async function run(operation:()=>Promise<AdminResult>){setPending(true);try{const r=await operation();setResult(r);if(r.status!=='unknown'){onResolved?.(r);router.refresh();}}catch{setResult({status:'unknown',key:commandKey,message:'De uitkomst kon nog niet worden gecontroleerd. Dezelfde opdracht en invoer blijven behouden.'});}finally{setPending(false);}}
 return <div className="admin-pending" role="status"><p>{result?.message??`Een eerdere keuze (${adminForms[label]?.title??'beheerwijziging'}) wacht op bevestiging. Controleer dezelfde opdracht voordat je opnieuw opslaat.`}</p>
 {input&&<details><summary>Eerdere invoer bekijken</summary><dl>{(adminForms[label]?.fields??[]).map(field=><div key={field.name}><dt>{field.label}</dt><dd>{typeof input.payload[field.name]==='boolean'?input.payload[field.name]?'Ja':'Nee':typeof input.payload[field.name]==='string'?String(input.payload[field.name]):input.payload[field.name]==null?'Geen':Array.isArray(input.payload[field.name])?`${(input.payload[field.name]as unknown[]).length} benoemde keuzes`:'Vastgelegde keuze'}</dd></div>)}</dl></details>}
 <div className="admin-pending-actions"><Button className="btn secondary" disabled={pending||result?.status==='confirmed'} onClick={()=>run(()=>adminStatusAction({surface,club,key:commandKey}))}>Dezelfde opdracht controleren</Button>
 {input&&<><Button className="btn secondary" disabled={pending||result?.status==='confirmed'} onClick={()=>run(async()=>{const prepared=await adminPrepareAction(input);return prepared.ok?adminCommandAction(input):{status:'rejected',key:commandKey,message:prepared.message??'Controleer je bevoegdheid en deze opgeslagen keuze.'};})}>Dezelfde invoer hervatten</Button><Button className="btn secondary" disabled={pending||result?.status==='confirmed'} onClick={()=>run(()=>adminCancelAction({surface,club,key:commandKey}))}>Voorbereide opdracht intrekken</Button></>}
 </div></div>;
}
