import Link from 'next/link';
import {notFound} from 'next/navigation';
import {PageTitle,Panel} from '@/components/cluvo/ui';
import {AccountHelpBanner} from '@/components/app/help-provider';
import {AdminTable,ReportTotals} from '@/components/admin/admin-table';
import {AdminForm,PendingAdminCommand} from '@/components/admin/admin-form';
import {NativeAdminWorkspace} from '@/components/admin/native-workspace';
import {clubRead} from '@/lib/admin/server';
import {clubSections,rows,str,num,clubSectionAllowed,type AdminRow} from '@/lib/admin/contracts';
import {loadMobileSnapshot} from '@/lib/pwa/server';
import {adminPending} from '@/lib/admin/pending';
import '@/components/mobile/mobile.css';

const columns:Record<string,string[]>={report_teams:['name','member_count','goal_total','confirmed_count','planned_count','assigned_count'],report_occupancy:['name','starts_at','total_places','free_places','reserved_places','booked_places','review_places','confirmed_places','no_show_places'],vacancies:['name','state','contact_name','expected_minutes','interested_count'],volunteer_roles:['name','active','version'],fund:['entry_kind','purpose','available_cents_delta','reserved_cents_delta','spent_cents_delta','created_at'],qualifications:['name','qualification_name','achieved_at','expires_at','revoked_at'],locations:['name','active','version'],organization:['name','slug','timezone','locale'],people:['name','status','membership_started_on'],households:['name','status','version'],access:['name','role_name','scope_kind','ends_at','revoked_at'],committees:['name','active'],teams:['name','active'],catalogue:['name','category_name','committee_name','active'],planning:['name','starts_at','ends_at','committee_name','state','credit_minutes'],execution:['name','starts_at','ends_at','committee_name','state'],requests:['name','kind','state','created_at'],policies:['name','current_revision','offered','accepted'],courses:['name','active'],communication:['channel','state','total'],templates:['name','current_revision','status'],reports:['name','effective_target_minutes','confirmed_minutes','planned_minutes','review_minutes'],finance:['name','effective_target_minutes','confirmed_minutes','review_minutes'],seasons:['name','starts_on','ends_on','status','target_minutes','winter_target_minutes'],support:['name','scope_kind','state','ends_at'],audit:['action','actor_auth_user_id','scope_kind','occurred_at']};
const options=(data:AdminRow[],key='id',label='name')=>data.filter(r=>str(r[key])).map(r=>({value:str(r[key]),label:str(r[label])||str(r[key])}));
const mainAction:Record<string,string>={vacancies:'save_vacancy',volunteer_roles:'save_volunteer_role',locations:'save_location',people:'save_person',households:'save_household',committees:'save_committee',teams:'save_team',courses:'save_course',policies:'save_policy_draft',seasons:'save_season'};
const subSections:Record<string,string[]>={reports:['reports','winter','annual','report_teams','report_occupancy','fund'],requests:['requests','vacancies','volunteer_roles'],organization:['organization','locations','settings'],people:['people','households'],planning:['planning','catalogue','calendar'],communication:['communication','templates'],support:['support','audit'],finance:['finance','fund'],courses:['courses','qualifications']};
const tabLabels:Record<string,string>={reports:'Huishoudvoortgang',winter:'Winterstand',annual:'Jaarstand',report_teams:'Teamtaken',report_occupancy:'Bezetting',requests:'Aanvragen en opvolging',vacancies:'Vacatures',volunteer_roles:'Structurele functies',organization:'Vereniging',locations:'Locaties',settings:'Afspraken',people:'Personen',households:'Huishoudens',planning:'Planning en verdeling',catalogue:'Taaksoorten',calendar:'Kalender',communication:'Inbox en kanalen',templates:'Berichttemplates',support:'Supporttoestemming',audit:'Audit',finance:'Huishoudbesluiten',fund:'Vrijwilligerspot',courses:'Cursusaanbod',qualifications:'Kwalificatieregister'};
export default async function ClubAdministrationPage({params,searchParams}:{params:Promise<{club:string;section?:string[]}>;searchParams:Promise<Record<string,string|undefined>>}){
 const {club,section:path=[]}=await params;const query=await searchParams;const section=path[0]??'cockpit';if(path.length>2||!clubSections.some(([s])=>s===section))notFound();
 const preliminary=await clubRead(club,'cockpit');if(!clubSectionAllowed(preliminary.access,section))notFound();
 const tab=query.part??(section==='people'&&!preliminary.access.permissions.some(p=>p.key==='organization.manage'&&p.kind==='tenant')?'households':section==='finance'&&!preliminary.access.permissions.some(p=>p.key.startsWith('finance.assessment.'))?'fund':subSections[section]?.[0])??section;if(subSections[section]&&!subSections[section].includes(tab))notFound();
 const readSection=tab==='settings'?'organization':tab==='calendar'?'planning':['winter','annual'].includes(tab)?'reports':tab;
 const seasons=preliminary.access.seasons;const selectedSeason=(query.season??str((seasons.find(s=>s.status==='active')??seasons[0])?.id))||undefined;
 const offset=Math.max(0,Math.min(100000,Number.parseInt(query.offset??'0',10)||0));
 const ctx=readSection==='cockpit'&&!selectedSeason?preliminary:await clubRead(club,readSection,{season:selectedSeason,resource:path[1],query:query.q,status:query.status,offset,filters:Object.fromEntries(['committee_id','team_id','category_id','queue','starts_on','ends_on'].filter(key=>query[key]).map(key=>[key,query[key]!]))});
 const data=rows(ctx.read.rows);const detail=path[1]?data[0]:undefined;if(path[1]&&!detail)notFound();
 const base=`/c/${encodeURIComponent(club)}/beheer`;const seasonQuery=selectedSeason?`season=${encodeURIComponent(selectedSeason)}`:'';
 const href=(part=section,resource?:string,extra='')=>`${base}/${part}${resource?`/${resource}`:''}?${[seasonQuery,extra].filter(Boolean).join('&')}`;
 const can=(key:string)=>ctx.access.permissions.some(p=>p.key===key&&p.kind==='tenant');
 const pending=await adminPending({tenant:ctx.access.tenant_id,person:ctx.actor});
 const workspaces=await ctx.client.schema('api').from('my_workspaces').select('tenant_slug').eq('tenant_slug',club);
 const personal=workspaces.data?.some(r=>r.tenant_slug===club)===true;
 const snapshot=personal&&['planning','execution','requests','teams','committees','communication','policies'].includes(section)?await loadMobileSnapshot(club,{season:selectedSeason,household:query.household}):null;
 const sources:Record<string,AdminRow[]>={};
 // Load each picker through its own authorized projection. Never use an
 // unrestricted person directory for a team parent or commission coordinator.
 for(const [key,target]of [['people','people'],['households','households'],['committees','committees'],['teams','teams'],['courses','courses']] as const){if(key==='courses'?can('development.manage'):key==='committees'?clubSectionAllowed(ctx.access,'committees'):key==='teams'?clubSectionAllowed(ctx.access,'teams'):can('organization.manage'))sources[key]=rows((await clubRead(club,target,{season:selectedSeason})).read.rows);}
 const roles=rows(ctx.read.extras?.roles);const categories=rows(ctx.read.extras?.categories);
 for(const key of ['people','committees','teams','households'])if(!sources[key])sources[key]=rows(ctx.read.extras?.[key]);
 const pageHref=(nextOffset:number)=>{const filters=new URLSearchParams(Object.entries(query).filter(([key,value])=>key!=='offset'&&typeof value==='string') as [string,string][]);filters.set('offset',String(nextOffset));if(selectedSeason)filters.set('season',selectedSeason);return `${base}/${section}?${filters}`;};
 const picker={person_id:options(sources.people??[]),person_ids:options(sources.people??[]),household_id:options(sources.households??[]),team_id:options(sources.teams??[]),committee_id:options(sources.committees??[]),owner_committee_id:options(sources.committees??[]),course_id:options(sources.courses??[]),contact_person_id:options(sources.people??[]),role_version_id:options(rows(ctx.read.extras?.role_versions)),role_id:options(roles),category_id:options(categories),qualification_type_id:options(rows(ctx.read.extras?.qualification_types)),source_season_id:options(seasons.filter(s=>s.status==='closed')),selected_template_keys:options(rows(ctx.read.extras?.published_templates),'template_key'),exception_decision_id:options(rows(ctx.read.extras?.decisions)),supply_assessment_id:options(rows(ctx.read.extras?.supply_assessments)),reservation_key:options(rows(ctx.read.extras?.fund_entries).filter(e=>e.reservation_key),'reservation_key','purpose'),reverses_entry_id:options(rows(ctx.read.extras?.fund_entries),'id','purpose'),owner_person_id:options(sources.people??[]),processing_record_id:options(rows(ctx.read.extras?.processing_records)),auth_user_id:(sources.people??[]).flatMap(p=>rows(p.accounts).map(a=>({value:str(a.auth_user_id),label:str(p.name)}))),scope_id:[...options(sources.committees??[]),...options(sources.teams??[]),...options(sources.households??[])]};
 const inherited=ctx.read.extras?.adopted_defaults as Record<string,{version:number;value:Record<string,unknown>}>|undefined;
 const templateDefault=inherited?.template?.value;
 const planningDefault=inherited?.planning?.value;
 const title=detail?str(detail.name):clubSections.find(([s])=>s===section)![1];
 const form=(action:string,row?:AdminRow,extra:Record<string,unknown>={})=><AdminForm key={`${action}:${str(row?.id)}:${num(row?.version)}`} surface="club" club={club} action={action} resourceId={row?str(row.id):undefined} version={num(row?.version)} values={row} options={picker} timezone={ctx.access.timezone} {...extra}/>;
 return <div className="cluvo-admin"><PageTitle eyebrow={`${ctx.access.name} · verenigingsbeheer`} title={title} description="Dezelfde afspraken, taken en bevestigde standen als in de ledenapp."/><div className="admin-context"><b>{ctx.access.name} · {str(seasons.find(s=>s.id===selectedSeason)?.name)||'Kies een seizoen'}</b><form method="get"><label htmlFor="admin-season">Seizoen</label><select id="admin-season" name="season" defaultValue={selectedSeason??''}><option value="">Kies een seizoen</option>{seasons.map(s=><option key={str(s.id)} value={str(s.id)}>{str(s.name)} · {str(s.status)}</option>)}</select>{query.part&&<input type="hidden" name="part" value={query.part}/>}<button type="submit" className="btn secondary">Kiezen</button></form></div>
 {ctx.access.support.map(s=><aside key={str(s.id)} className="admin-support" role="note"><b>Tijdelijke benoemde ondersteuning</b><p>{str(s.purpose)} · bereik {str(s.scope_kind)} · eindigt {str(s.ends_at)}. Je werkt met je eigen account en de toestemming van deze vereniging.</p></aside>)}<AccountHelpBanner topicId={`admin.club.${section}.v1`}/>{pending.map(p=><PendingAdminCommand key={p.key} surface="club" club={club} commandKey={p.key} label={p.command} input={p.input}/>)}
 {Object.entries(ctx.access.modules??{}).some(([module,enabled])=>enabled===false&&({planning:'planning',teams:'teams',courses:'courses',policies:'policies',communication:'communication'}as Record<string,string>)[section]===module)&&<aside className="admin-support" role="note">Deze module is gepauzeerd voor nieuwe werkzaamheden. Je kunt bestaande afspraken opvolgen en de historie bekijken.</aside>}
 {detail&&<Link className="text-link" href={href()}>← Terug naar het overzicht</Link>}{subSections[section]&&<nav className="admin-tabs" aria-label="Beheeronderdelen">{subSections[section].filter(t=>!(section==='people'&&t==='people'&&!can('organization.manage'))&&!(t==='fund'&&!can('finance.fund.manage'))).map(t=><Link key={t} href={href(section,undefined,`part=${t}`)} aria-current={t===tab?'page':undefined}>{tabLabels[t]}</Link>)}</nav>}
 {section==='cockpit'?<div className="secure-stat-grid">{Object.entries(ctx.read.rows).map(([key,value])=>{const card:Record<string,[string,string,string]>={free_positions:['Vrije verenigingstaakplaatsen','planning','queue=free'],reserved_positions:['Teamreserveringen','planning','queue=reserved'],no_executor:['Plaatsen zonder uitvoerder','planning','queue=no_executor'],execution:['Uitvoering ter controle','execution','queue=review'],team_deadlines:['Naderende of verstreken verdeling','teams','queue=deadlines'],questions:['Openstaande huishoudvragen','requests','queue=questions'],exception_requests:['Openstaande uitzonderingsaanvragen','requests','queue=exceptions'],hour_disputes:['Openstaande uurvragen','requests','queue=disputes'],vacancy_interests:['Vacatureinteresse opvolgen','requests','queue=vacancies'],team_credit_requests:['Teamtaakminuten beoordelen','requests','queue=team_credit'],transfers:['Openstaande overnames','requests','queue=transfers'],policy_actions:['Openstaande beleidsacties','policies','queue=policy']};const [label,target,filter]=card[key]??[key,'cockpit',''];return <article key={key}><span>{label}</span><strong>{String(value)}</strong><small>Actuele bevoegde werkvoorraad</small><Link href={href(target,undefined,filter)}>Bekijken →</Link></article>;})}</div>:<>
 {tab==='settings'?<Panel title="Nieuwe verenigingsafspraken"><p>Nieuwe regels gelden vanaf de ingestelde datum. Bestaande boekingen behouden hun afspraakversie en afmelddeadline.</p>{form('save_settings',undefined,{version:num((ctx.read.extras?.settings as AdminRow|undefined)?.revision),values:ctx.read.extras?.settings??planningDefault??{}})}</Panel>:<Panel title={detail?'Gegevens':tabLabels[tab]??title}><AdminTable data={data} columns={tab==='winter'?['name','effective_winter_minutes','confirmed_before_winter_minutes','winter_deficit_minutes','review_minutes','winter_state']:tab==='annual'?['name','effective_target_minutes','confirmed_minutes','planned_minutes','review_minutes','remaining_minutes','annual_state']:columns[readSection]??['name','status']} href={!detail&&!['communication','access','support','audit','fund','reports','report_teams','report_occupancy'].includes(readSection)?r=>href(section,str(r.id),subSections[section]?`part=${tab}`:''):undefined}/></Panel>}
 {['reports','finance','report_teams','report_occupancy'].includes(readSection)&&<>{['reports','finance'].includes(readSection)&&<ReportTotals totals={ctx.read.extras?.report_totals as AdminRow|undefined}/>}<Panel title="Berekening en periode"><p>{readSection==='report_teams'?'Teamdoelen en tellingen gebruiken dezelfde bron als de teamomgeving. Een plaats telt voor één gekozen lid. Een gesloten seizoen toont de bij sluiting vastgelegde teamstand.':readSection==='report_occupancy'?'Bezetting telt concrete plaatsen. Een toegewezen lid is nog geen geboekte uitvoerder; gereserveerde plaatsen zijn afzonderlijk van de vrije markt.':'Bevestigd komt uitsluitend uit geldige ledgerposten. Gepland en uitvoering ter controle tellen apart. Een huishouden wordt via zijn verplichting één keer opgeteld.'}</p>{ctx.read.extras?.historical_measurement_available===false?<p role="status">De teamstand is bij dit oudere seizoen niet vastgelegd. Deze historische meting is onbekend.</p>:<Link className="btn secondary" href={`${base}/export?section=${readSection}&${new URLSearchParams(Object.entries(query).filter(([key,v])=>key!=='section'&&typeof v==='string') as [string,string][])}&${seasonQuery}`}>Toegestane CSV downloaden</Link>}<p>{selectedSeason?`${str(seasons.find(s=>s.id===selectedSeason)?.starts_on)} t/m ${str(seasons.find(s=>s.id===selectedSeason)?.ends_on)}`:'Kies een seizoen voor een seizoensrapport.'}</p></Panel></>}
 {tab==='calendar'&&<Panel title="Kalenderexport"><p>Download de getoonde geautoriseerde selectie als agenda. De export bevat taak, tijd en locatie; persoonlijke uitvoerders en huishoudgegevens worden niet opgenomen.</p><Link className="btn secondary" href={`${base}/export?section=planning&format=ics&${new URLSearchParams(Object.entries(query).filter(([,v])=>typeof v==='string') as [string,string][])}&${seasonQuery}`}>Geselecteerde kalender downloaden</Link></Panel>}
 {tab==='calendar'&&<div className="admin-calendar">{data.map(r=><Link className="admin-calendar-entry" key={str(r.id)} href={href('planning',str(r.id))}><b>{str(r.name)}</b><span>{new Intl.DateTimeFormat('nl-NL',{dateStyle:'full',timeStyle:'short',timeZone:ctx.access.timezone}).format(new Date(str(r.starts_at)))}</span><span>{str(r.committee_name)} · {str(r.state)}</span></Link>)}</div>}
 {section==='organization'&&tab==='organization'&&<>{form('save_organization',undefined,{resourceId:ctx.access.tenant_id,version:ctx.access.version,values:{...data[0],contact_name:(ctx.read.extras?.contact as AdminRow|undefined)?.name,contact_email:(ctx.read.extras?.contact as AdminRow|undefined)?.email,contact_phone:(ctx.read.extras?.contact as AdminRow|undefined)?.phone,...(data[0]?.branding as AdminRow??{})}})}</>}
 {mainAction[readSection]&&(!['people','households','committees','teams','locations','seasons'].includes(readSection)||can('organization.manage'))&&(!detail||detail.can_edit!==false)&&(readSection!=='vacancies'||!detail||detail.state==='draft')&&form(mainAction[readSection],detail,readSection==='policies'&&detail?{values:{...detail,...rows(detail.revisions).find(r=>r.revision===detail.current_revision)}}:{})}
 {readSection==='planning'&&detail&&snapshot?.tasks.some(t=>t.id===detail.id)&&<Link className="btn secondary" href={href(section,str(detail.id),`task=${str(detail.id)}`)}>Taakafspraak en bezetting openen</Link>}
 {readSection==='teams'&&detail&&<Panel title="Individuele doelafspraken en historie"><AdminTable data={rows(detail.goals)} columns={['member_person_id','goal','version','reason']}/>{rows(detail.goals).filter(g=>rows(g.agreement_history).length).map(g=><details className="admin-details" key={str(g.id)}><summary>Eerdere afspraken voor dit lid</summary><AdminTable data={rows(g.agreement_history)} columns={['version','goal','reason','replaced_at']}/></details>)}<p>Doel nul is een geldige afspraak. Het aanpassen van een doel verandert geen uitgevoerde tellingen.</p></Panel>}{readSection==='teams'&&detail&&can('organization.manage')&&<><Panel title="Teamleden"><AdminTable data={rows(detail.members)} columns={['name','membership_kind','ends_at']}/>{rows(detail.members).filter(m=>m.membership_kind!=='team_parent'&&!m.ends_at).map(m=><details key={str(m.id)} className="admin-details"><summary>{str(m.name)} · teamdeelname beëindigen</summary>{form('end_team_member',m)}</details>)}</Panel>{form('add_team_member',undefined,{values:{team_id:detail.id}})}<Panel title="Overdracht"><p>De huidige teamouder houdt het recht totdat de benoemde opvolger de actuele gereedstaande versie accepteert. Gebruik hieronder de bestaande teamafspraken en overdracht.</p></Panel></>}
 {readSection==='execution'&&detail&&!snapshot&&rows(detail.bookings).filter(b=>b.can_confirm===true).map(b=><Panel key={str(b.id)} title={`Uitvoering · ${str(b.executor_name)}`}><AdminTable data={[b]} columns={['executor_name','state','credit_minutes']}/>{['booked','performed_pending'].includes(str(b.state))&&form('confirm_attendance',b,{values:{awarded_minutes:b.credit_minutes}})}{['confirmed','no_show'].includes(str(b.state))&&form('correct_attendance_award',b,{values:{awarded_minutes:b.credit_minutes}})}</Panel>)}
 {readSection==='people'&&detail&&<><Panel title="Koppelingen"><AdminTable data={rows(detail.households)} columns={['label','link_kind']}/></Panel>{form('link_household_person',undefined,{values:{person_id:detail.id}})}</>}
 {readSection==='households'&&detail&&<><Panel title="Persoonlijke uitnodigingen"><AdminTable data={rows(detail.invitations)} columns={['delivery_status','accepted_at','cancelled_at','expires_at']}/><p>De uitnodiging en acceptatie zijn afzonderlijke stappen. Alleen expliciet bevoegde ontvangers krijgen toegang.</p>{detail.can_open_dossier===true?<Link href={`/c/${encodeURIComponent(club)}/huishouden?household=${str(detail.id)}&${seasonQuery}`}>Bevoegd huishouddossier en uitnodiging openen →</Link>:<p>Uitnodigen en privéafspraken vragen een afzonderlijke huishoudbevoegdheid.</p>}</Panel>{can('organization.manage')&&form('link_household_person',undefined,{values:{household_id:detail.id}})}</>}
 {readSection==='volunteer_roles'&&detail&&<><Panel title="Vastgelegde functieversies"><AdminTable data={rows(detail.revisions)} columns={['revision','household_exempt','effective_from','effective_until']}/>{rows(detail.revisions).map(r=><p className="admin-document" key={str(r.id)}>Versie {num(r.revision)}: {str(r.conditions)}</p>)}</Panel>{detail.active===true&&form('revise_volunteer_role',detail)}</>}
 {readSection==='vacancies'&&detail&&<Panel title="Publicatie en bestaande belangstelling"><p className="admin-document">{str(detail.description)}</p><p>{str(detail.guidance)}</p><p>Verwachte inzet: {num(detail.expected_minutes)} minuten. Huishoudvrijstelling kan alleen na een afzonderlijke erkende aanstelling op deze functieversie.</p>{['draft','published'].includes(str(detail.state))&&form('set_vacancy_state',detail,{values:{...detail,state:detail.state==='draft'?'published':'closed'},options:{...picker,state:[{value:detail.state==='draft'?'published':'closed',label:detail.state==='draft'?'Publiceren in de ledenapp':'Sluiten, historie behouden'}]}})}<Link className="text-link" href={href('requests',undefined,'part=requests&queue=vacancies')}>Belangstelling en kennismaking opvolgen →</Link></Panel>}
 {readSection==='committees'&&detail&&<><Panel title="Contact en verantwoordelijkheden"><AdminTable data={[detail]} columns={['contact_name','contact_email','contact_phone']}/><AdminTable data={rows(detail.responsibilities)} columns={['role','ends_at']}/>{detail.can_manage_members===true&&form('save_committee_contact',detail)}</Panel><Panel title="Commissieleden en historie"><AdminTable data={rows(detail.members)} columns={['name','duty','starts_at','ends_at']}/>{detail.can_manage_members===true&&<>{form('add_committee_member',undefined,{values:{committee_id:detail.id}})}{rows(detail.members).filter(m=>!m.ends_at).map(m=><details className="admin-details" key={str(m.id)}><summary>Lidmaatschap van {str(m.name)} beëindigen</summary>{form('end_committee_member',m)}</details>)}</>}<p>Lidmaatschap, werkzaamheden en toegang zijn afzonderlijke afspraken. Werkafspraken en instructies hieronder gebruiken de bestaande commissiewerkruimte.</p></Panel></>}
 {readSection==='access'&&<><Panel title="Benoemde beheeruitnodigingen"><AdminTable data={rows(ctx.read.extras?.invitations)} columns={['name','scope_kind','invitation_status','expires_at','ends_at']}/>{rows(ctx.read.extras?.invitations).filter(i=>['pending','expired'].includes(str(i.invitation_status))).map(i=><details className="admin-details"key={str(i.id)}><summary>{str(i.name)} · uitnodiging intrekken</summary>{form('cancel_access_invitation',i)}</details>)}</Panel>{form('grant_access')}{form('invite_access')}{data.filter(g=>!g.revoked_at).map(g=><details className="admin-details" key={str(g.id)}><summary>{str(g.name)} · {str(g.role_name)} intrekken</summary>{form('revoke_access',g)}</details>)}</>}
 {readSection==='catalogue'&&<>{form('save_category')}{form('save_task_type',detail)}{detail&&<><Panel title="Ongewijzigde versies"><AdminTable data={rows(detail.revisions)} columns={['revision','credit_minutes','cancellation_minutes_override','published_at']}/></Panel>{form('revise_task_type',detail)}</>}</>}
 {readSection==='policies'&&detail&&<><Panel title="Documentversies"><AdminTable data={rows(detail.revisions)} columns={['revision','state','effective_at','published_at']}/>{rows(detail.revisions).map(r=><details className="admin-details" key={str(r.id)}><summary>Versie {num(r.revision)} · {str(r.state)}</summary><p className="admin-document">{str(r.exact_body)}</p></details>)}</Panel>{rows(detail.revisions).some(r=>r.state==='draft')&&form('publish_policy',detail,{options:{...picker,revision_id:rows(detail.revisions).filter(r=>r.state==='draft').map(r=>({value:str(r.id),label:`Conceptversie ${num(r.revision)}`}))}})}</>}
 {readSection==='templates'&&<>{form('save_template_draft',detail,{values:detail?{...detail,...rows(detail.revisions).find(r=>r.revision===detail.current_revision)}:templateDefault?{subject:templateDefault.subject,text_body:templateDefault.text,sender_name:templateDefault.sender_name}:undefined})}{detail&&<>
  <Panel title="Versiegeschiedenis"><AdminTable data={rows(detail.revisions)} columns={['revision','state','subject','sender_name','published_at']}/>{rows(detail.revisions).map(r=><details key={str(r.id)} className="admin-details"><summary>Versie {num(r.revision)} · {str(r.state)}</summary><p className="admin-document">{str(r.text_body)}</p></details>)}</Panel>
  {rows(detail.revisions).filter(r=>r.revision===detail.current_revision).map(r=>{const templateOptions={...picker,revision_id:[{value:str(r.id),label:`Exacte versie ${num(r.revision)}`}]};return <div key={str(r.id)}>{['draft','previewed','test_sent'].includes(str(r.state))&&form('preview_template',detail,{options:templateOptions})}{['previewed','test_sent'].includes(str(r.state))&&form('queue_template_test',detail,{options:templateOptions})}{r.state==='test_sent'&&form('approve_template',detail,{options:templateOptions})}{r.state==='approved'&&form('publish_template',detail,{options:templateOptions})}</div>;})}
  <Panel title="Voorbeelden en echte testuitkomsten"><p>Provider geaccepteerd is afzonderlijk van ontvangen in je inbox. Een onbekende uitkomst wordt eerst gecontroleerd.</p>{rows(ctx.read.extras?.tests).map(t=><details key={str(t.id)} className="admin-details"><summary>Versie {num(t.revision)} · {str(t.last_delivery_state)||str(t.status)}</summary><h3>{str(t.rendered_subject)}</h3><p className="admin-document">{str(t.rendered_text)}</p></details>)}</Panel>
 </>}</>}
 {readSection==='qualifications'&&<>{!detail&&form('register_qualification')}{detail&&!detail.revoked_at&&form('revoke_qualification',detail)}</>}
 {readSection==='courses'&&<>{form('save_qualification_type')}{detail&&<>{form('save_course_session',undefined,{values:{course_id:detail.id}})}{rows(detail.sessions).map(s=><Panel key={str(s.id)} title={`Cursusmoment ${str(s.starts_at)}`}><AdminTable data={rows(s.enrollments)} columns={['name','state','qualification_name']}/>{rows(s.enrollments).filter(e=>e.state==='enrolled').map(e=><details className="admin-details" key={str(e.id)}><summary>Beoordeeld resultaat registreren</summary>{form('certify_enrollment',e)}</details>)}</Panel>)}</>}</>}
 {section==='finance'&&detail&&<>
  {can('finance.assessment.prepare')&&form('prepare_assessment',detail)}
  {rows(detail.assessments).map(a=><Panel key={str(a.id)} title={`Financieel besluit · ${str(a.state)}`}><AdminTable data={[a.calculation as AdminRow]} columns={['missing_minutes','proposed_cents','ledger_revision']}/><p>Route: {str(a.route)} · berekeningsversie {num(a.current_revision)}. Controleer de onderbouwing en openstaande blokkades voor je beslist.</p>{a.state==='draft'&&can('finance.assessment.approve')&&form('approve_assessment',a)}{a.state==='committee_approved'&&can('finance.assessment.finalize')&&form('finalize_assessment',a)}</Panel>)}
 </>}
 {readSection==='fund'&&!detail&&can('finance.fund.manage')&&<Panel title="Vrijwilligerspot"><AdminTable data={ctx.read.extras?.fund_balance?[ctx.read.extras.fund_balance as AdminRow]:[]} columns={['available_cents','reserved_cents','spent_cents']}/><AdminTable data={rows(ctx.read.extras?.fund_entries)} columns={['entry_kind','purpose','available_cents_delta','reserved_cents_delta','spent_cents_delta','created_at']}/>{form('post_fund_entry')}</Panel>}
 {section==='requests'&&detail?.kind==='hour_dispute'&&<Panel title="Uurvraag en oorspronkelijke uitvoering"><p className="admin-document">{str((ctx.read.extras?.dispute as AdminRow|undefined)?.description)}</p><AdminTable data={ctx.read.extras?.dispute?[ctx.read.extras.dispute as AdminRow]:[]} columns={['reviewer_auth_user_id','outcome','resolved_at']}/>{['open','in_review'].includes(str(detail.state))&&<>{form('take_hour_dispute',detail)}{detail.state==='in_review'&&(ctx.read.extras?.dispute as AdminRow|undefined)?.reviewer_auth_user_id===ctx.actor&&form('resolve_hour_dispute',detail,{values:{decision_id:(ctx.read.extras?.dispute as AdminRow|undefined)?.decision_id},options:{...picker,decision_id:(ctx.read.extras?.dispute as AdminRow|undefined)?.decision_id?[{value:str((ctx.read.extras?.dispute as AdminRow).decision_id),label:'Actueel bevestigd uitvoeringsbesluit'}]:[]}})}</>}{str((ctx.read.extras?.dispute as AdminRow|undefined)?.shift_id)&&<Link className="text-link" href={href('execution',str((ctx.read.extras?.dispute as AdminRow).shift_id))}>Bevoegde uitvoering en gemotiveerde correctie openen →</Link>}<p>{str((ctx.read.extras?.dispute as AdminRow|undefined)?.resolution_reason)}</p></Panel>}
 {section==='requests'&&detail?.kind==='vacancy_interest'&&<Panel title="Belangstelling, kennismaking en vervolg"><p className="admin-document">{str((ctx.read.extras?.interest as AdminRow|undefined)?.motivation)}</p><p>{str((ctx.read.extras?.interest as AdminRow|undefined)?.guidance)}</p><p>{str((ctx.read.extras?.interest as AdminRow|undefined)?.next_step)}</p>{['interested','contacted','meeting'].includes(str(detail.state))&&form('follow_vacancy_interest',detail,{options:{...picker,state:({interested:['contacted','rejected'],contacted:['meeting','rejected'],meeting:['rejected']}as Record<string,string[]>)[str(detail.state)].map(value=>({value,label:({contacted:'Contact gelegd',meeting:'Kennismaking gepland',rejected:'Gemotiveerd afgewezen'}as Record<string,string>)[value]}))}})}{detail.state==='meeting'&&can('volunteer_role.manage')&&rows((ctx.read.extras?.interest as AdminRow|undefined)?.obligations).map(o=><details className="admin-details" key={str(o.id)}><summary>Afzonderlijke aanstelling voor {str(o.name)}</summary>{form('recognize_vacancy_appointment',detail,{payload:{obligation_id:o.id,expected_obligation_version:o.version}})}</details>)}</Panel>}
 {section==='requests'&&detail?.kind==='transfer'&&<Panel title="Overname met behoud van de inschrijving"><AdminTable data={ctx.read.extras?.transfer?[ctx.read.extras.transfer as AdminRow]:[]} columns={['origin_state','expires_at','reason']}/><p>De oorspronkelijke inschrijving blijft actief totdat de geschikte vervanger definitief accepteert. De bestaande overnameroute controleert uitvoerder, overlap en huishoudrechten.</p><Link className="text-link" href={href('planning',str((ctx.read.extras?.transfer as AdminRow|undefined)?.shift_id))}>Taak en actuele overnamehistorie openen →</Link></Panel>}
 {section==='requests'&&detail&&<Panel title="Opvolgingshistorie"><AdminTable data={rows(ctx.read.extras?.request_history)} columns={['action','actor_auth_user_id','occurred_at','reason','resulting_version']}/></Panel>}
 {section==='requests'&&detail?.kind==='exception'&&<Panel title="Actuele aanvraag en onafhankelijke beoordelingen"><AdminTable data={ctx.read.extras?.proposal?[ctx.read.extras.proposal as AdminRow]:[]} columns={['proposed_target_minutes','proposed_winter_minutes','valid_from','valid_until']}/><p className="admin-document">{str((ctx.read.extras?.proposal as AdminRow|undefined)?.practical_reason)}</p><AdminTable data={rows(ctx.read.extras?.reviews)} columns={['outcome','has_conflict','reason','reviewed_at']}/>{can('exception.review')&&form('review_exception',detail,{resourceId:str(detail.current_revision_id)})}{can('exception.finalize')&&form('finalize_exception',detail,{resourceId:str(detail.current_revision_id)})}</Panel>}
 {section==='seasons'&&detail&&<>{detail.status==='active'&&can('season.close')&&form('close_season',detail)}{detail.status==='preparing'&&can('season.rollover')&&form('rollover_season',detail)}</>}
 {readSection==='support'&&data.map(s=><details className="admin-details" key={str(s.id)}><summary>{str(s.name)} · {str(s.state)}</summary><p>Benoemde medewerker {str(s.employee_auth_user_id)} · einde {str(s.ends_at)} · bereik {str(s.scope_kind)}</p><p>Gevraagde rechten: {Array.isArray(s.permission_keys)?s.permission_keys.join(', '):'Onbekend'}</p>{s.state==='requested'&&form('consent_support',s)}{['requested','approved'].includes(str(s.state))&&form('end_support',s)}</details>)}
 {snapshot&&tab!=='catalogue'&&tab!=='templates'&&!['vacancies','volunteer_roles'].includes(tab)&&<NativeAdminWorkspace key={`${ctx.actor}:${ctx.access.tenant_id}:${selectedSeason}:${path[1]??section}`} section={section} snapshot={snapshot} resourceId={path[1]}/>}
 </>}
 {section==='cockpit'&&ctx.read.extras?.report_totals!=null&&<><ReportTotals totals={ctx.read.extras.report_totals as AdminRow}/><Link className="text-link" href={href('reports')}>Seizoensvoortgang bekijken →</Link></>}
 {!detail&&readSection!=='cockpit'&&<nav className="admin-pagination" aria-label="Pagina’s">{offset>0&&<Link href={pageHref(Math.max(0,offset-100))}>← Vorige pagina</Link>}{data.length===100&&<Link href={pageHref(offset+100)}>Volgende pagina →</Link>}<span>{typeof ctx.read.extras?.total_rows==='number'?`${ctx.read.extras.total_rows} resultaten`:data.length?`Resultaten ${offset+1}–${offset+data.length}`:'Geen resultaten'}</span></nav>}
 <form className="admin-filters" method="get"><input type="hidden" name="season" value={selectedSeason??''}/>{subSections[section]&&<input type="hidden" name="part" value={tab}/>}<label className="field"><span>Zoeken in dit onderdeel</span><input name="q" defaultValue={query.q??''} maxLength={200}/></label>{['planning','execution','report_occupancy'].includes(readSection)&&<>{[['starts_on','Vanaf'],['ends_on','Tot en met']].map(([key,label])=><label key={key} className="field"><span>{label}</span><input type="date" name={key} defaultValue={query[key]??''}/></label>)}<label className="field"><span>Commissie</span><select name="committee_id"defaultValue={query.committee_id??''}><option value="">Alle bevoegde commissies</option>{options(sources.committees??[]).map(o=><option key={o.value}value={o.value}>{o.label}</option>)}</select></label><label className="field"><span>Team</span><select name="team_id"defaultValue={query.team_id??''}><option value="">Alle bevoegde teams</option>{options(sources.teams??[]).map(o=><option key={o.value}value={o.value}>{o.label}</option>)}</select></label><label className="field"><span>Categorie</span><select name="category_id" defaultValue={query.category_id??''}><option value="">Alle bevoegde categorieën</option>{options(categories).map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="field"><span>Status</span><select name="status"defaultValue={query.status??''}><option value="">Alle statussen</option>{['draft','published','cancelled','completed'].map(status=><option key={status}value={status}>{({draft:'Concept',published:'Gepubliceerd',cancelled:'Geannuleerd',completed:'Afgerond'}as Record<string,string>)[status]}</option>)}</select></label></>}{query.queue&&<input type="hidden"name="queue"value={query.queue}/>}<button className="btn secondary" type="submit">Zoeken</button></form><p className="admin-observed">Peildatum: {new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium',timeStyle:'short',timeZone:ctx.access.timezone}).format(new Date(ctx.read.observed_at))} · actuele Cluvoadministratie</p></div>;
}
