-- Additive staging automation. No provider credential, Auth manufacture or cron
-- is created here. The hosted source-bound worker owns dispatch and receipts.
begin;
create table app.pwa_reminder_rules(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id),revision bigint not null check(revision>0),offset_minutes integer[] not null check(cardinality(offset_minutes) between 1 and 4),approved_by_auth_user_id uuid references auth.users(id),approval_kind text not null check(approval_kind in('canon_default','organization_approved')),reason text not null check(length(btrim(reason)) between 1 and 1000),created_at timestamptz not null default statement_timestamp(),version bigint not null default 1,unique(tenant_id,id),unique(tenant_id,revision),check(approval_kind='canon_default' or approved_by_auth_user_id is not null));
create table app.pwa_reminder_jobs(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id),source_kind text not null check(source_kind in('booking','team_self','team_assign')),source_id uuid not null,source_version bigint not null,source_time timestamptz not null,rule_id uuid,offset_minutes integer not null,due_at timestamptz not null,state text not null default 'scheduled' check(state in('scheduled','enqueued','superseded')),created_at timestamptz not null default statement_timestamp(),version bigint not null default 1,unique(tenant_id,id),unique(tenant_id,source_kind,source_id,source_version,rule_id,offset_minutes),foreign key(tenant_id,rule_id) references app.pwa_reminder_rules(tenant_id,id),check((source_kind='booking')=(rule_id is not null)));
create unique index pwa_team_reminder_jobs_once on app.pwa_reminder_jobs(tenant_id,source_kind,source_id,source_version,offset_minutes)where source_kind<>'booking';
create table app.pwa_automation_sources(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id),outbox_id uuid not null,source_kind text not null check(source_kind in('task_offer','daily_digest','booking','team_self','team_assign')),source_id uuid not null,source_version bigint not null,source_time timestamptz,rule_id uuid,local_date date,created_at timestamptz not null default statement_timestamp(),unique(tenant_id,id),unique(tenant_id,outbox_id),foreign key(tenant_id,outbox_id) references app.pwa_delivery_outbox(tenant_id,id),foreign key(tenant_id,rule_id) references app.pwa_reminder_rules(tenant_id,id));
create table app.pwa_automation_run_log(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references app.tenants(id),worker_id uuid not null,source_sha text not null check(source_sha~'^[0-9a-f]{40}$'),workflow_run_id text not null check(workflow_run_id~'^[1-9][0-9]{0,19}$'),actor text not null check(actor~'^[A-Za-z0-9][A-Za-z0-9_.\[\]-]{0,63}$'),scope text not null default 'staging' check(scope='staging'),result_counts jsonb not null check(jsonb_typeof(result_counts)='object'),created_at timestamptz not null default statement_timestamp(),unique(tenant_id,id));
create table app.pwa_fixture_run_sources(integration_run_id uuid primary key references app.integration_runs(id),tenant_id uuid not null references app.tenants(id),source_sha text not null check(source_sha~'^[0-9a-f]{40}$'),workflow_run_id text not null check(workflow_run_id~'^[1-9][0-9]{0,19}$'),actor text not null check(actor~'^[A-Za-z0-9][A-Za-z0-9_.\[\]-]{0,63}$'),source_kind text not null default 'cluvo-pwa-match-fixture-v1'check(source_kind='cluvo-pwa-match-fixture-v1'),created_at timestamptz not null default statement_timestamp());
create table app.pwa_offer_processing(tenant_id uuid not null references app.tenants(id),person_id uuid not null,shift_id uuid not null,publication_event_id uuid not null,created_at timestamptz not null default statement_timestamp(),primary key(tenant_id,person_id,shift_id),foreign key(tenant_id,person_id)references app.persons(tenant_id,id),foreign key(tenant_id,shift_id)references app.shifts(tenant_id,id),foreign key(tenant_id,publication_event_id)references app.domain_events(tenant_id,id));
do $privacy$ declare name text;begin
 foreach name in array array['pwa_reminder_rules','pwa_reminder_jobs','pwa_automation_sources','pwa_automation_run_log','pwa_offer_processing','pwa_fixture_run_sources']loop
 execute format('alter table app.%I enable row level security',name);execute format('alter table app.%I force row level security',name);
 execute format('revoke all on app.%I from public,anon,authenticated,service_role',name);
 execute format('create policy native_session_required on app.%I as restrictive for all to authenticated using((select internal.actor_has_active_session())) with check((select internal.actor_has_active_session()))',name);
 end loop;
end;$privacy$;
grant select,insert on app.pwa_reminder_rules to cluvo_command_owner;
create policy command_owner_read on app.pwa_reminder_rules for select to cluvo_command_owner using(true);
create policy command_owner_insert on app.pwa_reminder_rules for insert to cluvo_command_owner with check(approved_by_auth_user_id=internal.current_actor_uid());
create trigger pwa_automation_sources_immutable before update or delete on app.pwa_automation_sources for each row execute function internal.reject_immutable_change();
create trigger pwa_offer_processing_immutable before update or delete on app.pwa_offer_processing for each row execute function internal.reject_immutable_change();
create trigger pwa_fixture_run_sources_immutable before update or delete on app.pwa_fixture_run_sources for each row execute function internal.reject_immutable_change();
create trigger pwa_reminder_rules_immutable before update or delete on app.pwa_reminder_rules for each row execute function internal.reject_immutable_change();
create trigger pwa_automation_log_immutable before update or delete on app.pwa_automation_run_log for each row execute function internal.reject_immutable_change();
insert into app.pwa_reminder_rules(tenant_id,revision,offset_minutes,approval_kind,reason)select id,1,array[10080,1440],'canon_default','V1: zeven dagen en 24 uur voor de dienst' from app.tenants;
create function internal.pwa_seed_reminder_rule() returns trigger language plpgsql security invoker set search_path='' as $$begin
 insert into app.pwa_reminder_rules(tenant_id,revision,offset_minutes,approval_kind,reason)values(new.id,1,array[10080,1440],'canon_default','V1: zeven dagen en 24 uur voor de dienst');return new;end;$$;
create trigger pwa_seed_reminder_rule after insert on app.tenants for each row execute function internal.pwa_seed_reminder_rule();
revoke all on function internal.pwa_seed_reminder_rule() from public,anon,authenticated,service_role,cluvo_command_owner;

create function internal.pwa_reminder_settings(p_tenant_id uuid)returns jsonb language plpgsql stable security definer set search_path='' as $$declare v_row app.pwa_reminder_rules%rowtype;begin
 if not internal.actor_has_active_session() or not internal.has_permission(p_tenant_id,'organization.manage','tenant',p_tenant_id)then raise exception using errcode='42501',message='FORBIDDEN';end if;
 select * into strict v_row from app.pwa_reminder_rules where tenant_id=p_tenant_id order by revision desc limit 1;
 return jsonb_build_object('id',v_row.id,'version',v_row.revision,'offset_minutes',v_row.offset_minutes,'approval_kind',v_row.approval_kind);end;$$;
create function internal.pwa_set_reminder_rule(p_tenant_id uuid,p_expected_version bigint,p_offset_minutes integer[],p_reason text,p_idempotency_key uuid)returns jsonb language plpgsql security definer set search_path='' as $$
declare v_version bigint;v_id uuid;v_actor uuid:=internal.current_actor_uid();v_previous jsonb;v_result jsonb;begin
 if not internal.actor_has_active_session() or not internal.has_permission(p_tenant_id,'organization.manage','tenant',p_tenant_id)then raise exception using errcode='42501',message='FORBIDDEN';end if;
 if p_expected_version is null or p_idempotency_key is null or cardinality(p_offset_minutes) not between 1 and 4 or p_offset_minutes is null or exists(select 1 from unnest(p_offset_minutes)x where x is null or x not between 1 and 43200)or cardinality(p_offset_minutes)<>(select count(distinct x)from unnest(p_offset_minutes)x)or length(btrim(p_reason)) not between 1 and 1000 or p_reason is null then raise exception using errcode='22023',message='INVALID_REMINDER_RULE';end if;
 perform pg_advisory_xact_lock(hashtextextended('pwa-rule:'||p_tenant_id::text,0));
 v_previous:=internal.claim_idempotency(p_tenant_id,'pwa_reminder_rule',p_idempotency_key,extensions.digest(convert_to(jsonb_build_object('expected_version',p_expected_version,'offsets',p_offset_minutes,'reason',p_reason)::text,'UTF8'),'sha256'));
 if v_previous is not null then return v_previous;end if;
 select revision into strict v_version from app.pwa_reminder_rules where tenant_id=p_tenant_id order by revision desc limit 1;
 if v_version<>p_expected_version then raise exception using errcode='40001',message='STALE_VERSION';end if;
 insert into app.pwa_reminder_rules(tenant_id,revision,offset_minutes,approved_by_auth_user_id,approval_kind,reason)values(p_tenant_id,v_version+1,p_offset_minutes,v_actor,'organization_approved',p_reason)returning id into v_id;
 insert into app.audit_events(tenant_id,actor_auth_user_id,action,resource_type,resource_id,scope_kind,scope_id,reason_code,idempotency_key,payload_minimal)values(p_tenant_id,v_actor,'pwa.reminder_rule_approved','reminder_rule',v_id,'tenant',p_tenant_id,'ORGANIZATION_APPROVED',p_idempotency_key,jsonb_build_object('expected_version',p_expected_version,'new_version',v_version+1,'offset_minutes',p_offset_minutes));
 v_result:=jsonb_build_object('ok',true,'resource_id',v_id,'version',v_version+1);perform internal.finish_idempotency(p_tenant_id,'pwa_reminder_rule',p_idempotency_key,v_result);return v_result;end;$$;
create function api.pwa_reminder_settings(p_tenant_id uuid)returns jsonb language sql stable security invoker set search_path='' as $$select internal.pwa_reminder_settings(p_tenant_id);$$;
create function api.pwa_set_reminder_rule(p_tenant_id uuid,p_expected_version bigint,p_offset_minutes integer[],p_reason text,p_idempotency_key uuid)returns jsonb language sql security invoker set search_path='' as $$select internal.pwa_set_reminder_rule(p_tenant_id,p_expected_version,p_offset_minutes,p_reason,p_idempotency_key);$$;
grant create on schema api to cluvo_command_owner;
do $owners$declare r record;begin for r in select p.oid::regprocedure sig from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in('api','internal')and p.proname in('pwa_reminder_settings','pwa_set_reminder_rule')loop execute format('alter function %s owner to cluvo_command_owner',r.sig);execute format('revoke all on function %s from public,anon,authenticated,service_role',r.sig);execute format('grant execute on function %s to authenticated',r.sig);end loop;end;$owners$;
revoke create on schema api from cluvo_command_owner;

create function internal.pwa_automation_guard()returns void language plpgsql stable security invoker set search_path='' as $$begin
 if current_user<>'postgres' or current_database()<>'postgres' or pg_is_in_recovery()or current_setting('cluvo.delivery_scope',true)is distinct from 'staging' or current_setting('cluvo.delivery_project',true)is distinct from 'fbozlbgmktkgcdfqdaaz' or coalesce(current_setting('cluvo.delivery_source',true),'')!~'^[0-9a-f]{40}$' or coalesce(current_setting('cluvo.delivery_run',true),'')!~'^[1-9][0-9]{0,19}$' or coalesce(current_setting('cluvo.delivery_actor',true),'')!~'^[A-Za-z0-9][A-Za-z0-9_.\[\]-]{0,63}$' then raise exception 'STAGING_AUTOMATION_CONTEXT_REQUIRED';end if;end;$$;
create function internal.pwa_offer_usable(p_tenant_id uuid,p_person_id uuid,p_shift_id uuid)returns boolean language sql stable security invoker set search_path='' as $$
 select exists(select 1 from app.shifts s join app.tenants t on t.id=s.tenant_id where s.tenant_id=p_tenant_id and s.id=p_shift_id and t.status='active' and s.state='published' and s.starts_at>statement_timestamp()and(s.booking_opens_at is null or s.booking_opens_at<=statement_timestamp())and(s.booking_closes_at is null or s.booking_closes_at>statement_timestamp())
 and exists(select 1 from app.persons person where person.tenant_id=p_tenant_id and person.id=p_person_id and person.birth_date_precision='day'and person.birth_date+interval '16 years'<=(s.starts_at at time zone t.timezone)::date)
 and internal.pwa_executor_fits(p_tenant_id,p_person_id,p_shift_id)and internal.person_has_permission(p_tenant_id,p_person_id,'shift.book','committee',s.committee_id)
 and exists(select 1 from app.account_person_links l join auth.users u on u.id=l.auth_user_id join app.tenant_memberships m on m.tenant_id=l.tenant_id and m.auth_user_id=l.auth_user_id where l.tenant_id=p_tenant_id and l.person_id=p_person_id and l.revoked_at is null and l.verified_at is not null and u.email_confirmed_at is not null and u.deleted_at is null and(u.banned_until is null or u.banned_until<=statement_timestamp())and m.status='active'and m.starts_at<=statement_timestamp()and(m.ends_at is null or m.ends_at>statement_timestamp()))
 and exists(select 1 from app.shift_positions pos where pos.tenant_id=s.tenant_id and pos.shift_id=s.id and pos.state='open'and not exists(select 1 from app.bookings b where b.tenant_id=pos.tenant_id and b.position_id=pos.id and b.state not in('cancelled','transferred'))and not exists(select 1 from app.waitlist_offers w where w.tenant_id=pos.tenant_id and w.position_id=pos.id and w.state='active'and w.expires_at>statement_timestamp())and not exists(select 1 from app.pwa_allocations a where a.tenant_id=pos.tenant_id and a.position_id=pos.id and a.state<>'released')));
$$;
create function internal.pwa_automation_notification(p_tenant_id uuid,p_person_id uuid,p_event uuid,p_kind text,p_title text,p_body text,p_path text,p_channel text,p_source_kind text,p_source_id uuid,p_source_version bigint,p_source_time timestamptz default null,p_rule_id uuid default null,p_local_date date default null)returns integer language plpgsql security invoker set search_path='' as $$
declare v_notification uuid;v_outbox uuid;v_pref app.pwa_preferences%rowtype;v_enabled boolean;begin
 select * into v_pref from app.pwa_preferences where tenant_id=p_tenant_id and person_id=p_person_id;
 v_enabled:=case p_kind when 'news'then coalesce(v_pref.news,true)when 'reminder'then coalesce(v_pref.reminders,true)when 'team'then coalesce(v_pref.team,true)else true end;
 if not v_enabled and p_source_kind not in('booking','team_self','team_assign') then return 0;end if;
 insert into app.pwa_notifications(tenant_id,recipient_person_id,event_id,notification_kind,deliver_inbox,essential,title,body,source_path)values(p_tenant_id,p_person_id,p_event,p_kind,case when p_source_kind in('booking','team_self','team_assign')then true else coalesce(v_pref.inbox,true)end,p_source_kind in('booking','team_self','team_assign'),p_title,p_body,p_path)on conflict do nothing;
 select id into strict v_notification from app.pwa_notifications where tenant_id=p_tenant_id and recipient_person_id=p_person_id and event_id=p_event;
 if not v_enabled then return 0;end if;
 if not (case p_channel when 'email'then coalesce(v_pref.email,true)when 'push'then coalesce(v_pref.push,false)else false end) then return 0;end if;
 insert into app.pwa_delivery_outbox(tenant_id,recipient_person_id,notification_id,channel)values(p_tenant_id,p_person_id,v_notification,p_channel)on conflict do nothing returning id into v_outbox;
 if v_outbox is null then return 0;end if;
 insert into app.pwa_automation_sources(tenant_id,outbox_id,source_kind,source_id,source_version,source_time,rule_id,local_date)values(p_tenant_id,v_outbox,p_source_kind,p_source_id,p_source_version,p_source_time,p_rule_id,p_local_date);
 return 1;end;$$;

-- Closed synthetic source adapter. This never calls a live provider, reads a
-- credential or impersonates an Auth actor. Only explicitly marked QA tenants
-- and the exact compiled fixture source may use this integration connection.
create function internal.pwa_import_match_fixture(p_connection_id uuid,p_occurrence_id uuid)returns jsonb language plpgsql security invoker set search_path='' as $$
declare c app.integration_connections%rowtype;o app.scheduled_occurrences%rowtype;m app.matches%rowtype;v_run uuid;v_team uuid;v_revision integer;v_complete boolean;v_start timestamptz;v_field text;v_hash bytea;v_changed boolean:=false;v_fields text[];v_match uuid;v_match_revision uuid;begin
 perform internal.pwa_automation_guard();
 select * into strict c from app.integration_connections where id=p_connection_id for update;
 select * into strict o from app.scheduled_occurrences where id=p_occurrence_id and tenant_id=c.tenant_id for update;
 if c.provider<>'cluvo_fixture' or c.connection_key<>'cluvo-pwa-match-fixture-v1' or c.status<>'active' or c.credential_reference is not null
 or c.capabilities->>'source' is distinct from 'cluvo-pwa-match-fixture-v1' or c.capabilities->>'synthetic' is distinct from 'true'
 or coalesce(c.capabilities->>'fixture_revision','') not in('1','2') or coalesce(c.capabilities->>'complete','') not in('true','false')
 or (select count(*)from jsonb_object_keys(c.capabilities))<>5 or exists(select 1 from jsonb_object_keys(c.capabilities)k where k not in('source','synthetic','fixture_revision','complete','team_id'))
 or not exists(select 1 from app.tenants t where t.id=c.tenant_id and t.status='active'and t.branding_json->>'synthetic'='true')
 or o.job_kind<>'match_sync_fixture:'||c.id::text or o.state<>'scheduled' or o.scheduled_at>statement_timestamp()
 then raise exception 'SYNTHETIC_MATCH_SOURCE_REQUIRED';end if;
 v_team:=(c.capabilities->>'team_id')::uuid;v_revision:=(c.capabilities->>'fixture_revision')::integer;v_complete:=(c.capabilities->>'complete')::boolean;
 if not exists(select 1 from app.teams where tenant_id=c.tenant_id and id=v_team and active)then raise exception 'SYNTHETIC_MATCH_TEAM_REQUIRED';end if;
 v_run:=gen_random_uuid();
 insert into app.integration_runs(id,tenant_id,connection_id,trigger_kind,idempotency_key,cursor_before)values(v_run,c.tenant_id,c.id,'scheduled',o.id,'cluvo-pwa-match-fixture-v1:'||v_revision);
 insert into app.pwa_fixture_run_sources(integration_run_id,tenant_id,source_sha,workflow_run_id,actor)values(v_run,c.tenant_id,current_setting('cluvo.delivery_source'),current_setting('cluvo.delivery_run'),current_setting('cluvo.delivery_actor'));
 v_start:=timestamptz '2026-11-07 12:00:00+01'+case v_revision when 2 then interval '1 hour'else interval '0 hours'end;
 v_field:=case v_revision when 2 then 'Cluvo QA veld 2'else 'Cluvo QA veld 1'end;
 v_hash:=extensions.digest(convert_to(jsonb_build_object('source_id','cluvo-pwa-fixture-match-1','team_id',v_team,'opponent','Cluvo QA tegenstander','starts_at',v_start,'is_home',true,'location_text','Cluvo synthetische testlocatie','field_name',v_field,'locker_room_text',null,'status','scheduled')::text,'UTF8'),'sha256');
 select * into m from app.matches where tenant_id=c.tenant_id and connection_id=c.id and source_id='cluvo-pwa-fixture-match-1'for update;
 if m.id is null then
  v_changed:=true;v_fields:=array['created'];v_match:=gen_random_uuid();
  insert into app.matches(id,tenant_id,connection_id,source_id,team_id,opponent,starts_at,is_home,location_text,field_name,status,source_hash,last_seen_run_id)values(v_match,c.tenant_id,c.id,'cluvo-pwa-fixture-match-1',v_team,'Cluvo QA tegenstander',v_start,true,'Cluvo synthetische testlocatie',v_field,'scheduled',v_hash,v_run)returning *into m;
 elsif m.source_hash=v_hash then
  v_match:=m.id;update app.matches set last_seen_run_id=v_run,updated_at=statement_timestamp()where id=m.id;
 else
  v_changed:=true;v_match:=m.id;
  v_fields:=array_remove(array[case when m.starts_at<>v_start then 'starts_at'end,case when m.field_name<>v_field then 'field_name'end,case when m.team_id<>v_team then 'team_id'end],null);
  update app.matches set team_id=v_team,starts_at=v_start,field_name=v_field,source_hash=v_hash,last_seen_run_id=v_run,version=version+1,updated_at=statement_timestamp()where id=m.id returning *into m;
 end if;
 if v_changed then
  v_match_revision:=gen_random_uuid();insert into app.match_revisions(id,tenant_id,match_id,revision,integration_run_id,opponent,starts_at,is_home,location_text,field_name,locker_room_text,status,source_hash,changed_fields)values(v_match_revision,c.tenant_id,m.id,m.version,v_run,m.opponent,m.starts_at,m.is_home,m.location_text,m.field_name,m.locker_room_text,m.status,v_hash,v_fields);
  if v_fields<>array['created']then insert into app.match_change_impacts(tenant_id,match_revision_id,shift_id,impact_kind)select c.tenant_id,v_match_revision,shift_id,case when cardinality(v_fields)>1 then 'multiple'when 'starts_at'=any(v_fields)then 'time'else 'location'end from app.match_shift_links where tenant_id=c.tenant_id and match_id=m.id on conflict do nothing;end if;
  insert into app.domain_events(tenant_id,aggregate_type,aggregate_id,aggregate_version,event_type,payload_minimal)values(c.tenant_id,'match',m.id,m.version,case when v_fields=array['created']then 'match.imported'else 'match.changed'end,jsonb_build_object('source','cluvo-pwa-match-fixture-v1','synthetic',true,'changed_fields',v_fields));
 end if;
 -- Incomplete sources never cancel unseen matches or advance last_success.
 update app.integration_runs set status=case when v_complete then 'succeeded'else 'incomplete'end,source_complete=v_complete,seen_count=1,changed_count=case when v_changed then 1 else 0 end,cursor_after=case when v_complete then 'cluvo-pwa-match-fixture-v1:'||v_revision end,error_code=case when v_complete then null else 'SYNTHETIC_SOURCE_INCOMPLETE'end,completed_at=statement_timestamp(),updated_at=statement_timestamp(),version=version+1 where id=v_run;
 if v_complete then update app.integration_connections set last_success_at=statement_timestamp(),updated_at=statement_timestamp(),version=version+1 where id=c.id;end if;
 update app.scheduled_occurrences set state=case when v_complete then 'succeeded'else 'failed'end,completed_at=statement_timestamp(),version=version+1 where id=o.id;
 return jsonb_build_object('synthetic',true,'run_id',v_run,'changed',v_changed,'complete',v_complete);end;$$;
create function internal.pwa_sync_match_fixtures(p_worker_id uuid,p_limit integer)returns integer language plpgsql security invoker set search_path='' as $$
declare c record;o record;slot time;d date;r record;v_count integer:=0;begin
 perform internal.pwa_automation_guard();if p_worker_id is null or p_limit not between 1 and 500 then raise exception 'INVALID_AUTOMATION_BATCH';end if;
 for c in select conn.*,t.timezone from app.integration_connections conn join app.tenants t on t.id=conn.tenant_id and t.status='active'and t.branding_json->>'synthetic'='true'where conn.provider='cluvo_fixture'and conn.connection_key='cluvo-pwa-match-fixture-v1'and conn.status='active'and conn.credential_reference is null and conn.capabilities->>'source'='cluvo-pwa-match-fixture-v1'and conn.capabilities->>'synthetic'='true'order by conn.id limit p_limit loop
  d:=(statement_timestamp()at time zone c.timezone)::date;
  foreach slot in array array[time '06:00',time '18:00']loop
   select *into strict r from internal.resolve_local_slot(d,slot,c.timezone);
   insert into app.scheduled_occurrences(tenant_id,job_kind,local_date,slot_key,requested_local_time,effective_local_time,timezone,scheduled_at,dst_resolution)values(c.tenant_id,'match_sync_fixture:'||c.id::text,d,slot::text,slot,r.effective_local_time,c.timezone,r.scheduled_at,r.dst_resolution)on conflict do nothing;
  end loop;
  for o in select *from app.scheduled_occurrences where tenant_id=c.tenant_id and job_kind='match_sync_fixture:'||c.id::text and state='scheduled'and scheduled_at<=statement_timestamp()order by scheduled_at,id for update skip locked limit p_limit loop
   perform internal.pwa_import_match_fixture(c.id,o.id);v_count:=v_count+1;
  end loop;
 end loop;return v_count;end;$$;
revoke all on function internal.pwa_import_match_fixture(uuid,uuid),internal.pwa_sync_match_fixtures(uuid,integer)from public,anon,authenticated,service_role,cluvo_command_owner;

create function internal.pwa_enqueue_automation(p_worker_id uuid,p_limit integer default 100)returns jsonb language plpgsql security invoker set search_path='' as $$
declare r record;j record;v_category uuid;v_intent uuid;v_candidate uuid;v_event uuid;v_digest uuid;v_offers integer:=0;v_push integer:=0;v_digests integer:=0;v_reminders integer:=0;v_deadlines integer:=0;v_counts jsonb;v_matchslots integer;begin
 perform internal.pwa_automation_guard();if p_worker_id is null or p_limit is null or p_limit not between 1 and 500 then raise exception 'INVALID_AUTOMATION_BATCH';end if;
 -- Canonical candidates are keyed by first publication/person/shift. Changing
 -- copy or matching several roles cannot create another logical offer.
 for r in select distinct on(s.tenant_id,p.id,s.id)s.tenant_id,s.id shift_id,s.version,s.starts_at,p.id person_id,e.id event_id,e.created_at from app.shifts s join app.domain_events e on e.tenant_id=s.tenant_id and e.aggregate_id=s.id and e.event_type='task.published'join app.persons p on p.tenant_id=s.tenant_id where internal.pwa_offer_usable(s.tenant_id,p.id,s.id)and not exists(select 1 from app.pwa_offer_processing x where x.tenant_id=s.tenant_id and x.person_id=p.id and x.shift_id=s.id)order by s.tenant_id,p.id,s.id,e.created_at,e.id limit p_limit loop
  insert into app.pwa_offer_processing(tenant_id,person_id,shift_id,publication_event_id)values(r.tenant_id,r.person_id,r.shift_id,r.event_id)on conflict do nothing;if not found then continue;end if;
  insert into app.notification_categories(tenant_id,category_key,name)values(r.tenant_id,'task.offer','Nieuw passend aanbod')on conflict do nothing;
  select id into strict v_category from app.notification_categories where tenant_id=r.tenant_id and category_key='task.offer';
  insert into app.notification_intents(tenant_id,domain_event_id,recipient_person_id,category_id,channels,dedupe_key,safe_title,safe_body,source_path,status)values(r.tenant_id,r.event_id,r.person_id,v_category,array['inbox'],'task-offer:'||r.shift_id::text||':'||r.person_id::text,'Nieuwe passende taak','Er is nieuw passend aanbod in de vereniging.','/app/tasks','queued')on conflict do nothing;
  select id into strict v_intent from app.notification_intents where tenant_id=r.tenant_id and dedupe_key='task-offer:'||r.shift_id::text||':'||r.person_id::text;
  insert into app.task_offer_candidates(tenant_id,intent_id,recipient_person_id,shift_id,publication_event_id,usable_until)values(r.tenant_id,v_intent,r.person_id,r.shift_id,r.event_id,r.starts_at)on conflict do nothing returning id into v_candidate;
  if v_candidate is not null then v_offers:=v_offers+1;end if;
  v_push:=v_push+internal.pwa_automation_notification(r.tenant_id,r.person_id,r.event_id,'news','Nieuwe passende taak','Er is een nieuwe passende taak beschikbaar.','/app/tasks','push','task_offer',r.shift_id,r.version);
 end loop;
 -- A unique person/tenant/local-day row occupies the daily slot even after
 -- timeout. New candidates after this reservation wait for the next local day.
 for r in select distinct c.tenant_id,c.recipient_person_id,t.timezone,(statement_timestamp()at time zone t.timezone)::date local_day from app.task_offer_candidates c join app.tenants t on t.id=c.tenant_id left join app.pwa_preferences p on p.tenant_id=c.tenant_id and p.person_id=c.recipient_person_id where internal.pwa_offer_usable(c.tenant_id,c.recipient_person_id,c.shift_id)and coalesce(p.email,true)and coalesce(p.news,true)and not exists(select 1 from app.daily_task_digests day_slot where day_slot.tenant_id=c.tenant_id and day_slot.recipient_person_id=c.recipient_person_id and day_slot.local_date=(statement_timestamp()at time zone t.timezone)::date)and not exists(select 1 from app.daily_digest_items i where i.tenant_id=c.tenant_id and i.task_offer_candidate_id=c.id)order by c.tenant_id,c.recipient_person_id limit p_limit loop
  v_digest:=null;insert into app.daily_task_digests(tenant_id,recipient_person_id,local_date,timezone,status)values(r.tenant_id,r.recipient_person_id,r.local_day,r.timezone,'queued')on conflict do nothing returning id into v_digest;
  if v_digest is null then continue;end if;
  insert into app.daily_digest_items(tenant_id,digest_id,task_offer_candidate_id)select r.tenant_id,v_digest,c.id from app.task_offer_candidates c where c.tenant_id=r.tenant_id and c.recipient_person_id=r.recipient_person_id and internal.pwa_offer_usable(c.tenant_id,c.recipient_person_id,c.shift_id)and not exists(select 1 from app.daily_digest_items i where i.tenant_id=c.tenant_id and i.task_offer_candidate_id=c.id);
  v_event:=gen_random_uuid();insert into app.domain_events(id,tenant_id,aggregate_type,aggregate_id,aggregate_version,event_type,payload_minimal)values(v_event,r.tenant_id,'daily_digest',v_digest,1,'pwa.news',jsonb_build_object('local_date',r.local_day));
  v_digests:=v_digests+internal.pwa_automation_notification(r.tenant_id,r.recipient_person_id,v_event,'news','Nieuw passend aanbod','Bekijk je nieuwe passende taken in de vereniging.','/app/tasks','email','daily_digest',v_digest,1,null,null,r.local_day);
 end loop;
 -- Rules and source versions are append-only. Superseded future jobs remain
 -- historical; no sent or unknown provider receipt is removed or retried.
 update app.pwa_reminder_jobs current_job set state='superseded',version=current_job.version+1 where current_job.state='scheduled'and((current_job.rule_id is not null and not exists(select 1 from app.pwa_reminder_rules rr where rr.tenant_id=current_job.tenant_id and rr.id=current_job.rule_id and rr.revision=(select max(x.revision)from app.pwa_reminder_rules x where x.tenant_id=current_job.tenant_id)))or(current_job.source_kind='booking'and not exists(select 1 from app.bookings b where b.tenant_id=current_job.tenant_id and b.id=current_job.source_id and b.version=current_job.source_version and b.state in('booked','reconfirmation_required','transfer_pending')))or(current_job.source_kind<>'booking'and not exists(select 1 from app.pwa_clusters c where c.tenant_id=current_job.tenant_id and c.id=current_job.source_id and c.version=current_job.source_version and c.state='active')));
 insert into app.pwa_reminder_jobs(tenant_id,source_kind,source_id,source_version,source_time,rule_id,offset_minutes,due_at)
 select b.tenant_id,'booking',b.id,b.version,coalesce(b.pending_starts_at,b.starts_at_snapshot),rule.id,off,coalesce(b.pending_starts_at,b.starts_at_snapshot)-make_interval(mins=>off)from app.bookings b join app.tenants t on t.id=b.tenant_id and t.status='active'join lateral(select * from app.pwa_reminder_rules rr where rr.tenant_id=b.tenant_id order by revision desc limit 1)rule on true cross join unnest(rule.offset_minutes)off where b.state in('booked','reconfirmation_required','transfer_pending')and coalesce(b.pending_starts_at,b.starts_at_snapshot)>statement_timestamp()and coalesce(b.pending_starts_at,b.starts_at_snapshot)-make_interval(mins=>off)>=greatest(b.created_at,rule.created_at) and not exists(select 1 from app.pwa_reminder_jobs old where old.tenant_id=b.tenant_id and old.source_kind='booking'and old.source_id=b.id and old.source_time=coalesce(b.pending_starts_at,b.starts_at_snapshot)and old.rule_id=rule.id and old.offset_minutes=off and old.state='enqueued')on conflict do nothing;
 insert into app.pwa_reminder_jobs(tenant_id,source_kind,source_id,source_version,source_time,rule_id,offset_minutes,due_at)
 select c.tenant_id,kind,c.id,c.version,case kind when 'team_self'then c.self_until else c.assign_until end,null,0,case kind when 'team_self'then c.self_until else c.assign_until end from app.pwa_clusters c join app.tenants t on t.id=c.tenant_id and t.status='active'cross join unnest(array['team_self','team_assign'])kind where c.state='active'and(case kind when 'team_self'then c.self_until else c.assign_until end)>=c.created_at and not exists(select 1 from app.pwa_reminder_jobs old where old.tenant_id=c.tenant_id and old.source_kind=kind and old.source_id=c.id and old.source_time=case kind when 'team_self'then c.self_until else c.assign_until end and old.state='enqueued')on conflict do nothing;
 for j in select * from app.pwa_reminder_jobs where state='scheduled'and due_at<=statement_timestamp()order by due_at,id for update skip locked limit p_limit loop
  v_event:=gen_random_uuid();insert into app.domain_events(id,tenant_id,aggregate_type,aggregate_id,aggregate_version,event_type,payload_minimal)values(v_event,j.tenant_id,'reminder_job',j.id,1,case when j.source_kind='booking'then 'pwa.reminder'else 'pwa.set_followup'end,jsonb_build_object('source_kind',j.source_kind,'source_id',j.source_id,'source_version',j.source_version));
  if j.source_kind='booking'then
   for r in select executor_person_id person_id from app.bookings where tenant_id=j.tenant_id and id=j.source_id and version=j.source_version and state in('booked','reconfirmation_required','transfer_pending')loop
    perform internal.pwa_automation_notification(j.tenant_id,r.person_id,v_event,'reminder','Je dienst nadert','Controleer de actuele afspraak en instructies.','/app/agenda','email','booking',j.source_id,j.source_version,j.source_time,j.rule_id);
    v_push:=v_push+internal.pwa_automation_notification(j.tenant_id,r.person_id,v_event,'reminder','Je dienst nadert','Controleer de actuele afspraak en instructies.','/app/agenda','push','booking',j.source_id,j.source_version,j.source_time,j.rule_id);v_reminders:=v_reminders+1;
   end loop;
  else
   for r in select distinct p.id person_id from app.pwa_clusters c join app.persons p on p.tenant_id=c.tenant_id where c.tenant_id=j.tenant_id and c.id=j.source_id and c.version=j.source_version and c.state='active'and internal.can_person_view_team(c.tenant_id,p.id,c.team_id)loop
    perform internal.pwa_automation_notification(j.tenant_id,r.person_id,v_event,'team','Teamdeadline bereikt','Bekijk de teamtaken en de actuele opvolging.','/app/teams','email',j.source_kind,j.source_id,j.source_version,j.source_time,j.rule_id);
    v_push:=v_push+internal.pwa_automation_notification(j.tenant_id,r.person_id,v_event,'team','Teamdeadline bereikt','Bekijk de teamtaken en de actuele opvolging.','/app/teams','push',j.source_kind,j.source_id,j.source_version,j.source_time,j.rule_id);v_deadlines:=v_deadlines+1;
   end loop;
  end if;
  update app.pwa_reminder_jobs set state='enqueued',version=version+1 where id=j.id;
 end loop;
 v_matchslots:=internal.pwa_sync_match_fixtures(p_worker_id,p_limit);
 v_counts:=jsonb_build_object('offers',v_offers,'push',v_push,'digests',v_digests,'reminders',v_reminders,'deadlines',v_deadlines,'matchslots',v_matchslots);
 for r in select id from app.tenants where status='active'loop insert into app.pwa_automation_run_log(tenant_id,worker_id,source_sha,workflow_run_id,actor,result_counts)values(r.id,p_worker_id,current_setting('cluvo.delivery_source'),current_setting('cluvo.delivery_run'),current_setting('cluvo.delivery_actor'),v_counts);end loop;
 return v_counts;end;$$;

create function internal.pwa_revalidate_delivery(p_target_id uuid,p_worker_id uuid,p_expected_version bigint)returns jsonb language plpgsql security invoker set search_path='' as $$
declare t app.pwa_delivery_targets%rowtype;o app.pwa_delivery_outbox%rowtype;src app.pwa_automation_sources%rowtype;n app.pwa_notifications%rowtype;pref app.pwa_preferences%rowtype;v_email text;v_path text;v_eligible boolean:=false;v_items jsonb:='[]';v_subscription jsonb;begin
 perform internal.pwa_automation_guard();select * into strict t from app.pwa_delivery_targets where id=p_target_id for update;
 if t.state<>'leased'or t.lease_owner is distinct from p_worker_id or t.version<>p_expected_version then raise exception using errcode='40001',message='STALE_DELIVERY_LEASE';end if;
 select * into strict o from app.pwa_delivery_outbox where tenant_id=t.tenant_id and id=t.outbox_id;select * into strict n from app.pwa_notifications where tenant_id=o.tenant_id and id=o.notification_id;select * into pref from app.pwa_preferences where tenant_id=o.tenant_id and person_id=o.recipient_person_id;select * into src from app.pwa_automation_sources where tenant_id=o.tenant_id and outbox_id=o.id;
 select u.email,'/app/c/'||club.slug||'/notifications'into v_email,v_path from app.persons p join app.tenants club on club.id=p.tenant_id and club.status='active'join app.account_person_links l on l.tenant_id=p.tenant_id and l.person_id=p.id and l.revoked_at is null and l.verified_at is not null join auth.users u on u.id=l.auth_user_id and u.email_confirmed_at is not null and u.deleted_at is null and(u.banned_until is null or u.banned_until<=statement_timestamp())join app.tenant_memberships m on m.tenant_id=l.tenant_id and m.auth_user_id=l.auth_user_id and m.status='active'and m.starts_at<=statement_timestamp()and(m.ends_at is null or m.ends_at>statement_timestamp())where p.tenant_id=o.tenant_id and p.id=o.recipient_person_id and p.status='active'limit 1;
 v_eligible:=v_email is not null and case o.channel when 'email'then coalesce(pref.email,true)else coalesce(pref.push,false)end and case n.notification_kind when 'news'then coalesce(pref.news,true)when 'reminder'then coalesce(pref.reminders,true)when 'team'then coalesce(pref.team,true)else true end;
 if src.source_kind='task_offer'then v_eligible:=v_eligible and internal.pwa_offer_usable(o.tenant_id,o.recipient_person_id,src.source_id)and exists(select 1 from app.shifts s where s.tenant_id=o.tenant_id and s.id=src.source_id and s.version=src.source_version);
 elsif src.source_kind='daily_digest'then
  select coalesce(jsonb_agg(jsonb_build_object('shift_id',s.id,'title',s.title,'starts_at',s.starts_at,'path','/app/c/'||club.slug||'/tasks?task='||s.id::text)order by s.starts_at,s.id),'[]')into v_items from app.daily_digest_items i join app.task_offer_candidates c on c.tenant_id=i.tenant_id and c.id=i.task_offer_candidate_id join app.shifts s on s.tenant_id=c.tenant_id and s.id=c.shift_id join app.tenants club on club.id=s.tenant_id where i.tenant_id=o.tenant_id and i.digest_id=src.source_id and c.recipient_person_id=o.recipient_person_id and internal.pwa_offer_usable(c.tenant_id,c.recipient_person_id,c.shift_id);
  v_eligible:=v_eligible and jsonb_array_length(v_items)>0 and exists(select 1 from app.daily_task_digests d where d.tenant_id=o.tenant_id and d.id=src.source_id and d.recipient_person_id=o.recipient_person_id and d.local_date=src.local_date and d.status in('queued','failed'));
 elsif src.source_kind='booking'then v_eligible:=v_eligible and exists(select 1 from app.bookings b where b.tenant_id=o.tenant_id and b.id=src.source_id and b.executor_person_id=o.recipient_person_id and b.version=src.source_version and b.state in('booked','reconfirmation_required','transfer_pending')and coalesce(b.pending_starts_at,b.starts_at_snapshot)=src.source_time and coalesce(b.pending_starts_at,b.starts_at_snapshot)>statement_timestamp());
 elsif src.source_kind in('team_self','team_assign')then v_eligible:=v_eligible and exists(select 1 from app.pwa_clusters c where c.tenant_id=o.tenant_id and c.id=src.source_id and c.version=src.source_version and c.state='active'and internal.can_person_view_team(c.tenant_id,o.recipient_person_id,c.team_id));end if;
 if src.rule_id is not null then v_eligible:=v_eligible and exists(select 1 from app.pwa_reminder_rules r where r.tenant_id=o.tenant_id and r.id=src.rule_id and r.revision=(select max(x.revision)from app.pwa_reminder_rules x where x.tenant_id=o.tenant_id));end if;
 if o.channel='push'then select jsonb_build_object('endpoint',s.endpoint,'keys',jsonb_build_object('p256dh',s.p256dh,'auth',s.auth_secret))into v_subscription from app.pwa_push_subscriptions s where s.tenant_id=t.tenant_id and s.id=t.subscription_id and s.person_id=o.recipient_person_id and s.revoked_at is null;v_eligible:=v_eligible and v_subscription is not null;end if;
 return jsonb_build_object('id',t.id,'version',t.version,'channel',o.channel,'path',coalesce(v_path,'/app/'),'eligible',coalesce(v_eligible,false),'email',v_email,'subscription',v_subscription,'source_kind',src.source_kind,'digest_items',v_items,'notification_tag',n.event_id);end;$$;
create function internal.pwa_digest_delivery_receipt()returns trigger language plpgsql security invoker set search_path='' as $$declare src app.pwa_automation_sources%rowtype;begin
 select s.*into src from app.pwa_delivery_targets t join app.pwa_automation_sources s on s.tenant_id=t.tenant_id and s.outbox_id=t.outbox_id where t.id=new.target_id and s.source_kind='daily_digest';
 if src.id is not null and new.state in('sent','failed','unknown','cancelled')then update app.daily_task_digests set status=case new.state when 'sent'then 'provider_accepted'when 'unknown'then 'unknown'else 'failed'end,version=version+1,updated_at=statement_timestamp()where tenant_id=src.tenant_id and id=src.source_id;end if;return new;end;$$;
create trigger pwa_digest_delivery_receipt after insert on app.pwa_delivery_attempt_log for each row execute function internal.pwa_digest_delivery_receipt();
revoke all on function internal.pwa_automation_guard(),internal.pwa_offer_usable(uuid,uuid,uuid),internal.pwa_automation_notification(uuid,uuid,uuid,text,text,text,text,text,text,uuid,bigint,timestamptz,uuid,date),internal.pwa_enqueue_automation(uuid,integer),internal.pwa_revalidate_delivery(uuid,uuid,bigint),internal.pwa_digest_delivery_receipt()from public,anon,authenticated,service_role,cluvo_command_owner;
commit;
